### ISSUE TITLE
Dev server hangs without logging errors

### ISSUE THREAD

**Issue by ananyalohani** [tailwindlabs/tailwindcss#4715] opened 2021-06-19 16:45 UTC
### What version of Tailwind CSS are you using?

v2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.0.0

### What version of Node.js are you using?

v14.17.1

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/ananyalohani/tailwind-nextjs-bug-report

### Describe your issue

On running the server through `next dev`, the process hangs and it seems like it takes forever to load the page. When I try to quit the dev process by <kbd>ctrl</kbd> + <kbd>C</kbd> on the terminal, it doesn't quit the process correctly, as seen here:

![image](https://user-images.githubusercontent.com/61914211/122649413-5abcb100-d14b-11eb-9df8-0d11f69bdee6.png)

I had to manually force quit the node process through Activity Monitor.
Tailwind doesn't log any errors in the terminal for this. It took me a long time to figure out where I was going wrong. After hours of debugging, I finally noticed this mistake I made in `styles/tailwind.css`:

```
  .btn.link {
    @apply btn underline;
  }
```

Even though I realise what I've done is clearly wrong, Tailwind should've at least logged some errors in the console so it would save some time debugging. It definitely should not hang the dev server.

## Steps to reproduce the bug

```
  npm install
  npm run dev
```

**Comment by adamwathan** [comment] 2021-06-19 17:43
Hey sorry you lost so much time to this! 😞  This is a duplicate of this issue ultimately:

https://github.com/tailwindlabs/tailwindcss/issues/2807

It's unfortunately a _lot_ harder than it sounds to solve but would like to improve the error handling around this for sure. Going to close this in favor of the existing issue but thank you for providing a clear issue and including the reproduction.

**Closed by adamwathan** 2021-06-19 17:43 UTC

**Comment by ananyalohani** [comment] 2021-06-19 17:46
Yeah, I understand. Thanks!
