### ISSUE TITLE
[Bug]: Erratic css purging behaviour on Next.js app

### ISSUE THREAD

**Issue by hood** [tailwindlabs/tailwindcss#4365] opened 2021-05-16 14:36 UTC
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 10.2.0

### What version of Node.js are you using?

v14.6.0

### What browser are you using?

Chrome / Vivaldi / Firefox

### What operating system are you using?

Arch Linux

### Reproduction repository

#

### Describe your issue

I'm working on a personal website build with Next.js + TailwindCSS as of right now, and I've found unexpected behaviour when my CSS is getting purged on my (temporary) staging/production environment (I'm deploying directly to vercel.com using their default Next.js deployment configuration): my responsive breakpoint-related tailwindcss (all my `lg/xl:...` stuff) classes are getting purged on some builds, even if no code whatsover gets changed (I've tried by pushing new commits with no substantial modifications, and they get purged randomly on some occasions). 
I have the code and urls which point to the different deployments related to the same code which are behaving strangely, but would prefer giving access to my repository by inviting somebody, rather than by making it public.

My postcss.config.js file:
```
module.exports = {
  plugins: {
    tailwindcss: {},
    "postcss-preset-env": {},
  },
};
```

My tailwind.config.js file:
```
const colors = require("tailwindcss/colors");

module.exports = {
  purge: ["./components/**/*.tsx", "./pages/**/*.tsx"],
  darkMode: false,
  theme: {
    colors: {
      white: colors.white,
      black: colors.black,
      gray: colors.trueGray,
    },
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
  corePlugins: {
    backdropBlur: true,
  },
};
```

Visual example:
Here are two subsequent deployments stemmed from the same original commit (i've used the `redeploy` button showed in the picture)
https://i.imgur.com/KDduezZ.png

You can see that in the earlier one I've got this visual issue:
https://i.imgur.com/SRcnucJ.png

Which is completely gone in the successive deployment:
https://i.imgur.com/LPjgWz8.png

**EDIT**
The same behaviour has happened again today in an old application of mine, which I have just updated to the latest versions of Next.js/TailwindCSS. The following two deployments have stemmed from the same commit, but clearly producing radically different artifacts:
- shabang-r61x5h3z1-hood.vercel.app (screenshot: `blob:https://vercel.com/6c4aedf1-6ecb-435f-b32d-287e7d841da5`)
- shabang-mz9bitv8h-hood.vercel.app (screenshot: `blob:https://vercel.com/059777fd-2a10-496c-bd2d-c9608b2b8ead`)

**Comment by bradlc** [comment] 2021-05-19 10:55
Hey @hood. Please could you share a repository that reproduces the issue? Otherwise it is going to be incredibly difficult to debug. Thanks!

**Comment by hood** [comment] 2021-05-20 09:35
As I said, I'm willing to show give access to the repository to whoever is gonna investigate this issue, but I'd prefer to share the access privately, rather than make the repo public.

**Comment by bradlc** [comment] 2021-05-20 09:39
Sorry, I missed that! If you share it with me I will take a look 👍

**Comment by mikebarnhardt** [comment] 2021-05-21 17:54
I'm having similar issues. Might be an issue with Next or Webpack 5 caching because if I delete the `.next` folder on rebuilds it doesn't happen at all.

You can either `rm -rf .next` or `npm i -D rimraf` and add to your scripts:

```"build": "rimraf .next && next build"```

Does this solve your issue?

**Comment by patrickgaskill** [comment] 2021-05-22 03:43
I just ran into a similar issue, since I was importing `tailwind.css` directly into my `_app.tsx` like the docs suggest. For some reason this prevents responsive utility classes from being generated. Adding the tailwind directives to a `styles/globals.css` fixed it.

**Comment by Neekhaulas** [comment] 2021-05-26 10:42
Hello, I have the same issue. It seems that the patterns in the purge options are not correctly handled
```purge: ["./components/**/*.tsx", "./pages/**/*.tsx"],```

For exemple I have a component located in `./components/Subfolder1/Subfolder2/MyComponent.tsx` that will get its classes purged.

And if I use
```purge: ["./components/**/*.tsx", "./pages/**/*.tsx", "./components/Subfolder1/Subfolder2/**/*.tsx"],```
it will work.

**Comment by JoseGarciaM** [comment] 2021-05-26 19:37
I'm running the same problem and the solution @Neekhaulas gave is working for me. Apparently subfolders styles are being purged no matter what.

**Comment by JoseGarciaM** [comment] 2021-05-27 01:25
Also... it purges somethings and some don't in both solution cases. I already removed the purge option and it still doesn't appear to add all the classes in production mode, in dev mode everything works fine.

**Comment by Neekhaulas** [comment] 2021-05-27 09:50
@JoseGarciaM even by doing
```purge: {
   enabled: false,
}```
this works for me.

**Comment by JoseGarciaM** [comment] 2021-05-28 23:32
@Neekhaulas but the bundle size in production is super big =/


I found a salution to this version of Tailwind (I didn't need to implement it in past versions):

purge: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './pages/**/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './components/**/**/*.{js,ts,jsx,tsx}',
    './components/**/**/**/*.{js,ts,jsx,tsx}',
    './components/**/**/**/**/*.{js,ts,jsx,tsx}',
  ],

**Comment by JoseGarciaM** [comment] 2021-05-28 23:33
@Neekhaulas but the bundle size in production is super big =/

I found a salution to this version of Tailwind (I didn't need to implement it in past versions):
```
purge: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './pages/**/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './components/**/**/*.{js,ts,jsx,tsx}',
    './components/**/**/**/*.{js,ts,jsx,tsx}',
    './components/**/**/**/**/*.{js,ts,jsx,tsx}',
  ],
```

**Comment by adamwathan** [comment] 2021-06-04 18:23
Going to close this since no one has provided a reproduction — I really want to fix this but we need a repo to play with to figure it out. Hoping by closing this that the next person who has this issue will open a new issue and include a reproduction (even if it is super intermittent). Leaving it open just attracts a lot of "+1" style comments that unfortunately don't get us any closer to a solution.

Both @bradlc and @RobinMalfait have spent several hours independently trying to reproduce this issue but haven't been able to get it to happen (at least not when using `TAILWIND_DISABLE_TOUCH=true` so there must be some other missing piece of the puzzle and we'll need a project that is affected by this issue to see what we're doing differently.

If you find this issue and are having the same problem, **please open a new issue and include a repository that demonstrates the issue** and we will 100% work to fix it.

**Closed by adamwathan** 2021-06-04 18:23 UTC

**Comment by Neekhaulas** [comment] 2021-06-04 18:56
Updating from 2.1.2 to 2.1.4 has solved the issue for me.

**Comment by hood** [comment] 2021-06-16 08:41
@adamwathan I've sent an e-mail to @bradlc as of today. I'll wait for his reply then both him and, you and every other TailwindCSS maintainer is more than welcome to investigate the issue in my repository.
