### ISSUE TITLE
Backdrop Filter doesn't animate with Transition

### ISSUE THREAD

**Issue by greghesp** [tailwindlabs/tailwindcss#4001] opened 2021-04-07 12:57 UTC
### What version of Tailwind CSS are you using?

2.1.1

### What version of Node.js are you using?

v14.15

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

http://somup.com/crfilsbsDB

I have a Modal component using Transition from `@headlessui/react`, full code below.

As you can see from the screen capture, the modal itself works, however the background div doesn't seem to work as expected, there are a couple of issues I have noticed

1) If you apply a background color class `bg-red-900` to the div, it does not apply.  If you force it with a style `style={{backgroundColor: "red"}}` then this works.

2) As demonstrated in the video, the backdrop filter only applies once the transition has fully completed.  I thought the way the transition element worked was it'd transition the entire child in as is?

```
<div className="fixed transition inset-0 backdrop-filter backdrop-blur-sm"/>
```

```jsx
import React, { useState } from 'react'
import { Transition } from '@headlessui/react'
import cx from 'classnames'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faTimes } from '@fortawesome/free-solid-svg-icons'

export function ModalCore({
    show,
    closeModal,
    title = 'Title',
    children,
    width = 'default',
}) {
    return (
        <Transition
            show={show}
            enter="ease-out duration-300"
            enterFrom="opacity-0"
            enterTo="opacity-100"
            leave="ease-in duration-200"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
        >
            <div className="fixed z-50 inset-0 overflow-y-auto">
                <div className="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
                    <div
                        className="fixed transition inset-0 backdrop-filter backdrop-blur-sm"
                        aria-hidden="true"
                        onClick={() => closeModal()}
                    >
                        <div className="absolute inset-0" />
                    </div>
                    <span
                        className="hidden sm:inline-block sm:align-middle sm:h-screen"
                        aria-hidden="true"
                    >
                        &#8203;
                    </span>

                    <div
                        className={cx(
                            'inline-block align-bottom bg-gray-600 rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle  sm:w-full sm:p-6',
                            {
                                'sm:max-w-2xl': width === 'large',
                                'sm:max-w-lg': width === 'default',
                            }
                        )}
                    >
                        <div className="hidden sm:block absolute top-0 right-0 pt-4 pr-4">
                            <button
                                onClick={() => closeModal()}
                                type="button"
                                className="rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
                            >
                                <span className="sr-only">Close</span>
                                <FontAwesomeIcon icon={faTimes} />
                            </button>
                        </div>
                        <div className="sm:flex sm:items-start text-gray-100">
                            <div className="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                                <h3
                                    className="text-lg leading-6 font-medium"
                                    id="modal-title"
                                >
                                    {title}
                                </h3>
                                <div className="mt-2">{children}</div>
                            </div>
                        </div>
                        <div className="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
                            <button
                                type="button"
                                className="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-red-600 text-base font-medium text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm"
                            >
                                Deactivate
                            </button>
                            <button
                                onClick={() => closeModal()}
                                type="button"
                                className="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:w-auto sm:text-sm"
                            >
                                Cancel
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </Transition>
    )
}
```

**Comment by adamwathan** [comment] 2021-05-07 17:07
Hey! Looked into this and did the work to get it all working on my machine — it works fine in Safari but not in Chrome. Looks like Chrome just can't really animated backdrop filters well yet :/

https://stackoverflow.com/questions/61785743/how-to-animate-backdrop-filter

So going to close this as unfortunately nothing we can really do on our end, just a browser thing.

**Closed by adamwathan** 2021-05-07 17:07 UTC

**Comment by greghesp** [comment] 2021-05-07 17:33
Well, that is not the answers I was expecting 😂. Surprised Safari supports something Chrome doesn't! Thanks for looking.

**Comment by JayBox325** [comment] 2024-12-23 19:30
3 years later and this is still an issue with animating the opacity of an element that has backdrop blur.

**Comment by zackdotcomputer** [comment] 2025-01-14 17:58
To be fair, this is a webkit bug and not a Tailwind bug. Whether you're using Tailwind or raw css, if you apply the the opacity transition and a backdrop blur to the SAME element, then it works fine. If you apply the opacity transition to a parent and then the backdrop blur to a child of that parent, that is when you run into the edge case where the blur flickers in and out as the animation runs.

That is to say this will work:
```jsx
<div className={"transition-all backdrop-blur " + isShown ? "opacity-100" : "opacity-0"}>Your Stuff</div>
```

This will have bugs in Webkit
```jsx
<div className={"transition-all " + isShown ? "opacity-100" : "opacity-0"}>
  <div className="backdrop-blur">Your Stuff</div>
</div>
```

**Comment by JayBox325** [comment] 2025-01-16 12:17
I resolved this by using a pseudo element to be the backdrop blur for the parent element, as has been highlighted, it's the nature of this CSS property.

**Comment by verheyenkoen** [comment] 2025-01-17 12:49
> I resolved this by using a pseudo element to be the backdrop blur for the parent element, as has been highlighted, it's the nature of this CSS property.

@JayBox325 Can you provide an example of what you are doing?

**Comment by JayBox325** [comment] 2025-01-17 13:06
I used it to make the backdrop of navigation child elements blurred, but here's a super minimal reproduction. I didn't use a pseudo element for this example to keep the HTML clearer.

https://codepen.io/jaybox325/pen/PwYBqvv

**Comment by SHxKM** [comment] 2025-02-12 19:00
> I used it to make the backdrop of navigation child elements blurred, but here's a super minimal reproduction. I didn't use a pseudo element for this example to keep the HTML clearer.
> 
> https://codepen.io/jaybox325/pen/PwYBqvv

Thank you. This saved my night.
