### ISSUE TITLE
Tailwind v2.2.7 - group-hover Animation Does Not Work

### ISSUE THREAD

**Issue by ConnorMarble** [tailwindlabs/tailwindcss#5216] opened 2021-08-15 15:56 UTC
### What version of Tailwind CSS are you using?

2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

Nextjs

### What version of Node.js are you using?

11.1.0

### What browser are you using?

chrome

### What operating system are you using?

windows

### Reproduction repository

https://github.com/ConnorMarble/tailwindcss-2.2.7-bug

### Describe your issue

# About
Tailwind 2.2.7 has a bug where the group-hover class does not work. I have tested this by downgrading to Tailwind 2.1.1 and have no issues.

# Getting Started
First, run the npm install or yarn.

Then start the server:

npm run dev
or
yarn dev
Open http://localhost:3000 with your browser to see the result.

# Reproduce
Simply try to hover over the icon on the page. The HomeIcon should bounce on hover.

Try downgrading to v2.1.1 and it should work.

**Comment by adamwathan** [comment] 2021-08-15 18:50
Weird one, thanks for reporting. Here's a minimal reproduction we can use to troubleshoot this when we have a chance:

https://play.tailwindcss.com/us4tcBYN3H

**Comment by FallDownTheSystem** [comment] 2021-08-16 08:45
Is this a duplicate of https://github.com/tailwindlabs/tailwindcss/issues/4705?

**Comment by bradlc** [comment] 2021-08-16 14:47
> Is this a duplicate of #4705?

Looks like it 👍

**Closed by bradlc** 2021-08-16 14:47 UTC

**Comment by infothien** [comment] 2021-08-17 01:34
Sorry not sure @adamwathan , but your example doesn't seem to work for me, could you double check it please ! 

https://user-images.githubusercontent.com/30365498/129649592-ba6b70bb-a722-446e-9d65-78ed83030fb1.mov
