### ISSUE TITLE
JIT Missing Gradient Stops 

### ISSUE THREAD

**Issue by XavierGeerinck** [tailwindlabs/tailwindcss#4807] opened 2021-06-25 18:30 UTC
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

Next,.js 10.0.9

### What version of Node.js are you using?

v16.1.0

### What browser are you using?

Edge (Chromium)

### What operating system are you using?

Windows

### Reproduction repository

before:bg-gradient-to-r before:from-transparent before:to-primary-500/50

### Describe your issue

When entering `before:bg-gradient-to-r before:from-transparent before:to-primary-500/50` as the configuration for a linear gradient, it appears that the JIT is not adding the `--tw-gradient-stops` variable?

This is what I see when inspecting:

```css
.before\:bg-gradient-to-r::before {
    content: "";
    background-image: linear-gradient(to right, var(--tw-gradient-stops));
```

But when hovering over `--tw-gradient-stops` it shows: "--tw-gradient-stops is not defined"

**Comment by adamwathan** [comment] 2021-06-26 13:14
Hey! Works here:

https://play.tailwindcss.com/CNlAvxrUlo

Make sure you use `bg-gradient-to-l` though and don't use `from-transparent`, we do transparent by default and do it in a clever way to work properly in Safari because it doesn't support the "transparent" keyword in gradients properly.

Closing but if it's still an issue please open a new one with an actual reproduction, it's a required field, thanks ❤️

**Closed by adamwathan** 2021-06-26 13:14 UTC
