### ISSUE TITLE
Tailwind Cli doesn't support nested classes

### ISSUE THREAD

**Issue by jaschaio** [tailwindlabs/tailwindcss#7691] opened 2022-02-27 09:14 UTC
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/7216

<div type='discussions-op-text'>

<sup>Originally posted by **cvkmohan** January 26, 2022</sup>
Firstly, thanks for a great framework.
I am working with Phoenix, and have integrated Tailwind CLI v 3.0.15 into my application.
However, I have observed that the nested css classes are not working well. Going via the JS bundler approach is the only alternative or am I making any mistake in configuring?

</div>

**Comment by jaschaio** [comment] 2022-02-27 09:22
Workaround just using the postcss cli:

```
npm i tailwindcss postcss postcss-cli autoprefixer
```

```
// postcss.config.js
module.exports = {
    plugins: {
        'tailwindcss/nesting': {},
        tailwindcss: {
            config: './tailwind.config.cjs',
        },
        autoprefixer: {},
    },
};
```

```diff
// package.json
- "dev:css": "tailwindcss -w -i  app.css -o dist/css/app.css",
+ "dev:css": "postcss -w  app.css -o dist/css/app.css",
```

**Comment by adamwathan** [comment] 2022-02-27 13:35
Closing in favor of the discussion, this is a feature request and not a bug 👍🏻

**Closed by adamwathan** 2022-02-27 13:35 UTC

**Comment by lance-anderson** [comment] 2022-07-19 01:41
Plus one for the feature request and ditto on all the amazing goodness in the framework and library.

Thanks @jaschaio for the workaround.
