### ISSUE TITLE
Styling Not Being Applied in NextJS-13

### ISSUE THREAD

**Issue by delfincortesb** [tailwindlabs/tailwindcss#10161] opened 2022-12-22 23:58 UTC
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/9936

<div type='discussions-op-text'>

<sup>Originally posted by **MattHeslington** November 25, 2022</sup>
Hello,

I'm experiencing a really strange issue with the experimental version of NextJs13 whereby styling is not being applied despite the rules being present in the static stylesheet. I have tried both the TS and JS implementations of Next, and have tried different browsers too.

I've folowed both the instructions on the Tailwind site, and those on the Next site for implementing Tailwind. Nothing has worked correctly.

Here we can see a div with 3 Tailwind classes, but only font-bold is being honoured:

![Screenshot 2022-11-25 at 19 17 11](https://user-images.githubusercontent.com/8208896/203975210-7c8343fa-8a51-42a1-af41-4448d7a99948.jpg)

I thought that maybe there was an issue with the classes not being compiled, but looking at the static stylesheet, they are there:

![Screenshot 2022-11-25 at 19 16 29](https://user-images.githubusercontent.com/8208896/203975444-53ab2f1f-347c-4749-99cc-09f5fd56704f.jpg)

The only way I can get the classes to show is to manually reload or refresh the browser, but obviously this isn' t ideal in a large app.

I have raised this in a discussion on the Next repo, but have received no answers as yet. Does anyone know what's causing this, please?

Cheers, Matt</div>

**Comment by adamwathan** [comment] 2022-12-23 00:44
Duplicate of this perhaps? https://github.com/tailwindlabs/tailwindcss/issues/9954

**Comment by adamwathan** [comment] 2022-12-23 03:00
Closing in favor of the other issue since this appears to be the same issue. In future please don’t create issues from discussions, we only accept issue that follow the issue template 🙏

**Closed by adamwathan** 2022-12-23 03:00 UTC
