### ISSUE TITLE
Watch doesn't deliver changes when using Sass and Tailwind

### ISSUE THREAD

**Issue by lexo-mpuzovic** [tailwindlabs/tailwindcss#6714] opened 2021-12-24 08:07 UTC
-   Laravel Mix Version: 6.0.39 (`npm list --depth=0`)
-   Node Version (`node -v`): 17.0.1
-   NPM Version (`npm -v`): 8.1.0
-   OS: macOS Monterey v12.1
-   Browser: Chrome

### Description:

Hi, I'm using Laravel Mix with Tailwind 3.0.7.

This is mine `webpack.mix.js` file:

```
const mix = require('laravel-mix');
const tailwindcss = require('tailwindcss');

mix
  .setPublicPath('dist')
  .browserSync({
    proxy: "http://localhost:10004",
    files: [
      'dist/**/**',
      'resources/**/**',
      '**/*.php',
    ],
  });

mix
  .js('resources/scripts/app.js', 'js')
  .js('resources/scripts/admin.js', 'js')
  .js('resources/scripts/tinymce-buttons.js', 'js')
  .autoload({
    jquery: [
      '$',
      'window.jQuery',
    ],
  });

mix
  .sass('resources/styles/app.scss', 'css')
  .sass('resources/styles/admin.scss', 'css')
  .sass('resources/styles/editor.scss', 'css');

mix
  .options({
    processCssUrls: false,
    postCss:        [
      tailwindcss('./tailwind.config.js'),
    ],
  });

mix
  .copy('resources/images', 'dist/images')
  .copy('resources/fonts', 'dist/fonts');

mix
  .version()
  .sourceMaps();
```

This is the content of `tailwind.config.js` file:

```
module.exports = {
  mode:    'jit',
  content: [
    './**/*.php',
    './resources/scripts/*.js',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

### Steps To Reproduce:

Everything works fine except watch. If I use commands `npx mix build` or `npx mix --production` it builds properly everything. But if I use `npx mix watch` it starts server with port 8000 and it reloads page properly after I make some change but build is not fresh. Not only that it doesn't compile changes on Tailwind classes but also other changes in my scss files. Basically it always delivers old files created after last `npx mix build`.

If I remove this part

```
    postCss:        [
      tailwindcss('./tailwind.config.js'),
    ],
```

or even this line only

```
      tailwindcss('./tailwind.config.js'),
```

then all changes in scss files are properly compiled when using `npx mix watch`.

Did anyone had some problems like these? Am I doing something wrong?

**Comment by LouieMartin** [comment] 2022-01-02 07:16
Same problem :(

**Comment by thecrypticace** [comment] 2022-01-03 19:45
Hey, appreciate the report.

I've tried for about 15m and I'm unable to reproduce this. Browsersync refreshes and injects the CSS just as I expect. Would you mind prepping a reproduction (even if it's not quite minimal) — or at the very least more details about your setup?

**Comment by reinink** [comment] 2022-01-06 13:38
Hey folks, we'd love to help here, but without a minimal reproduction repo there isn't much we can do. I'm going to close this, but feel free to submit a reproduction and we'll happily have another look 👍

**Closed by reinink** 2022-01-06 13:38 UTC
