### ISSUE TITLE
Scale vs group-hover

### ISSUE THREAD

**Issue by santaimark** [tailwindlabs/tailwindcss#2457] opened 2020-09-27 22:08 UTC
### Describe the problem:

Scale property doesn't work in group-hover.

### Config:

```
 // tailwind.config.js
module.exports = {
  variants: {
    // ...
    scale: ['responsive', 'hover', 'focus', 'active', 'group-hover'],
  }
}
```

### Simple code example:
```
<div class="w-32 h-32 bg-pink-500 hover:bg-blue-500 group">
  <p class="pt-10 transform group-hover:scale-110">Hi!</p>
</div>
```

Other properties, like background, work flawlessly.

**Comment by smetzdev** [comment] 2020-09-28 09:32
Hey, would love to help, can you provide a reproduction repo? 
(Because "it works on my machine" with the exact same code 🙈)

**Comment by IRediTOTO** [comment] 2020-10-03 09:41
me too. something not true here :D

**Comment by adamwathan** [comment] 2020-10-04 16:34
This is working as expected here:

https://tailwind.run/evtRCw

Closing but feel free to open a new issue that links to an actual reproduction if it's still a problem.

**Closed by adamwathan** 2020-10-04 16:34 UTC
Labels: needs reproduction

**Comment by Kyoss79** [comment] 2021-01-20 09:11
Just FYI:
I am having the same issue using
@tailwindcss/postcss7-compat@^2.0.2 and extracted components in a laravel project.

**Comment by splurtcake** [comment] 2021-02-10 08:34
I'm having the same issue

```
"devDependencies": {
    "@nuxtjs/eslint-config": "^3.1.0",
    "@nuxtjs/eslint-module": "^2.0.0",
    "@nuxtjs/google-fonts": "^1.2.0",
    "@nuxtjs/storybook": "^3.3.0",
    "@nuxtjs/tailwindcss": "^3.1.0",
    "@storybook/addon-a11y": "^6.1.11",
    "@storybook/addon-storysource": "^6.1.11",
    "autoprefixer": "^9",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.10.0",
    "eslint-config-prettier": "^6.12.0",
    "eslint-plugin-nuxt": "^1.0.0",
    "eslint-plugin-prettier": "^3.1.4",
    "postcss": "^7",
    "prettier": "^2.1.2",
    "tailwindcss": "^2.0.1-compat"
  }
  ```

**Comment by elilovna** [comment] 2021-02-15 21:06
I have the same issue with `tailwindcss` 2.0.2. Similar code works in pure html/css from the example @adamwathan provided, but not in React

**Comment by Easaaa** [comment] 2021-03-24 10:52
I have the same issue with Next.js

**Comment by miguel-krasamo** [comment] 2021-03-26 20:53
> I have the same issue with Next.js

Try adding the next code to your variants at your tailwind config file: 

```
  extend: {
      scale: ['group-hover']
    },
  },
```
And remember to use transform class
