### ISSUE TITLE
Tailwind vs StencilJs style scoping

### ISSUE THREAD

**Issue by petrosalema** [tailwindlabs/tailwindcss#1985] opened 2020-06-29 19:04 UTC
There is a bug when using Tailwind's  [pseudo-class variants](https://tailwindcss.com/docs/pseudo-class-variants)  (colon-prefixed classes) together with Stencil's [scoped styling](https://stenciljs.com/docs/styling#scoped-css).

Please see the scenario below:

```
import { Component, h } from '@stencil/core';

@Component({
    // Works when this is set to false. Fails when set to true.
    scoped: true,
    tag: 'my-test-component'
})
export class MyTestComponent {

    //  Notice the class attribute value.
    render() {
        return <div class="hover:bg-blue-500">Hover over me</div>;
    }

}
```

This should result in css like this:
```.focus.sc-my-test-component\:bg-blue-500:hover { background-color: blue; }```
_(The "**:**" in front of "**bg-blue-500**" is escaped.)_

Instead what is generated is wrong css like this:
```.focus\.sc-my-test-component:bg-blue-500:hover { background-color: blue; }```
_(The "**:**" in front of "**bg-blue-500**" is not escaped. Instead the "**.**" in front of "**sc-my-test-component**" is.)_

**Comment by adamwathan** [comment] 2020-07-07 17:47
Can you create a simple project that reproduces the issue? We got a lot of issues that require me to manually recreate someone's project from scratch and I unfortunately just don't have time for that so things end up going unfixed. If you can provide something I can clone and start troubleshooting with right away it's much easier for me to find time to diagnose and fix the issue.

**Comment by adamwathan** [comment] 2020-07-30 11:56
Closing this since no reproduction provided, if it's still an issue happy to take a look again if you can open a new issue with a reproduction 👍

**Closed by adamwathan** 2020-07-30 11:56 UTC
Labels: needs reproduction
