### ISSUE TITLE
Max-h-* is not working 

### ISSUE THREAD

**Issue by eminaydin** [tailwindlabs/tailwindcss#3119] opened 2020-12-17 08:22 UTC
I am using tailwind in my project where I have noticed no single problem at all. But when I try to set maxHeight with the default values from Tailwind, no css is applied. For example if I give ```max-h-80``` to any element it is not working but if I set a value for this class in ```tailwind.config.js``` file then I get the styles. Seems like there is a bug with the corresponding issue.

**Comment by adamwathan** [comment] 2020-12-17 15:50
Hey! I can't reproduce this, as you can see here it is working as expected:

https://play.tailwindcss.com/GXM6e3GptJ

Closing since no reproduction was provided, please follow the issue template if you would like more help.

**Closed by adamwathan** 2020-12-17 15:50 UTC

**Comment by dejurin** [comment] 2021-01-18 18:33
I have these problem

**Comment by Kitisaks** [comment] 2022-01-04 05:24
i got this problem too. tailwind v3 + esbuild (no webpack) + phoenix framework

**Comment by mwaddoups** [comment] 2022-01-11 09:13
Just a note here for people that this is happening to - this seems to happen if you don't have a `postcss.config.js` file in your root (alongside `tailwind.config.js`). I got caught out by this when upgrading to the new tailwind as I only had `tailwind.config.js`.

Running `npx tailwindcss init -p` in your root will generate a new, empty one. When this was added I found all the styles were working properly.

**Comment by shivakilaru** [comment] 2022-03-09 19:42
For anyone else running into this, it can happen if you put your custom `maxHeight` values in `tailwind.config.js` under `theme.maxHeight` instead of `theme.extend.maxHeight`. Setting `theme.maxHeight` means that Tailwind will only pull in the `maxHeight` custom values you specify.

Docs: https://tailwindcss.com/docs/max-height#customizing-your-theme

**Comment by GalahadXVI** [comment] 2023-10-04 11:13
I've just had the same issue. Spent about 1 hour scratching my head why everything else would work but max-h-*.

I re-ran `npm run dev` and it started working again. Odd. Only seemed to affect max-h-*. Any other class (even if I've never used it before) seemed to be fine.

**Comment by arackaf** [comment] 2023-10-30 04:40
I bumped into this. Problem was me, not tailwind. Make sure you're doing 

class="max-h-[390px]"

as opposed to

class=`max-h-[${maxHeight}]`

The latter will fail silently, since tailwind needs a statically readable value at build-time, from the source file.

**Comment by naourass** [comment] 2024-04-11 08:51
I just encountered this issue with "max-h-*", rerunning npm dev seems to fix it, but this is an odd one 😁

**Comment by acewert** [comment] 2024-04-13 20:28
I had this problem with max-w-* classes, they just weren't being built into the styles (weirdly, the -md/-lg type classes worked, as did arbitrary -[100px] values, but not the -16, -24 etc.) Restarting run dev didn't fix it, but updating tailwind/postcss and rerunning the server did.

**Comment by lxl-sql** [comment] 2024-07-03 02:54
I think you can edit the `tailwind.config.js` file
For example
![image](https://github.com/tailwindlabs/tailwindcss/assets/73693935/3a4b1db1-9876-49a5-aaba-4d7c821a022f)
