### ISSUE TITLE
TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by marcin-stasiak** [tailwindlabs/tailwindcss#6393] opened 2021-12-11 11:07 UTC
**What version of Tailwind CSS are you using?**

v3.0.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Next 12.0.7

**What version of Node.js are you using?**

v14.18.2

**What browser are you using?**

Chrome

**What operating system are you using?**

Linux

**Describe your issue**

Compile error after import globals.css

```
error - ../../node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!../../node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./stylesheets/globals.css
TypeError: Cannot read property 'config' of undefined
```

**Comment by bolshoytoster** [comment] 2021-12-11 12:47
It appears the error is thrown in either `src/lib/setupWatchingContext.js` or `src/lib/setupTrackingContext.js`:

https://github.com/tailwindlabs/tailwindcss/blob/8a4b2f0627126d5ff160540f52d848ebec0c9cd7/src/lib/setupWatchingContext.js#L187-L189

The error occurs  when a null/undefined value is passed to the `tailwindcss` function.

**Comment by bolshoytoster** [comment] 2021-12-11 13:03
Adding a '?' to these should either remove the issue or just move it elsewhere.

**Comment by marcin-stasiak** [comment] 2021-12-11 14:17
@bolshoytoster  I tried your solution but i still get an error. This time:

```
error - ../../node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!../../node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!./stylesheets/globals.css
TypeError: Cannot read properties of undefined (reading 'corePlugins')
    at Array.map (<anonymous>)

```

**Comment by bolshoytoster** [comment] 2021-12-11 14:56
@marcin-stasiak That error comes from `normalize` in `tailwindcss/src/util/resolveConfig.js`

https://github.com/tailwindlabs/tailwindcss/blob/8a4b2f0627126d5ff160540f52d848ebec0c9cd7/src/util/resolveConfig.js#L222-L224

There should be a default config that is used if one isn't given.

Out of interest - could you give your `tailwind.config,js` (or just the `module.exports = {}` bit)

**Comment by reinink** [comment] 2021-12-16 19:04
Is this still an issue? I can see that you submitted #6399, and then immediately closed it, so I am going to assume that you found out what was wrong with your local setup.

In these situations we *really need* a minimal reproduction as required in the issue template:

> A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

I am going to close this — but feel free to provide a minimal reproduction, and I'd be happy to have another look 👍

**Closed by reinink** 2021-12-16 19:04 UTC

**Comment by vlechemin** [comment] 2022-03-09 23:00
If you have this, create a file `tailwind.config.js` in the root folder.

**Comment by TimotiusAnrez** [comment] 2022-03-11 08:05
it works, thank you.

I am working in Next.js and Electron stack, don't have much support on this stack so really glad to find an answer.

**Comment by wanjas** [comment] 2022-03-28 14:25
Thank you for the hint.

But instead of putting tailwind.config to the root you can do the following:

```javascript
/* postcss.config.js */
const path = require('path');

module.exports = {
  plugins: {
    tailwindcss: {
      config: path.join(__dirname, 'tailwind.config.js'),
    },
    autoprefixer: {},
  },
};
```

```javascript
/* tailwind.config.js */
const path = require('path');

module.exports = {
  content: [
    path.join(__dirname, './pages/**/*.{js,ts,jsx,tsx}'),
    path.join(__dirname, './components/**/*.{js,ts,jsx,tsx}'),
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

```

**Comment by mkdirnow** [comment] 2022-04-02 06:12
> 谢谢你的提示。
> 
> 但是，您可以执行以下操作，而不是将 tailwind.config 放到根目录：
> 
> ```js
> /* postcss.config.js */ 
> const  path  =  require ( 'path' ) ;
> 
> 模块。出口 =  {
>   插件：{ 
>     tailwindcss：{
>       配置：路径。join ( __dirname ,  'tailwind.config.js' ) , 
>     } , 
>     autoprefixer : { } , 
>   } , 
> } ;
> ```
> 
> ```js
> /* tailwind.config.js */ 
> const  path  =  require ( 'path' ) ;
> 
> 模块。出口 =  {
>   内容：[
>     路径。加入（__dirname ， './pages/**/*.{js,ts,jsx,tsx}' ），
>     路径。join ( __dirname ,  './components/**/*.{js,ts,jsx,tsx}' ) , 
>   ] ,
>   主题: {
>     扩展: { } , 
>   } ,
>   插件: [ ] , 
> } ;
> ```

Nice!

**Comment by Explosion-Scratch** [comment] 2022-06-08 19:53
This happened to me as well, it turned out to be due to a `process.chdir(...)` call that I had run, and then never changed back to the root dir. Somehow this was messing with tailwind.

**Comment by Nicholaiii** [comment] 2022-07-01 10:14
> Thank you for the hint.
> 
> But instead of putting tailwind.config to the root you can do the following:
> 
> ```js
> /* postcss.config.js */
> const path = require('path');
> 
> module.exports = {
>   plugins: {
>     tailwindcss: {
>       config: path.join(__dirname, 'tailwind.config.js'),
>     },
>     autoprefixer: {},
>   },
> };
> ```
> 
> ```js
> /* tailwind.config.js */
> const path = require('path');
> 
> module.exports = {
>   content: [
>     path.join(__dirname, './pages/**/*.{js,ts,jsx,tsx}'),
>     path.join(__dirname, './components/**/*.{js,ts,jsx,tsx}'),
>   ],
>   theme: {
>     extend: {},
>   },
>   plugins: [],
> };
> ```

This is clearly the superior solution than having to maintain two tailwind configs! :) Thank you.

**Comment by beginnerZzt** [comment] 2022-08-28 02:14
0

I ran into this problem too and I solved it by:

Create a new project, move the important files in the old project (for me, all the src files in the Vue project), then start the project, success!

**Comment by njsaugat** [comment] 2023-12-21 09:02
> Thank you for the hint.
> 
> But instead of putting tailwind.config to the root you can do the following:
> 
> ```js
> /* postcss.config.js */
> const path = require('path');
> 
> module.exports = {
>   plugins: {
>     tailwindcss: {
>       config: path.join(__dirname, 'tailwind.config.js'),
>     },
>     autoprefixer: {},
>   },
> };
> ```
> 
> ```js
> /* tailwind.config.js */
> const path = require('path');
> 
> module.exports = {
>   content: [
>     path.join(__dirname, './pages/**/*.{js,ts,jsx,tsx}'),
>     path.join(__dirname, './components/**/*.{js,ts,jsx,tsx}'),
>   ],
>   theme: {
>     extend: {},
>   },
>   plugins: [],
> };
> ```

this really worked for me. Thanks.

**Comment by sk29110** [comment] 2023-12-26 17:38
Sorry the issue is related to specific OS, npm version, or tailwind library? Why all the sudden I am seeing this problem?

**Comment by shinyatentree** [comment] 2023-12-26 17:45
Sorry why all the sudden it started appearing? Is it some specific issue on OS, npm version, or specific package version issue?

**Comment by njsaugat** [comment] 2023-12-27 14:01
I had this problem because I wasn't configuring the config file properly. I was using tailwind.config.ts instead of tailwind.config.js.
