### ISSUE TITLE
Watch issues on Docker on Windows

### ISSUE THREAD

**Issue by Sieabah** [tailwindlabs/tailwindcss#6343] opened 2021-12-10 09:10 UTC
**What version of Tailwind CSS are you using?** 

3.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

ng build (Angular)

**What version of Node.js are you using?**

Docker node:v14

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows, but app is built within Docker

**Describe your issue**

JIT is a great concept until the expected watch API doesn't work. When working within a docker container on windows file events are not correctly propagated. This creates issues for build systems that do not support polling.

I got around this in v2.2 by disabling purge in development mode and enabling it for builds. Now with JIT the styles are not properly recreated when I change a component template.

**Comment by eblaauw** [comment] 2021-12-10 10:30
Same issue here - I've tried:

`purge: false`
`purge: []`
`purge: ['*']`
`content: []`
`content: ['*']` 

and they all did not work.

**Comment by RobinMalfait** [comment] 2021-12-10 10:49
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a **minimal** reproduction repo with docker that showcases this issue?

**Comment by blackjak231** [comment] 2021-12-10 10:51
By looking at the normalizer in tailwind, it seems the `purge.enabled` option has completely disappeared from the options.

Is it possible to disable the purge any other way ?

**Comment by oller** [comment] 2021-12-10 11:01
It seems 

> Since Tailwind no longer uses PurgeCSS under the hood

https://tailwindcss.com/docs/upgrade-guide#configure-content-sources

Encountering similar issues, as `safelist` now only refers to internal tailwind classes, not broader purge options.  Looks like we'll need to bring this back in as an external dep.  Shall park this upgrade branch for now!

**Comment by Sieabah** [comment] 2021-12-10 22:01
> Hey! Thank you for your bug report! Much appreciated! 🙏
> 
> Can you create a **minimal** reproduction repo with docker that showcases this issue?

Literally any configuration of tailwind inside of a docker container from windows will not work in any capacity. So I could create a repo but it might end up working if you're using it from mac or linux since they share similar enough file events.

**Comment by zackdotcomputer** [comment] 2021-12-13 09:46
I was running into this issue with RedwoodJS and couldn't figure out why it was happening there but not in NextJS. I'll take that issue up with their team.

For the purposes of helping folks who wind up in this thread, though, I found [this troubleshooting tip](https://v2.tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files) from the V2 Tailwind site fixed my issue. TLDR; I needed to set the env variable `TAILWIND_MODE=watch` when developing to kick the JIT compiler into rebuilding the css files every time my sources changed. It might be worth promoting that tip to the v3 getting started guide now that JIT is the default?

**Comment by dotdiego** [comment] 2021-12-14 17:08
Disabling the purge is really helpful too for Visual Studio (not Code) since we do not have a dedicated tailwindcss intellisense plugin we can see all the classes availables when it's built in the .css files.

**Comment by Sieabah** [comment] 2021-12-15 22:35
@aizaiz That's a huge component of my workflow is playing around with classes before changing it in the source. It's a shame there doesn't seem to be a way to disable purge or even allowing polling. Postcss seems to support it but I'm not sure if it will work with Angular or with HMR.

@zackdotcomputer I have that in my environment and it doesn't help when the file events aren't properly handled like with Docker on windows. There simply is no file events that ever get emitted when a file changes. 

@RobinMalfait If you require a min repo for this to be considered a bug all I'm going to do is the following.

```
npm i -g @angular/cli
ng new sample
cd sample
npm i --save-dev tailwindcss

#tailwind config with content = './src/**/*.{html,ts}'
ng serve --poll 2500
```

That's all I'm willing to do because this should occur on any configuration within containers on windows due to how the file system is mounted.

Regardless I've had to downgrade to v2 until there is some fix that allows me to disable purging in development or allows polling so the JIT can work with containers consistently.

**Comment by DanielSpravtsev** [comment] 2021-12-16 13:53
@aizaiz @dotdiego Agree with you. I don't know how it's on VC Code, but PHPStorm built-in tailwindcss plugin not working as expected and with purging enabled there are no classnames to hint by IDE

**Comment by dotdiego** [comment] 2021-12-16 15:22
@DanielSpravtsev about Jetbrains IDEs they're tracking that issue ([WEB-48464](https://youtrack.jetbrains.com/issue/WEB-48464#focus=Comments-27-5656656.0-0) on their issue tracker). It seems there's a regression on all IDEs 2021.3

**Comment by HepplerDotNet** [comment] 2021-12-16 20:11
Still (3.0.5) no option to disable purging during development?
One workaround is to use `<script src="https://cdn.tailwindcss.com"></script>` during development

**Comment by Sieabah** [comment] 2021-12-17 03:28
@HepplerDotNet This works perfectly!

**Comment by leeshadle** [comment] 2021-12-22 00:29
### Purging via safelisting

As @HepplerDotNet shared, it looks like you can disable purging via safelisting:

```js
safelist: [
  {
    pattern: /./,
  },
]
```

And then to account for variants such as hover:, focus:, and responsive variants (lg:,md:,sm:) this works:
```js
safelist: [
  {
    pattern: /./,
    variants: ['hover','focus','sm','md'],
  },
]
```

And then to safelist chained variants such as md:hover:, sm:hover, md:focus, sm:focus this works:
```js
safelist: [
  {
    pattern: /./,
    variants: ['hover','focus','md','sm','md:hover','sm:hover','md:focus','sm:focus'],
  },
]
```

This was hard to figure out 🤔...

I used the appendix at the link below for referencing the variant types to use with safelist patterns and then figured out the chaining through trial and error: 
https://tailwindcss.com/docs/hover-focus-and-other-states#quick-reference

### Safelisting with Prefixes (tw-) and negative utility class values doesn't seem to work? 🤔
With that being said, if you use a prefix such as tw-, I can't get the safelisting to work with negative values ( such as for margin, skew, rotate, scale, translate utilities):
```js
prefix: 'tw-',
safelist: [
{
	pattern: /-skew-x-2/,
	variants: ['hover','focus','md','sm','md:hover','sm:hover','md:focus','sm:focus'],
},
```

```css
.tw-skew-x-2 {
	--tw-skew-x:2deg;
	transform:var(--tw-transform);
}

.tw--skew-x-2 {
	--tw-skew-x:-2deg;
	transform:var(--tw-transform);
}

.hover\:tw-skew-x-2:hover {
	--tw-skew-x:2deg;
	transform:var(--tw-transform);
}

.tw--skew-x-2 {
	--tw-skew-x:-2deg;
	transform:var(--tw-transform);
}

.focus\:tw-skew-x-2:focus {
	--tw-skew-x:2deg;
	transform:var(--tw-transform);
}

.tw--skew-x-2 {
	--tw-skew-x:-2deg;
	transform:var(--tw-transform);
}

@media (max-width: 1023px) {
	.md\:tw-skew-x-2 {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
	.md\:hover\:tw-skew-x-2:hover {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
	.md\:focus\:tw-skew-x-2:focus {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
}

@media (max-width: 767px) {
	.sm\:tw-skew-x-2 {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
	.sm\:hover\:tw-skew-x-2:hover {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
	.sm\:focus\:tw-skew-x-2:focus {
		--tw-skew-x:2deg;
		transform:var(--tw-transform);
	}
	.tw--skew-x-2 {
		--tw-skew-x:-2deg;
		transform:var(--tw-transform);
	}
}
```

**Comment by Firegarden** [comment] 2021-12-22 00:56
For the record I this issue is super disruptive to my development. I use visual studio and I normally wait to purge as I often will run my project to test my edits / adjustments in the live browser with developer tools by modifying classes and see the effect. Now that it purges everything I can not test classes that are not already being used - sucks.

This is super annoying and I have tried other work arounds like linking to the full class but that does not take in account my customizations. 

Yes I tested with the safelist *fix* and it *works* but you need to let people know - I am sure this is going to make people regret upgrading to 3.0 until they figure this out - you best be doing a better job of pointing this out in the documentation. 

Thank you

**Comment by reinink** [comment] 2021-12-28 17:03
@Sieabah Hey thanks for sharing this and for the reproduction steps. We're going to look into this after the Christmas break when we have easier access to a Windows machine.

For everyone else commenting on this issue who miss having all the classes being generated ahead of time (how Tailwind worked prior to the new JIT mode), that is a separate issue from file system events not working on Docker on Windows. In the interest of keeping this issue focused, I have renamed it to "Watch issues on Docker on Windows". Please keep any further discussion related to that problem specifically.

---

That said, for the benefit of everyone who is new to [the JIT mode](https://tailwindcss.com/blog/just-in-time-the-next-generation-of-tailwind-css), here is a quick history lesson on how we ended up here. One of the biggest challenges we faced in Tailwind prior to JIT mode was performance issues. Because all the classes were generated ahead of time, you ended up with a massive CSS file. Of course you could then purge any unused styles when going to production, but in development the problem still existed.

Working with a CSS file this large caused memory issues in webpack builds, it caused both production and development builds to be slow, and even once you were able to generate the large CSS file, the browser would then have a hard time parsing it at runtime — devtools would literally lock up.

The workaround to these issues was to limit the number of utilities available in Tailwind. Great CSS features had to be left out. Many variants were also disabled by default, and you were definitely not able to stack variants. And we had to limit the number of colors enabled, as they especially contributed to the overall file size.

**All of these problems go away with the new JIT mode.** In JIT mode, Tailwind only generates the styles that are actually needed for your project, and nothing else. This has huge performance benefits, and allows us to now enable a much wider range of utilities, variants and colors. Development builds are lightning fast, as are production builds. No more memory issues. No more issues with browser devtools crashing. It does mean, however, that you no longer have that massive CSS file generated ahead of time, as, of course, generating it in advance would be throwing away all these benefits.

We do understand that this has implications for autocompletion. This is the reason we've invested a lot into our [IntelliSense plugin](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss). We've worked with the folks at JetBrains to help them with [their Tailwind CSS plugin](https://www.jetbrains.com/help/webstorm/tailwind-css.html). We have opened sourced the [Tailwind CSS Language Server](https://github.com/tailwindlabs/tailwindcss-intellisense/tree/master/packages/tailwindcss-language-server) to make it possible for others to create similar plugins. Someone has already figured out how to use this to add autocompletion to [Neovim](https://elijahmanor.com/blog/neovim-tailwindcss). We really see this as the path forward to autocompletions.

That all said, if having this pre-generated CSS file was crucial to your workflow, and using the above mentioned autocompletion tools don't work for you, your best bet is to stick with Tailwind v2.

**Comment by thecrypticace** [comment] 2022-01-03 15:59
Hi! Thanks for reporting this issue! We've looked into it and verified the problem with angular apps, tailwind, and docker on Windows.

The core of the problem is that Angular is setting the `TAILWIND_MODE=watch` env. This flag only exists as a workaround shouldn't be necessary as long as postcss-loader is up to date. I've gone through and checked and it is as well as verified that it works when manually running anglar using the default setting `TAILWIND_MODE=build`.

The relevant code is here:
https://github.com/angular/angular-cli/blob/2c9a33dddb38694b6940ec6981c49904de1ab636/packages/angular_devkit/build_angular/src/webpack/configs/styles.ts#L152-L154

**Comment by Sieabah** [comment] 2022-01-06 22:32
@thecrypticace Manually running angular outside of the docker container would defeat the purpose of my issue?

Looking over the code snippet, in my case would I just have to set TAILWIND_MODE in the container environment to `build` and not `watch` and I should see it fixed?

**Comment by thecrypticace** [comment] 2022-01-07 00:00
Yeah I completely understand. I don't mean to run angular outside of docker. I mean you'll need to set the env of the server that's running in the container.

Alternatively, you can update to the latest version of Tailwind as we have outright removed support for `TAILWIND_MODE=watch` because it is no longer needed. As such I'm going to close this issue because it should be "fixed" at this point. If you do run into further problems please re-open it and I'll take another look.

**Closed by thecrypticace** 2022-01-07 00:00 UTC
