### ISSUE TITLE
Erratic behavior with JIT in generating arbitrary CSS styles

### ISSUE THREAD

**Issue by k16e-me** [tailwindlabs/tailwindcss#3967] opened 2021-04-01 17:53 UTC
### What version of @tailwindcss/jit are you using?

v0.1.4

### What version of Node.js are you using?

v14.15.1

### What build tool (or framework if it abstracts the build tool) are you using?

Nuxt

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://www.loom.com/share/c21032290b6c4a7285151b3d711e3c26

**Comment by bradlc** [comment] 2021-05-13 10:10
Hey @k16e-me. Can you share a repository which reproduces the issue please? Otherwise it's not going to be possible to find the cause. Thanks!

As a complete guess based on your video, maybe that template is not covered by your `purge` config, and the values that _do_ work just happen to appear in other templates that are covered?

**Comment by erjdev** [comment] 2021-05-25 14:18
Looks like the linked reproduction loom video is now leading to a 404.

**Comment by bradlc** [comment] 2021-08-19 17:04
Going to close this as it was for the old `@tailwindcss/jit` package and a reproduction has not been provided. Please open a new issue if you're still seeing this 👍

**Closed by bradlc** 2021-08-19 17:04 UTC
Labels: jit
