### ISSUE TITLE
Tailwind 2.0 empty class does not exist

### ISSUE THREAD

**Issue by danirg15** [tailwindlabs/tailwindcss#2860] opened 2020-11-21 20:31 UTC
### Describe the problem:

After upgrading to TailwindCSS 2.0 I get the following error when i run `npm run dev`

```
ERROR in ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(2:1) The `` class does not exist. If you're sure that `` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  1 | @tailwind base;
> 2 | @tailwind components;
    | ^
  3 | @tailwind utilities;
  4 |

 @ ./resources/css/app.css 2:14-142
```

**Comment by adamwathan** [comment] 2020-11-21 21:04
Hey, can you share a GitHub repo that reproduces? This is impossible to troubleshoot without a real example codebase.

**Comment by adamwathan** [comment] 2020-12-01 15:47
Closing since no reproduction has been provided, please open a new issue with a reproduction if this is still a problem for you.

**Closed by adamwathan** 2020-12-01 15:47 UTC
Labels: needs reproduction

**Comment by dipunj** [comment] 2020-12-18 22:29
Hi @adamwathan, I too encountered the same problem when migrating to 2.0.

This is why it was breaking for me, In 1.9 we could declare default classes like:

```js
// tailwind.config.js
const { colors } = require('tailwindcss/defaultTheme')
module.exports = {
	theme: {
		colors: {
			...colors,
			gray: {
				...colors.gray,
				lighter: '#BDBDBD',
				default: '#828282',
			},
			black: {
				lighter: '#333333',
				default: '#191A1D',
				darkest: '#000000',
			},
		},
         }
}
```

and use it in jsx as 

```jsx
<div className="bg-black">
        Hello
</div>
```

But since 2.0, this seems to have changed, and now requires:

```tsx
<div className="bg-black-default">
        Hello
</div>
```

**Comment by adamwathan** [comment] 2020-12-18 23:19
@dipunj You need to use DEFAULT now not default, check the upgrade guide 💪🏻
