### ISSUE TITLE
JIT mode is not picking up changes unless I change tailwind.config.js file

### ISSUE THREAD

**Issue by MohammadxAli** [tailwindlabs/tailwindcss#4978] opened 2021-07-15 20:13 UTC
### What version of Tailwind CSS are you using?

v2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli v8.3.1

### What version of Node.js are you using?

v14.15.5

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/MohammadxAli/tailwind-test-repo

### Describe your issue

Sometimes tailwind in `jit` mode is not adding classes to final CSS when I'm adding them to my HTML files unless I edit the `tailwind.config.js` file, I usually comment and uncomment some line in that file and all of sudden I see the class has been added to the CSS file, I had this very same issue on my **Next.js** project as well. 

I made a new reproduction repository and tested things there, it was all good and working. Not really sure why it's not working on my own projects at some point. This may sound stupid but maybe tailwind is not picking up changes as the project get's more complicated?
I made this issue to know if anyone had some similar experience or not, so maybe someone can guide me on how to resolve this.

**Comment by moracabanas** [comment] 2021-07-16 16:17
Not to bloat this thread but I have just the same Issue with the exact same specs. Hot reloading is working but changes on tailwind styling fails until you modify and save `tailwind.config.js`

**Comment by moracabanas** [comment] 2021-07-16 16:44
I tried to downgrade to 2.2.0 and 2.1.4 but behaviour is the same.

**Comment by DevNvll** [comment] 2021-07-17 04:32
Same. Happening in my nextjs and vite projects. Tried to downgrade already but no luck. Its happening in a brand new vite project and a 1 year old nextjs project.

**Comment by DevNvll** [comment] 2021-07-17 04:33
It works for like 10 minutes and then stops generating classes.

**Comment by NickSdot** [comment] 2021-07-17 05:40
> It works for like 10 minutes and then stops generating classes.

Not 100% the same issue here, but similar so I think it's worth to add. HMR stops working and the page is fully reloaded on every change (might be related: #4970 and #4968). If I disable JIT it is working. Then, when I activate JIT again, it is working  and stops again after a while. Already tried the `TAILWIND_MODE=watch` without success.

Setup as following. Everything on the very latest versions.

**Tailwind:**
v2.2.4

**Build tool:**
Vite v2.42 with Post Css 8.3.5

**Node:**
v16.5.0

**Browser:**
Chrome v91

**Operating System:**
macOS v11.4

**Backend**
Laravel v8.50 on PHP 8

**Comment by paraboul** [comment] 2021-07-18 06:53
This is a vite issue :

https://github.com/vitejs/vite/issues/4150

There is a PR incoming :

https://github.com/vitejs/vite/pull/4267

**Comment by vesper8** [comment] 2021-07-18 14:19
In my case HMR does not work at all when I make modifications to JIT classes unless I stop the `yarn serve` process entirely and start it up again. Not using vite

**Comment by moracabanas** [comment] 2021-07-18 14:25
> In my case HMR does not work at all when I make modifications to JIT classes unless I stop the `yarn serve` process entirely and start it up again. Not using vite

Can I ask you if you can reproduce this situation?

1. You serve your application make a change on any JIT generated class:
 -This brokes something in the render for example change `bg-red-500` to `bg-red-800` and color goes out.
 
 2. You come back to `bg-red-500`, save it and it returns back. But no "new changes" are applying on JIT mode

**Comment by epitaphmike** [comment] 2021-07-20 02:16
I am running into the same issue. I created a test repo from the `with-tailwindcss` example and it works fine, I see both red and green colors. As soon as I run it in my larger project HMR doesn't pick up changes. It sees the first group of colors `hello-green` in the extended theme, but not the second. The weird part is, if I delete `hello-green` and change `hello-red` to `hello-green`, I get all the text in red.

My larger project is typescript, 

`module.exports = {
  mode: 'jit',
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
        extend: {
            colors: {
                "hello-green": {
                    900: '#262E1F',
                    800: '#2D3723',
                    700: '#37432A',
                    600: '#40601D',
                    500: '#5A8136',
                    400: '#759E4D',
                    300: '#ADCE8F',
                    200: '#DDE9D4',
                    100: '#EFF5ED',
                    50: '#F6F9F4'
                },
                "hello-red": {
                    900: '#351911',
                    800: '#542417',
                    700: '#6A2919',
                    600: '#973623',
                    500: '#BF533C',
                    400: '#D96E51',
                    300: '#E7BCAD',
                    200: '#EAE3E1',
                    100: '#F4F2F1',
                    50: '#FAF8F8'
                }
            }
        },
    },
    variants: {},
    plugins: [],
}
`

**Comment by vicurybin** [comment] 2021-07-20 06:42
> FWIW, there is a vite issue with how postcss registers all purgeable files as dependencies with `dir-dependency` :
> 
> [vitejs/vite#4150](https://github.com/vitejs/vite/issues/4150)
> 
> There is a PR incoming :
> 
> [vitejs/vite#4267](https://github.com/vitejs/vite/pull/4267)

**Comment by vicurybin** [comment] 2021-07-20 06:57
I downgrade vite to 2.3.8,tailwind to 2.14,it works

**Comment by pingustar** [comment] 2021-07-20 11:13
same issue here on v2.2.4 with create-react-app -> using CRACO

Dev server needs to be stopped and started up again after every change.

**Comment by kungpaogao** [comment] 2021-07-23 05:30
> same issue here on v2.2.4 with create-react-app -> using CRACO

@pingustar try the solution from #4768

**Comment by bradlc** [comment] 2021-07-23 13:24
@MohammadxAli I think I was able to reproduce this, but the classes do get picked up if I re-save the HTML file. Can you confirm whether this is the case for you?

**Comment by MohammadxAli** [comment] 2021-07-23 17:41
@bradlc Yes that's true! I didn't realize that saving the same HTML files can also trigger picking up classes. But it's important to note that the contents of the file must be **changed** when re-saving, otherwise the classes won't be added.

I am now using tailwindcss with `jit` mode in a Laravel based project which I'm changing `.blade.php` files, the issue still exists. If classes are not added I need to change the contents of the **same file**  which I used the new class in it or `tailwind.config.js` file.

**Comment by voicingewe** [comment] 2021-07-24 16:14
Just to add an example from Tailwind UI, if you go to https://tailwindui.com/components/marketing/sections/heroes change the "Hero Section" title to "text-red-400" instead of text-grey-400 and the color goes blank. Change it to another color and it also goes blank.

**Comment by Kostia-K** [comment] 2021-08-01 02:02
I'm facing the same issue using Vite.

When creating an example to reproduce the issue, I noticed that it only happens when I set the [base path](https://vitejs.dev/config/#base) in Vite. I need this option to integrate with Django.

I created a repo that demonstrates my observation https://github.com/Kostia-K/vite-tailwind-jit-issue

**Comment by type1fool** [comment] 2021-08-01 19:40
Hey all. I too was stumped by this issue while working on a Phoenix project last night. After finding this issue, I dug around a bit, and I have a workaround for Webpack pipelines.

**As it turns out, Phoenix 1.5.9 uses `webpack@4`, which is incompatible with the latest versions of `postcss-loader`.**
> You need webpack v5 to use the latest version. For Webpack v4, you have to install postcss-loader v4.

https://webpack.js.org/loaders/postcss-loader/

Installing `postcss-loader@4.3.0` resolved the issue in my project, and once again I can gleefully write Tailwind utils and see the changes in the browser quickly thanks to the JIT.

**Comment by phifa** [comment] 2021-08-05 21:11
having the same issue, on nextjs 11.

**Comment by type1fool** [comment] 2021-08-09 02:58
> Hey all. I too was stumped by this issue while working on a Phoenix project last night. After finding this issue, I dug around a bit, and I have a workaround for Webpack pipelines.
> 
> **As it turns out, Phoenix 1.5.9 uses `webpack@4`, which is incompatible with the latest versions of `postcss-loader`.**
> 
> > You need webpack v5 to use the latest version. For Webpack v4, you have to install postcss-loader v4.
> 
> https://webpack.js.org/loaders/postcss-loader/
> 
> Installing `postcss-loader@4.3.0` resolved the issue in my project, and once again I can gleefully write Tailwind utils and see the changes in the browser quickly thanks to the JIT.

Update: This only worked temporarily and I'm stumped.

**Comment by ElMassimo** [comment] 2021-08-12 13:02
As @Kostia-K mentioned, problems in Vite.js seem to be related to the usage of the `base` configuration option.

Related: https://github.com/ElMassimo/vite_ruby/discussions/115

**Comment by sebastiaanluca** [comment] 2021-08-30 19:01
Same here, but slightly different scenario: with JIT mode and hot reload enabled, using a class that's not been used yet, it'll add the class to the div but Tailwind won't generate the CSS for the class. If I refresh the page, the CSS class has been added to the styles and it works. Just not when using hot reload.

Tried a few variations like adding the Node env variables or changing the Tailwind config file, but nothing fixes it.

Firefox Developer Edition
@tailwindcss/forms@0.3.3
@tailwindcss/typography@0.3.1
@vue/compiler-sfc@3.2.6
autoprefixer@10.3.3
browser-sync@2.27.5
browser-sync-webpack-plugin@2.3.0
laravel-mix@6.0.28
postcss@8.3.6
postcss-import@14.0.2
tailwindcss@2.2.8
vue@3.2.6
vue-loader@16.5.0

**Comment by masterkain** [comment] 2021-09-05 15:26
I have the same problem as @sebastiaanluca but maybe it's vite + pug https://github.com/vitejs/vite/issues/4588

**Comment by adamwathan** [comment] 2021-09-10 14:13
@MohammadxAli I was able to reproduce in your repo but it seemed to stem from build configuration issues. I've opened a PR to your repo that fixes it by just fixing the configuration problems:

https://github.com/MohammadxAli/tailwind-test-repo/pull/1

Going to close this one only because everyone here I think has slightly different issues, and the issue for the OP is resolved with that PR. It's hard to keep track of multiple problems/conversations in a single issue, so instead I would ask that you please open a new issue if you are experiencing a problem that brought you to this issue and include a minimal reproduction so we can figure out what the specific issue is for your particular situation. Happy to help, not closing to be dismissive, just need to keep things on topic and organized if we want any hope of actually helping people, thanks!

**Closed by adamwathan** 2021-09-10 14:13 UTC

**Comment by sebastiaanluca** [comment] 2021-09-11 15:58
For those of you using Laravel Mix and HMR (`mix watch hot`), please try the example from the repository in the issue below and let me know if it works or not. I was able to reproduce the bug in one situation, but maybe it's just my quirky system.

Issue: https://github.com/tailwindlabs/tailwindcss/issues/5477
Repository: https://github.com/sebastiaanluca/tailwind-hmr-bug

**Comment by yuwanlin** [comment] 2023-02-28 12:08
> I downgrade vite to 2.3.8,tailwind to 2.1.4,it works

I use webpack v5, downgrade  tailwind from 3.2.7 to 2.1.4, it works.

**Comment by bcastillo-2022474** [comment] 2023-11-23 08:17
I know this is an old thread, but Im having troubles with this too, with Astro, the styles at some point are no longer applied, I need to comment a line of my `tailwind.config.mjs` and then uncomment it to make tailwindcss catch the change and apply the changes. really annoying, idk if this has something to do with vite, tailwindcss, or the fact that im using SSR. is there  a fix??
