### ISSUE TITLE
`has-*` with relative selector produces wrong output

### ISSUE THREAD

**Issue by sntran** [tailwindlabs/tailwindcss#14202] opened 2024-08-15 17:26 UTC
**What version of Tailwind CSS are you using?**

tailwindcss v4.0.0-alpha.19

**What build tool (or framework if it abstracts the build tool) are you using?**

`@tailwindcss/cli@4.0.0-alpha.19`

**What version of Node.js are you using?**

v20.12.2

**What browser are you using?**

Chrome version 127.0.6533.89 (Official Build) (arm64)

**What operating system are you using?**

macOS 14.5

**Reproduction URL**

https://play.tailwindcss.com/eVAnr2RUDF

**Describe your issue**

Element with `has-[>img]:bg-red-500` should only have red background when it has an immediate child that is an `<img>`.

However, the generated output is

![image](https://github.com/user-attachments/assets/c3389c6e-b1cc-4e45-bedf-a2df50160cc5)

With `has-[&>img]:bg-red-500`, the outer container has red background, even though its immediate children is the one that has immediate `<img>`. The output of that is:

![image](https://github.com/user-attachments/assets/628b1ed1-df24-480b-8d69-5d4f6bcb70ed)

What I would expect it to output:

```css
.has-\[\>img\]\:bg-red-500 {
  &:has(>img) {
    background-color: var(--color-red-500, #ef4444);
  }
}
```

For the case of `has-[&>img]:bg-red-500`, it should probably output the same as above, since `&>img` is not really a [relative selector](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/Selector_structure#relative_selector)

**Comment by adamwathan** [comment] 2024-08-15 20:29
Great catch, thanks! PR to fix here:

https://github.com/tailwindlabs/tailwindcss/pull/14203

For `has-[&>img]:bg-red-500` I _think_ the current behavior is correct based on how arbitrary variants work elsewhere in Tailwind — in `has-[&:hover]:flex` for example converting the `&:hover` part to `*:hover` is the right behavior, so keeping it that way with `:has` too even though I agree it's sort of a brain-melter to figure out what the user is even trying to do.

My thinking is that if you had a custom variant like this:

```css
@variant img-child (& > img);
```

…it would be used to style an image that is the child of the element with that class, like:

```html
<div class="img-child:rounded-full">
  <img ... />
</div>
```

And if you then wrote `has-img-child:bg-red-500`, you'd expect it to match if the current element has an element where `img-child` would match:

```html
<div class="has-img-child:bg-red-500">
  <div class="img-child:rounded-full">
    <img ... />
  </div>
</div>
```

So if that's expected, then writing `has-[&>img]` should work the same way, since that's just inlining the definition of the custom `img-child` variant.

Either way, `has-[>img]` will give you the expected behavior after we get that PR merged and a release tagged 👍

**Comment by sntran** [comment] 2024-08-16 16:46
Thank you for the quick fix!

> `@variant img-child (& > img);`

I did have something similar, but as a compound version:

```css
@variant descendants (& *);
@variant is-img (:where(&):is(img))
```

It's easier to combine with `descendants:is-img` or even `*:is-img`, but unfortunately I can't make a compound `is-*` variant yet.

> And if you then wrote `has-img-child:bg-red-500`, you'd expect it to match if the current element has an element where `img-child` would match:
>
> ```html
> <div class="has-img-child:bg-red-500">
>   <div class="img-child:rounded-full">
>     <img ... />
>   </div>
> </div>
> ```

This seems like a weird example to me when reading it out loud. I would not expect the outer `<div>` to have red background at all, since it does not have an immediate child that is an `<img>`, as I would read that it "has a child img". But maybe it's just the limitation of using variant to target child/descendant element.

**Closed** 2024-08-16 17:42 UTC

**Comment by philipp-spiess** [comment] 2024-08-23 14:03
@sntran We just release v4.0.0-alpha.20 with the fix included 🙂
