### ISSUE TITLE
Tailwind 3.2.1 issue with `@apply` inside rules with multiple referenced classes with `:not` pseudo-class

### ISSUE THREAD

**Issue by micobarac** [tailwindlabs/tailwindcss#9703] opened 2022-11-01 12:18 UTC
**What version of Tailwind CSS are you using?**

`Tailwind CSS 3.2.1`

**What build tool (or framework if it abstracts the build tool) are you using?**

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.2.7
Node: 16.17.1
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 14.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.7
@angular-devkit/build-angular   14.2.7
@angular-devkit/core            14.2.7
@angular-devkit/schematics      14.2.7
@angular/cdk                    14.2.6
@angular/cli                    14.2.7
@schematics/angular             14.2.7
rxjs                            7.5.7
typescript                      4.8.4
```

**What version of Node.js are you using?**

`Node: 16.17.1`

**What browser are you using?**

`Chrome`

**What operating system are you using?**

`macOS Ventura 13.0 (22A380)`

**Reproduction URL**

[https://play.tailwindcss.com/CVazo8CCwE?file=css](https://play.tailwindcss.com/CVazo8CCwE?file=css)

**Describe your issue**

**HTML:**

```html
<div class="ant-select-focused ant-select">
  <div class="ant-select-selector">Take 1</div>
</div>
<div class="ant-select-focused ant-select ant-select-disabled ant-select-customize-input">
  <div class="ant-select-selector">Take 2</div>
</div>
```

**SASS:**

Using `@apply` doesn't work:

```scss
@tailwind base;
@tailwind components;
@tailwind utilities;

.ant-select-focused:not(.ant-select-disabled).ant-select:not(.ant-select-customize-input)
  .ant-select-selector {
  @apply text-blue-500;
}
```
![take1](https://user-images.githubusercontent.com/16001837/199231988-a2369470-e04b-4ce4-834a-99789b278df1.png)

Using `plain css` works:

```scss
@tailwind base;
@tailwind components;
@tailwind utilities;

.ant-select-focused:not(.ant-select-disabled).ant-select:not(.ant-select-customize-input)
  .ant-select-selector {
  --tw-text-opacity: 1;
  color: rgb(59 130 246 / var(--tw-text-opacity));
}

```
![take2](https://user-images.githubusercontent.com/16001837/199232341-7dcd8811-018f-4c42-b59a-c8f5787950f3.png)

**Comment by thecrypticace** [comment] 2022-11-02 20:50
The nesting in the other one is a bit of a red herring. Currently, we ask that you use `tailwindcss/nesting` before tailwindcss if you want us to support nested CSS. This flattens the CSS before it gets to us. So, yes this is indeed a duplicate of #9668 (I've also verified this manually).

I'm closing in favor of that one.

**Closed by thecrypticace** 2022-11-02 20:50 UTC
