### ISSUE TITLE
[v4] feature request: `animation-range` & `animation-timeline`

### ISSUE THREAD

**Issue by bobbymannino** [tailwindlabs/tailwindcss#15111] opened 2024-11-22 15:49 UTC
In v4 there is a lot of syntax for future css and it is awesome i love it, but what is missing is css scroll based animations, you can use your own `animate-fade-in-up: fade-in-up linear both` but you cannot set animation range or timeline, or i am just missing it, this would be a great feature to have in v4 before its initial release.

Syntax could be something like `timeline-view-block` `range-from-entry-0%` `range-to-entry-100%`?

i'm aware you can add it as a utility but i mean baked in

original post: https://github.com/tailwindlabs/tailwindcss/discussions/15086_

**Comment by adamwathan** [comment] 2024-11-22 16:03
Hey! The original post was in the right spot :) Closing this one since it's not a bug.

**Closed by adamwathan** 2024-11-22 16:03 UTC
