### ISSUE TITLE
[Svelte] addUtilities generates duplicated runtime styles

### ISSUE THREAD

**Issue by LBrian** [tailwindlabs/tailwindcss#3955] opened 2021-03-25 02:40 UTC
### What version of @tailwindcss/jit are you using?

v0.1.3

### What version of Node.js are you using?

v15.11.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/LBrian/direction-aware-ui

### @tailwindcss/jit
![image](https://user-images.githubusercontent.com/3888780/112410213-f4eca300-8d6e-11eb-9e51-56fa40769db7.png)
<img width="1636" alt="Screen Shot 2021-03-25 at 1 31 06 pm" src="https://user-images.githubusercontent.com/3888780/112410135-d1295d00-8d6e-11eb-9a73-d99ff8f247f3.png">

### tailwindcss
![image](https://user-images.githubusercontent.com/3888780/112410254-05048280-8d6f-11eb-9705-da8f2f2d522f.png)
<img width="767" alt="Screen Shot 2021-03-25 at 1 30 20 pm" src="https://user-images.githubusercontent.com/3888780/112410152-d9819800-8d6e-11eb-9b8f-3a86ed7fc97d.png">

### Reproduction steps
1. `git clone https://github.com/LBrian/direction-aware-ui.git`
2. `npm i daisyui --save`
3. Change `tailwind.config.js` as below
![image](https://user-images.githubusercontent.com/3888780/112410535-6d536400-8d6f-11eb-90c5-31748f6dafa4.png)

4. Add `glass` utility class into any class in `<style>` of `App.svelte`

**Comment by adamwathan** [comment] 2021-05-24 23:22
Closing since it's been a couple months with no follow up so going to assume you got this sorted out. If not please feel free to open a new issue with a minimum reproduction ❤️

**Closed** 2021-05-24 23:21 UTC
Labels: jit
