### ISSUE TITLE
PurgeCSS ignore safelist/whitelist option

### ISSUE THREAD

**Issue by MKlblangenois** [tailwindlabs/tailwindcss#2577] opened 2020-10-16 13:03 UTC
### Describe the problem:

I'm trying to keep my color `class` in compiled `css` file with `safelist`option.

```
tailwind.config.js

[...]
    future: {
      removeDeprecatedGapUtilities: true,
      purgeLayersByDefault: true,
   },
   purge: {
      layers: ["components", "utilities"],
      content: ["./src/**/*.js"],
      // Try #1
      safelist: ["bg-red-500"],

      // Try #2
      options: {
         safelist: ["bg-red-500"],
      },

      // Try #3
      options: {
         whitelist: ["bg-red-500"],
      },
   },
[...]
```

### Link to a minimal reproduction:
https://github.com/MKlblangenois/gatsby-tailwind-purge-issue

**Comment by adamwathan** [comment] 2020-10-16 18:29
Just cloned and tested with this config and it kept the class:

```js
module.exports = {
   future: {
      removeDeprecatedGapUtilities: true,
      purgeLayersByDefault: true,
   },
   purge: {
      layers: ["components", "utilities"],
      content: ["./src/**/*.js"],
      options: {
         whitelist: ["bg-red-500"],
      },
   },
   theme: {
      fontFamily: {
         sans: ["Nunito Sans", "sans-serif"],
      },
   },
   variants: {},
   plugins: [require("@tailwindcss/ui")],
};
```

**Comment by adamwathan** [comment] 2020-10-16 18:29
We'll be upgrading to PurgeCSS 3 for Tailwind 2.0 in a couple of weeks which will let you use `safelist` instead.

**Comment by adamwathan** [comment] 2020-10-17 13:35
Going to close this as resolved, feel free to open another issue though if it turns out the problem is slightly different and needs a different reproduction.

**Closed by adamwathan** 2020-10-17 13:35 UTC

**Comment by sk8Guerra** [comment] 2021-07-06 05:09
For me it seems like `safelist` is not working in tailwind `2.1.1`. I'm using these settings in `tailwind.config.js`:  

```js
module.exports = {
  purge: {
    content: ['./src/**/*.js'],
    safelist: [
      'bg-gray-50',
      'bg-red-50',
      'bg-yellow-50',
      'bg-green-50',
      'bg-blue-50',
      'bg-indigo-50',
      'bg-purple-50',
      'bg-pink-50',
    ],
  },
  ...
};
```

```js
const colors = [
      'gray',
      'red',
      'yellow',
      'green',
      'blue',
      'indigo',
      'purple',
      'pink',
    ];

const background = colors[Math.floor(Math.random() * colors.length)];
```
Locally it works, bacause I compose those classes randomly when rendering some divs, but when deployed to production, those clases are gone. Any idea? Thanks!

**Comment by adamwathan** [comment] 2021-07-06 09:47
Hey! That feature was added in v2.2 so you need to update.

**Comment by sk8Guerra** [comment] 2021-07-06 14:32
@adamwathan that was exactly what was happening! Thanks you so much! 🙏🏼
