### ISSUE TITLE
Backticks in comments interfere when Tailwind CSS is used as CSS-in-JS

### ISSUE THREAD

**Issue by GHNewbiee** [tailwindlabs/tailwindcss#2492] opened 2020-10-04 18:25 UTC
### Describe the problem:
Backticks (`) in comments interfere when Tailwind CSS is used as CSS-in-JS.

Tailwind CSS can also be used in JS. For example, with **LitElements** where the following code:

**tailwindCssIn.js**
```js
import { css } from 'lit-element';

export default css`
  // Tailwind CSS content
`
```
is used and backticks have to be escaped.

### Link to a minimal reproduction:
https://github.com/QuinsZouls/lit-tailwindcss
https://github.com/QuinsZouls/lit-tailwindcss/blob/master/tailwindcss.js

**Comment by adamwathan** [comment] 2020-10-04 23:32
Closing as duplicate of #2493

**Closed by adamwathan** 2020-10-04 23:32 UTC
