### ISSUE TITLE
!important being added to custom utilities

### ISSUE THREAD

**Issue by stephenturvey** [tailwindlabs/tailwindcss#2906] opened 2020-11-25 23:09 UTC
I'm using important: true so that my utility classes have the !important declaration, but for some reason certain custom rules within my stylesheet are getting !important added automatically too. FYI it is not adding !important to _all_ my custom CSS. I've repeated the problem here:

https://play.tailwindcss.com/Hj5l41DW67

From the tailwind 2.0 docs: 
_To generate utilities as !important, set the important key in your configuration options to true:_
_Note that any of your own custom utilities will not automatically be marked as !important by enabling this option._

**Comment by stefanfisk** [comment] 2020-11-26 13:51
This looks like a dupe of https://github.com/tailwindlabs/tailwindcss/issues/2823.

**Closed** 2020-11-26 15:13 UTC
