### ISSUE TITLE
[Bug]: JIT does not work with filter

### ISSUE THREAD

**Issue by jenstornell** [tailwindlabs/tailwindcss#4257] opened 2021-05-06 14:28 UTC
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

postcss-cli 8.3.1

### What version of Node.js are you using?

15.0.1

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

Nope

### Describe your issue

I use JIT and have an imported file called `buttons.css` (postcss-import). In general everything works as expected, until I added some filter classes.

```css
.btn-delete {
  @apply text-white bg-red-600 border-red-700 filter saturate-50;
}
```

>CssSyntaxError: D:\projects\tools\squares\assets\css\buttons.css:27:3: The `filter` class does not exist. If `filter` is a custom class, make sure it is defined within a `@layer` directive.

In JIT we should not need to add classes into `tailwind.config.js` and `filter` should be active by default. Because I use the latest version of Tailwind I expected it to work.

Is it me or Tailwind? Did I miss something? Feels like a bug or a possible limitation of JIT?

### Update: Also fails within HTML

It also does not work as a normal class like this. All classes works except `filter` and `saturate-50`.

```html
<div class="text-white bg-red-600 border-red-700 filter saturate-50"></div>
```

**Comment by adamwathan** [comment] 2021-05-06 14:37
Hey! Seems like you must not actually be using Tailwind CSS v2.1. I just tested locally and it all works as expected.

Closing since no reproduction was provided, can't help without a reproduction as per the issue template:

> Unfortunately we can't provide support without a reproduction, and your issue will be closed and locked with no comment if this is not provided.

**Closed by adamwathan** 2021-05-06 14:37 UTC

**Comment by jenstornell** [comment] 2021-05-06 14:53
@adamwathan Alright! I've now tested it on another installation that I have a repo for which you can clone or download. It fails with the exact same issue. The version installed is Tailwind 2.1.2.

https://github.com/jenstornell/tailwind-jit-gulp

Run `npm run build` to see it after cloning.

>CssSyntaxError: D:\projects\tools\tailwind-jit-gulp\assets\css\src\tailwind.css:5:3: The `filter` class does not exist. If `filter` is a custom class, make sure it is defined within a `@layer` directive.

*It as Gulp installed but don't mind about that.*
