### ISSUE TITLE
[Tailwind 3.1.2] Gradient issue: `to-[color]-[number]` is not displayed even if specified

### ISSUE THREAD

**Issue by Infinituum17** [tailwindlabs/tailwindcss#8597] opened 2022-06-11 18:25 UTC
`[Tailwind v3.1.2, React v18.1.0, Node v17.0.1, Chrome, Windows]`

I copied the example [described here](https://tailwindcss.com/docs/gradient-color-stops#middle-color) and pasted it onto my main (and _only_) css file. Apparently in version 3.1.2 "via-[color]-[number]" causes a conflict with "to-[color]-[number]".

When "via-...-..." is added, the gradient shows only the "from-...-..." color and the "via-...-..." color, even if the "to-...-..." color is specified.

(My project has only one css file (screenshot below) and the other styles I apply are inline-classes, but I've tried removing them and it doesn't solve the issue)

`Main issue`:
![image](https://user-images.githubusercontent.com/40234342/173199261-4b7eba65-d233-4040-9342-511f8a4edca0.png)

`index.css`:
![image](https://user-images.githubusercontent.com/40234342/173199353-2167c11c-7bb6-49e3-a6d9-57d407522262.png)

`Chrome devtools`:
![image](https://user-images.githubusercontent.com/40234342/173199321-ff2d3884-0ade-478b-a582-26fe7e92f98e.png)

**Comment by adamwathan** [comment] 2022-06-11 20:59
I can't seem to reproduce this:

https://play.tailwindcss.com/gwJXfjag2V

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/4323180/173204638-e93ac38d-1c06-44e7-b873-4509b1171b02.png">

Can you provide a proper reproduction? As mentioned in the issue template it's required, otherwise it causes us to waste a lot of time, like I just did trying to create the reproduction by hand 🤪

**Comment by rohmann** [comment] 2022-06-11 21:01
@adamwathan I think it's a 3.1.2 issue. I tried it out as well and it works in the sandbox, but on 3.1.2 it overwrites `--tw-gradient-to` with a color that has zero opacity.

```
@supports (color: rgb(0 0 0 / 0))
body {
    --tw-gradient-to: rgb(59 130 246 / 0);
}
```

**Comment by adamwathan** [comment] 2022-06-11 21:12
Hey! You're really going to need to provide a reproduction. I've created another myself using v3.1.2 and can't reproduce:

https://github.com/adamwathan/tailwind-repro-8597

Run `npm run dev` to test it.

**Comment by adamwathan** [comment] 2022-06-11 21:15
@rohmann Sorry, thought you were the OP originally! Appreciate all the help you've been offering in issues and discussions lately, really a huge help 👊

**Comment by rohmann** [comment] 2022-06-11 22:56
No worries! Thanks! I think I figured out the issue here. The `@supports` rule is coming from the `create-react-app` stack. My local test env was just following the tailwind docs with React. After ejecting cra and tinkering around, I found the issue goes away when `postcss-preset-env` is removed.

Simplified, Tailwind outputs the `--tw-gradient-to` property multiple times.

```css
body {
  @apply bg-gradient-to-tr from-teal-500 via-blue-500 to-cyan-500;
}
```

produces this:

```css
body {
  --tw-gradient-to: rgb(20 184 166 / 0);
  --tw-gradient-to: rgb(59 130 246 / 0);
  --tw-gradient-to: #06b6d4;
}
```

Then if `postcss-preset-env` is involved, it transforms the above to...

```css
body {
  --tw-gradient-to: rgb(20 184 166 / 0);
  --tw-gradient-to: #06b6d4;
}

@supports (color: rgb(0 0 0 / 0)) {
  body {
    --tw-gradient-to: rgb(59 130 246 / 0);
  }
}
```

...and **that** causes the color to reset to the other value.

Technically, nothing wrong with the Tailwind CSS output. It looks like an edge case bug in how `postcss-preset-env` protects `rgb` colors with slash syntax. They should probably just ignore properties that get redeclared in a different syntax.

That being said, it could be fixed on the Tailwind side if the custom property was only output once.

**Comment by adamwathan** [comment] 2022-06-12 00:49
Ah that sucks. CRA continues to be a major source of pain for us because of how opinionated it is around PostCSS 😕 Going to close this as not our issue then, but would highly discourage using CRA. Use [Vite](https://vitejs.dev/) instead, it an amazing environment for client-side React apps like CRA is, but with a much smoother experience especially with Tailwind 👍

**Closed by adamwathan** 2022-06-12 00:49 UTC
