### ISSUE TITLE
Simplified entry `var()` does not work inside `calc()`

### ISSUE THREAD

**Issue by Serator** [tailwindlabs/tailwindcss#11036] opened 2023-04-19 14:22 UTC
**What version of Tailwind CSS are you using?**

v3.3.1

**What build tool (or framework if it abstracts the build tool) are you using?**

play.tailwindcss.com

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/nOih8esZYq

**Describe your issue**

* https://tailwindcss.com/blog/tailwindcss-v3-3#css-variables-without-the-var
* https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values

The documentation does not mention any restrictions.

The simplified `--var` entry does not work in the case of `calc()`, while it works in the familiar `var(--var)` entry.

**Comment by adamwathan** [comment] 2023-04-19 15:23
Hey! This is by design, the shorthand is only supported for simple cases where there's no chance of ambiguity 👍 

Duplicate of https://github.com/tailwindlabs/tailwindcss/issues/10895

**Closed by adamwathan** 2023-04-19 15:23 UTC

**Comment by Serator** [comment] 2023-04-19 15:46
Got it. It would be helpful to have this in the documentation.
