### ISSUE TITLE
Webpack errors while building the application but working fine in dev mode

### ISSUE THREAD

**Issue by shaijumt** [tailwindlabs/tailwindcss#3059] opened 2020-12-10 10:34 UTC

**Comment by shaijumt** [comment] 2020-12-10 10:36
> multilanguage@0.1.0 build /home/toobler/node/platform-property-marketing-website
> next build

info  - Creating an optimized production build  
Failed to compile.

Error: Expected an opening square bracket.


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/home/toobler/node/platform-property-marketing-website/node_modules/next/dist/build/index.js:15:918)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multilanguage@0.1.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multilanguage@0.1.0 build script.

**Comment by shaijumt** [comment] 2020-12-10 10:37
This is the error I am getting while trying to build the application

**Comment by RobinMalfait** [comment] 2020-12-10 12:08
Hey! Thank you for your bug report!
Much appreciated! 🙏

Can you create a (small) reproduction repo that you can share? 
In the mean time, also please check that you are using node 12.13 and up.

**Comment by adamwathan** [comment] 2020-12-15 11:01
Closing since it has been several days and no reproduction has been provided. Please open a new issue with a reproduction if you are still having this problem 👍🏻

**Closed** 2020-12-15 11:01 UTC
Labels: needs reproduction
