### ISSUE TITLE
dark mode not working in applied styles

### ISSUE THREAD

**Issue by samcharles93** [tailwindlabs/tailwindcss#3359] opened 2021-01-14 20:46 UTC
Dark classes not working in CSS body tag. no issues before install procedure updated

Create a vue3+Vite app following the instructions on the website. 
add @apply antialiased, bg, text color classes to body tag in App.vue - test ok.
add @apply dark:bg dark:text classes to body tag  in App.vue - test failed

![image](https://user-images.githubusercontent.com/1114464/104646789-0f6a2680-5705-11eb-92ec-51b45d021be7.png)

Steps to reproduce:
Follow instructions from https://tailwindcss.com/docs/guides/vue-3-vite
add body tag to index.css
add background and text classes
add antialiased class
test and working
add dark classes
test and failed.
add dark classes to App.vue template
test and working.

**Comment by adamwathan** [comment] 2021-01-15 13:29
I can't reproduce this, `apply` works as expected with dark variants in my testing:

https://play.tailwindcss.com/uSKKNdDerf

Make sure you are actually enabled the dark mode feature in your `tailwind.config.js` file:

```js
// tailwind.config.js
const colors = require('tailwindcss/colors')

module.exports = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'light-blue': colors.lightBlue,
        cyan: colors.cyan,
      },
    },
  },
  variants: {},
  plugins: [],
}
```

Closing since no reproduction was provided, if this is still an issue for you please provide an actual reproduction I can clone and test out locally.

**Closed by adamwathan** 2021-01-15 13:29 UTC
