### ISSUE TITLE
Tailwind just stops working randomly

### ISSUE THREAD

**Issue by MariuzM** [tailwindlabs/tailwindcss#4510] opened 2021-05-31 07:56 UTC
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome

### What operating system are you using?

Mac

### Reproduction repository

N/A

### Describe your issue

From time to time tailwing just stop working, so adding a new class or changing it does not take any effect solution i found is to nuke `.lock` and `node_modules` and do `yarn install` again

Has any one else experienced this? 

Also i have `mode: 'jit',` enabled

**Comment by brunottonurb** [comment] 2021-05-31 08:16
For me it stops working randomly too, but it's enough to restart webpack-dev-server to get it to work.
Using a webpack+babel+react+postcss+tailwind setup.

**Comment by MariuzM** [comment] 2021-05-31 08:31
I'm sure I've tried restarted dev server but will give this another go

**Comment by adamwathan** [comment] 2021-05-31 10:26
Try setting the `TAILWIND_DISABLE_TOUCH=true` environment variable in your script, it'll use an alternate dependency tracking engine that is a tiny bit slower but less prone to issues like race conditions and stuff like that. We're hoping to make it the default for v2.2+, but we had to make PRs to all of the popular build tools to be able to properly support it as it depends on a brand new feature we needed to get added to PostCSS.

Make sure you're on the latest version of postcss-loader in your Next project for it to work properly 👍🏻

**Comment by YannHulot** [comment] 2021-06-02 04:03
I am experiencing the same issue with NextJs and Jit mode on. I tried restarting the dev server but that usually does not fix it.

**Comment by MariuzM** [comment] 2021-06-02 06:44
Even with TAILWIND_DISABLE_TOUCH=true i still have the issue, o have to nuke both lock files and node_modules for it to work again. Using Next.js

**Comment by MariuzM** [comment] 2021-06-02 06:52
Done the recent update and also getting issues, for example added `rounded-xl` to another component worked, and when i wanted to change to `rounded-md` it just removed roundness all together, so again had to nuke lock and node_modules then it started working.

**Comment by TaycanRS** [comment] 2021-06-02 15:09
Same, using Next.js and JIT mode. Thought I was going crazy for a second.

**Comment by bradlc** [comment] 2021-06-02 16:26
Hey @MariuzM @brunottonurb @YannHulot @TaycanRS

I have tried to reproduce this in a Next.js project but I was unable to. Without a reproduction it is going to be really tricky to track down the issue. If anyone is able to share a project where this is happening (even if it's intermittent) that would be amazing, either as a public repository or an invitation to a private one 👍

**Comment by TaycanRS** [comment] 2021-06-02 16:51
Hey @bradlc

As MariuzM commented, adding a new class or changing it does not take any effect.
Important to note, it doesn't happen with all classes, this following example does not want to reflect space-x-4 from the ordered list.

For testing purposes, I added the breadcrumbs simple with chevrons from the tailwindui site:
https://tailwindui.com/components/application-ui/navigation/breadcrumbs#component-7dc6ffff20237868ddf0e7d21cf17cf1

This is how it shows on localhost:
![image](https://user-images.githubusercontent.com/74428362/120518602-981cf280-c386-11eb-99e7-ecac7afdeb94.png)

vs how it should look:
![image](https://user-images.githubusercontent.com/74428362/120518733-b97dde80-c386-11eb-8360-7a546d1b3154.png)

On my application, it is not respecting (-mb-4) to position between header section and main content, as well as (no-underline border-b-4  border-brand) to reflect the yellow underline.
![image](https://user-images.githubusercontent.com/74428362/120519365-60627a80-c387-11eb-9018-843342a6e2e8.png)

Working version on plain HTML
![image](https://user-images.githubusercontent.com/74428362/120519475-81c36680-c387-11eb-8031-d952154f56c6.png)

**Comment by adamwathan** [comment] 2021-06-02 20:21
@TaycanRS can you please create a GitHub repo that is set up the way your project is set up so we have something to test? That's what we mean by reproduction 🙏  If we can't make the problem happen on our own computers we have no way to know how to fix it. 100% believe that it's happening but we have tried to reproduce it and we can't, so we need a sample project where it has happened for someone so we can look at every possible cause.

**Comment by TaycanRS** [comment] 2021-06-02 23:07
Thanks for following up @adamwathan

Hope this helps: https://github.com/73devapp/seventhree
https://seventhree.vercel.app/contact

I'm new to github/git so if something is missing, please let me know and I'm happy to help out.

**Comment by TaycanRS** [comment] 2021-06-03 06:06
@adamwathan @bradlc 
Thank you both for being active and looking into the issue! 🙌

Latest update:
- This didn't work for me, perhaps I'm not doing it correctly: TAILWIND_DISABLE_TOUCH=true
- I can't replicate the issue. I cloned my project from GitHub repo and installed next/tailwind and it works on the new folder. Old folder is still faulty so I can try other suggestions.
- Also note that my previous project was a fresh install from a couple of days ago, so there is something that caused JIT to error.
- OP has a mac, I'm using ChromeOS

**Comment by adamwathan** [comment] 2021-06-04 18:22
Going to close this since no one has provided a reproduction — I really want to fix this but we need a repo to play with to figure it out. Hoping by closing this that the next person who has this issue will open a new issue and include a reproduction (even if it is super intermittent). Leaving it open just attracts a lot of "+1" style comments that unfortunately don't get us any closer to a solution.

Both @bradlc and @RobinMalfait have spent several hours independently trying to reproduce this issue but haven't been able to get it to happen (at least not when using `TAILWIND_DISABLE_TOUCH=true` so there must be some other missing piece of the puzzle and we'll need a project that is affected by this issue to see what we're doing differently.

If you find this issue and are having the same problem, **please open a new issue and include a repository that demonstrates the issue** and we will 100% work to fix it.

**Closed by adamwathan** 2021-06-04 18:22 UTC

**Comment by TimMTech** [comment] 2022-10-04 00:48
Next.js never fails to surprise me with its absolute shit instability.  PLEASE USE SOMETHING ELSE.  ANYTHING BESIDES NEXT.JS.  You will thank me later.

**Comment by shreyj786** [comment] 2023-04-29 12:45
What version of Tailwind CSS are you using?
3.3.2

What build tool (or framework if it abstracts the build tool) are you using?
React Native

What version of Node.js are you using?
16.13.1

What browser are you using?
Chrome

What operating system are you using?
Mac

Reproduction repository
https://github.com/shreyj786/React-Native-Design

I'm facing this issue in react-native where I'm using NativeWind.

Used command: 
`npx react-native start --reset-cache`

Cleaned node_module, lock file multiple times. 

Deleted and reinstalled the app at least 3-4 times but still facing this issue.

Also used command 
`npx tailwind -o output.css` and classes are not getting generated. 

For better understanding I have created a video.

https://user-images.githubusercontent.com/79035220/235302877-44c2152f-8475-4fb4-b0c3-fd8007fa0589.mp4

**Comment by xNOVA2** [comment] 2023-08-22 03:56
this issue still not fix,  facing same problem with nextjs try everything :(

**Comment by abelbeak** [comment] 2023-08-24 08:12
This occurs when NextJS uses css libraries that require post build, such as existing CSS (global.css) and tailwindcss.

My symptom was that some parts were not randomly applied when using TailwindCSS's custom color, custom width, etc., and it was resolved when the same value was applied in the parent node.

Save changes such as global.css. This situation occurred when Hot Reload was performed.

I couldn't find the exact cause, but I found in **tailwind.config.js**
```
module.exports = {
   content: [
     "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
     "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
     "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
     "./src/views/**/*.{js,ts,jsx,tsx,mdx}",
   ],
}
```
I solved it by adding the file path to

**Comment by alexyoung23j** [comment] 2023-08-26 01:43
@abelbeak bro you can't leave me hanging like that!

**Comment by TaycanRS** [comment] 2023-08-26 02:22
@alexyoung23j what do you mean, he did provide a solution, adding the paths in tailwind.config.js solved the issue. You can also do what MariuzM suggested, which is to delete node_modules and restart. This solves the problem as well.

**Comment by gatignoly** [comment] 2023-09-10 15:26
> This occurs when NextJS uses css libraries that require post build, such as existing CSS (global.css) and tailwindcss.
> 
> My symptom was that some parts were not randomly applied when using TailwindCSS's custom color, custom width, etc., and it was resolved when the same value was applied in the parent node.
> 
> Save changes such as global.css. This situation occurred when Hot Reload was performed.
> 
> I couldn't find the exact cause, but I found in **tailwind.config.js**

This solution worked for me !!
Thanks a lot @abelbeak

**Comment by rahulthomasdev** [comment] 2023-09-15 10:33
Had the same issue, checked the tailwind.config.json. Actually the components folder path was in the root.  Including the path "./components/**/*.{js,ts,jsx,tsx,mdx}" in addition to "./src/components/**/*.{js,ts,jsx,tsx,mdx}" worked for me.

**Comment by Developer-Nasim** [comment] 2024-01-27 07:36
use JIT mode then automatically will fix

**Comment by kishoreGleniseOfficial** [comment] 2024-02-06 06:39
In my case, I changed my folder set up, moved some folders to the root, and hence in my project the tailwind stopped suddenly.  Then I added the below in tailwind config 
`content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"]
`Now it works fine as usual. Hope it helps for someone.

**Comment by miraclemenikelechi** [comment] 2024-09-04 19:18
> In my case, I changed my folder set up, moved some folders to the root, and hence in my project the tailwind stopped suddenly. Then I added the below in tailwind config `content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"] `Now it works fine as usual. Hope it helps for someone.

just had this issue with NextJS 14.2.7, this solution works. thank you

**Comment by flawnn** [comment] 2024-10-02 17:52
> This occurs when NextJS uses css libraries that require post build, such as existing CSS (global.css) and tailwindcss.
> 
> My symptom was that some parts were not randomly applied when using TailwindCSS's custom color, custom width, etc., and it was resolved when the same value was applied in the parent node.
> 
> Save changes such as global.css. This situation occurred when Hot Reload was performed.
> 
> I couldn't find the exact cause, but I found in **tailwind.config.js**
> 
> ```
> module.exports = {
>    content: [
>      "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
>      "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
>      "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
>      "./src/views/**/*.{js,ts,jsx,tsx,mdx}",
>    ],
> }
> ```
> 
> I solved it by adding the file path to

Super interesting - I just had this because I moved Tailwind Classes _in a string, as part of a bigger struct object (basically a class config with key and the tailwind class as a value)_ into a .ts file. Most of these classes worked - but some didn't mysteriously. As soon as I put any other file endings than .tsx, it started working again... 

Maybe this should be the default for new projects? I am lucky to have found this thread but this could have taken me hours to be honest.

**Comment by natebennett21** [comment] 2024-10-03 20:50
For me, this problem was solved by adding the path to my `mdx-components.tsx` file in `tailwind.config.ts`. I was using some Tailwind styles there to affect all of my MDX files as described [here](https://nextjs.org/docs/app/building-your-application/configuring/mdx#global-styles-and-components), and forgot that the file was in my root, not my `app` folder, so it needs its own line.

```
const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./mdx-components.tsx",
  ],
};
export default config;
```
