### ISSUE TITLE
Tailwind+NX+Angular: Tailwind CSS classes doesn't work when applied directly in HTML

### ISSUE THREAD

**Issue by sharathsg27** [tailwindlabs/tailwindcss#6496] opened 2021-12-14 13:02 UTC
**What version of Tailwind CSS are you using?**

v3.0.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Nx workspace with Angular (v12),

**What version of Node.js are you using?**

v14.8.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Tailwind+NX+Angular: Tailwind CSS classes doesn't work when applied directly in HTML**

1. In SCSS file I'm using button mixins by applying tailwind classes & re-using my own custom button classes (Works)
2. Tailwind lib classes applied directly in HTML file for ex: "container mx-auto", "uppercase" (Doesn't work as styles are not applied)
<img width="553" alt="Screenshot 2021-12-14 at 3 53 14 PM" src="https://user-images.githubusercontent.com/29069848/146003215-6d28b076-6376-44f8-bd21-5abb7ae62c36.png">
<img width="973" alt="Screenshot 2021-12-14 at 3 54 33 PM" src="https://user-images.githubusercontent.com/29069848/146003233-02fecab5-e234-4089-8517-5e1cafc70bce.png">
<img width="561" alt="Screenshot 2021-12-14 at 4 12 35 PM" src="https://user-images.githubusercontent.com/29069848/146003264-a8d48659-c34f-46f6-a882-90a6fe17aff7.png">
<img width="505" alt="Screenshot 2021-12-14 at 4 13 34 PM" src="https://user-images.githubusercontent.com/29069848/146003280-211a1203-cb93-4b3c-beca-7378cb5b2191.png">

**Comment by reinink** [comment] 2021-12-15 14:58
Hey! In these situations we *really need* a minimal reproduction as required in the issue template:

> A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

That said, from a quick glance at the code you provided in the screenshots above, it appears that you have Tailwind configured incorrectly. The `plugins` array in the `tailwind.config.js` file is intended for Tailwind plugins — not PostCSS plugins.

![image](https://user-images.githubusercontent.com/882133/146209596-8baf84b0-1984-42d8-af6c-3664e048f61e.png)

Also, the `content` property has replaced the `purge` property, so you'll want to remove that as well.

![image](https://user-images.githubusercontent.com/882133/146209615-f8ad9e07-495f-4e65-b53b-d7527724314d.png)

I highly recommend reading through the upgrade guide for Tailwind v3.0, which covers how to migrate from v2.0 (which uses  PurgeCSS) to the new JIT engine: https://tailwindcss.com/docs/upgrade-guide

I am going to close this — but feel free to provide a minimal reproduction, and I'd be happy to have another look 👍

**Closed by reinink** 2021-12-15 14:58 UTC

**Comment by sharathsg27** [comment] 2021-12-15 17:28
Hey @reinink ,

Thank you so much for the guide link. I somehow missed it. After following that, it works perfectly. Thank you!

**Comment by reinink** [comment] 2021-12-15 17:29
@sharathsg27 Great to hear! 🙌
