### ISSUE TITLE
[v4] @theme directive is not evaluated in Vue SFC <style> sections

### ISSUE THREAD

**Issue by davidmatter** [tailwindlabs/tailwindcss#13244] opened 2024-03-14 11:16 UTC
**What version of Tailwind CSS are you using?**

4.0.0-alpha9

**What build tool (or framework if it abstracts the build tool) are you using?**

vite: 5.1.6

**What version of Node.js are you using?**

21.6.1

**What browser are you using?**

For example: Chrome, Safari, or N/A

**What operating system are you using?**

macOS

**Reproduction URL**
https://github.com/davidmatter/tw4-showcase/blob/main/src/App.vue

**Describe your issue**
`@theme` definitions should be evaluated in Vue SFC files. I've tried with both the vite plugin aswell as the postcss integration. It works if I import `tailwind` in `App.vue` directly but not if I import it in styles.css.

**Comment by adamwathan** [comment] 2024-03-22 17:40
Hey! So to understand what's happening here, it's crucial to understand that in tools like Vite, every single `<style>` block in a Vue component is processed entirely independently.

That means Tailwind processes this as if it's a completely separate CSS entrypoint:

```html
<style>
  @theme {
    --color-card: #000;
  }
</style>
```

...that is totally separate from your `style.css` file:

```css
/* style.css */
@import "tailwindcss";
```

Your `style.css` file is where the actual utility classes are being generated (because that's where you're importing Tailwind), and that file _only_ knows about `@theme` values declared in the _same_ file. So from the perspective of that file, the `--color-card` variable doesn't exist, because it is never registered with the same instance of Tailwind that is generating your utility classes (remember each CSS file is processed in isolation).

There's no way to "extend" your global Tailwind theme from within a Vue component I'm afraid because of this processing isolation.

I'm going to close this as not a bug because unfortunately there's nothing we can really do here and things are working the way they are supposed to even if it's surprising 😕

One "solution" in your case (although I don't really think it's the real solution to what you're trying to solve, but will demonstrate how things work) is to include `@import "tailwindcss/utilities"` in your Vue file:

```vue
<script setup lang="ts"></script>

<template>
  <div class="w-5 z-4 h-5 bg-card"><slot></slot></div>
</template>

<style>
  @import "tailwindcss/utilities";
  @theme {
    --color-card: #000;
  }
</style>
```

But now you will have two `w-5` classes in your project for example, because both instances of Tailwind are going to generate that class.

If you can share a more real-world example of the problem you are trying to solve though I can definitely give you some advice on what I'd consider the idiomatic solution 👍

**Closed by adamwathan** 2024-03-22 17:40 UTC

**Comment by davidmatter** [comment] 2024-03-22 18:29
Hey, thanks for your thorough answer! Right, I see the problem. I've just been playing around with the general question how (external) libraries that provide themable components could provide an easy way to override style tokens. I think something like this could be the right approach:

`
:root {
    --color-card: #f3f4f5;
}

@theme {
    --color-card: var(--color-card);
}
`

With this approach, users of such a component could just override :root vars locally (even when not using tailwind).
