### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by BlueFirePro** [tailwindlabs/tailwindcss#6908] opened 2022-01-05 15:11 UTC
Hi
I'm sorry but I'm just so tired...
you can find the bug described here:
https://github.com/sveltejs/kit/issues/3216

**Comment by rmuchall** [comment] 2022-01-05 15:31
I've also encountered the same issue with borders when using v3.10 of tailwindcss. Unfortunately I've not had time to investigate the cause and so I rolled back to tailwindcss v3.08.

**Comment by thecrypticace** [comment] 2022-01-05 18:36
Hey this is a regression in 3.0.10 which we reverted. It should be fixed in 3.0.11. I tested this in your reproduction with the latest version and it looks correct again.

Can you verify that this is also the case for you?

**Comment by BlueFirePro** [comment] 2022-01-05 20:46
Yep, it's fixed👍

**Comment by thecrypticace** [comment] 2022-01-05 21:24
phew awesome. Sorry about that again and thanks for double checking!

**Closed by thecrypticace** 2022-01-05 21:24 UTC
