### ISSUE TITLE
Tailwind doesnt allow forcing !important with selector in place

### ISSUE THREAD

**Issue by waffshappen** [tailwindlabs/tailwindcss#8979] opened 2022-07-28 16:35 UTC
**What version of Tailwind CSS are you using?**

3.1.6

**What build tool (or framework if it abstracts the build tool) are you using?**

vite 3.0.3

**What version of Node.js are you using?**

16.14.10

**What browser are you using?**

Firefox 101/Chromium 103

**What operating system are you using?**

Fedora 36

**Reproduction URL**

https://play.tailwindcss.com/2OCzJLtC9x

**Describe your issue**

Tailwind allows 2 modes for important application:
Mode 1 lets me go with !important on all styles
Mode 2 with just a selector.

However many common frameworks exist that share styles with tailwind and override them with !important if i only use a selector.
For these Tailwind would need to allow me to not only use the selector but also mark the generated styles as !important by default.

So important: '#selector', forceimportant: true
Or something similar.

Else i'd be forced to override each style bootstrap happens to share on an existing page with !p-2 or !px-2 - and hoping bootstrap doesnt add any more on updates.

**Comment by adamwathan** [comment] 2022-07-28 19:25
Hey! Yeah not sure what we can really do here — if you use the selector option then we don't use `!important`, that's kind of the whole idea. If you are using multiple tools and one of them is using `!important` we have no way to remove that from their styles or anything.

It sounds to me like you _shouldn't_ be using the selector option, since you need the specificity to be higher than it is when you use that option. It's not meant for scoping or anything, it's really just meant to add specificity.

Going to close this unfortunately as nothing we really can or plan to do here, just one of the challenges of using multiple tools that are fighting with each other, like using Vue and React in the same app or something at the same time.

Hope that explanation is somewhat helpful.

**Closed by adamwathan** 2022-07-28 19:25 UTC

**Comment by waffshappen** [comment] 2022-07-29 08:55
> Hey! Yeah not sure what we can really do here — if you use the selector option then we don't use `!important`, that's kind of the whole idea. If you are using multiple tools and one of them is using `!important` we have no way to remove that from their styles or anything.
> 
> It sounds to me like you _shouldn't_ be using the selector option, since you need the specificity to be higher than it is when you use that option. It's not meant for scoping or anything, it's really just meant to add specificity.
> 
> Going to close this unfortunately as nothing we really can or plan to do here, just one of the challenges of using multiple tools that are fighting with each other, like using Vue and React in the same app or something at the same time.
> 
> Hope that explanation is somewhat helpful.

Not really. All that would be needed is to allow in
https://github.com/tailwindlabs/tailwindcss/blob/a1346c9a8e088154c5b24d770305c0bafa43fcbd/src/lib/generateRules.js#L692
to also allow setting !important by specifying, for example,

``` javascript
if (typeof important === "string") {
    return (rule)=>{
        rule.walkDecls((d)=>{
            if (d.parent.type === "rule" && !inKeyframes(d.parent)) {
                d.important = true;
            }
        });
        rule.selectors = rule.selectors.map((selector)=>{
            return `${important} ${selector}`;
        });
    };
}
```
        
       
This could be solved both by adding an additional config option or by extending `important` to also allow an object like
``` javascript
important: {
    prefix: '#example',
    force: true,
}
```


Infact here is the entire function with that option added:

```javascript
// Strategy based on `tailwindConfig.important`
let strategy = ((important)=>{
    if (important === true) {
        return (rule)=>{
            rule.walkDecls((d)=>{
                if (d.parent.type === "rule" && !inKeyframes(d.parent)) {
                    d.important = true;
                }
            });
        };
    }
    if (typeof important === "string") {
        return (rule)=>{
            rule.selectors = rule.selectors.map((selector)=>{
                return `${important} ${selector}`;
            });
        };
    }
    if (typeof important === "object") {
        return (rule)=>{
            if(typeof important.force === 'boolean' && important.force) {
                rule.walkDecls((d) => {
                    if (d.parent.type === "rule" && !inKeyframes(d.parent)) {
                        d.important = true;
                    }
                });
            }
            if(typeof important.prefix === 'string') {
                rule.selectors = rule.selectors.map((selector) => {
                    return `${ important.prefix } ${ selector }`;
                });
            }
        };
    }
})(context.tailwindConfig.important);
```



This single change would massively improve scoped usability of tailwind - just like i can use vue on a page in partial so could i now with tailwind, easing a slower and partial adoption instead of the "all or nothing" approach.

If there is an interest in pursuing this i can turn this into a pr, with better object checking/error messages, doc update and all because i am forced in a project to enable this approach -right now- anyway. If not i'll just patch it each time it builds.

**Comment by adamwathan** [comment] 2022-07-29 12:02
What's the point of setting the selector if already using `!important`? The specificity is already at max if you use `!important`. There's no reason to have `#app` and `!important` happening at the same time unless you are trying to hack this feature to use it as a way to scope Tailwind styles to a specific part of a page, but that's not at all what this feature is meant for so I don't think it really makes sense to continue down that path, especially not when the option is called `important`. Being able to scope Tailwind styles is a neat idea but to me that's a totally separate feature request for something that doesn't exist at all in Tailwind currently.

**Comment by waffshappen** [comment] 2022-07-29 19:33
> What's the point of setting the selector if already using `!important`? 

In an application that has bootstrap already (legacy) i want to add a widget to (vue) that uses tailwind for itself.
I cant use !important since that would override existing app styles for the entire page.
I cant rely on just the app specific selector since bootstrap overrides it with !important.
I need it to override, for #exampleselector, everything with !important so bootstrap p-4 and co is forcefully overridden.


And thats why i need this. Yes, its a way to scope it to parts of the page.
If this is a desired feature i'd be willing to help to get this in.

**Comment by MatthewAry** [comment] 2022-11-14 21:23
@adamwathan there is a point for having this feature. You can't assume that the selector strategy will always the same level of specificity as `!important`. Especially when we're working with pre-existing component libraries or legacy applications. You also can't assume that everyone can make sure that everyone can control the order that their CSS frameworks load in.

Being able to do the selector strategy and `!important` together should be supported. In my case, using the selector yields the results I want in most issues I run into but not all of them. In those few situations, I will want to apply the `!important` modifier.

Frankly making it so you can only have one or the other means that your forcing a trade off on end-users. I understand that tailwind tries to steer developers to work in a specific way, but not being able to do this is fairly problematic for me.

**Comment by tresorama** [comment] 2023-02-25 23:09
I will be a great feature.
I'm currently working with a system that already apply some `!important`, and without going into details, if i want that my taliwind classes always win I need both a "scoped selector" before the class name and the value marked as `!important`.

Something like...
```css
.my-scope .text-2xl {
  font-size: 1.5rem !important;
}
```


I tried doing the same but with `tailwind/nesting` or directly with `postcss-nested`, using this input
```css
.my-scope {
  @tailwind utilities;
}
```
... and in the output,  plain classes work as intended, but media queries ones not

```css
.my-scope .text-2xl {
  font-size: 1.5rem !important;
}

@media (max-width: 999px) {

  .md:text-2xl {
    font-size: 1.5rem !important;
  }

}
```
