### ISSUE TITLE
The global variable `--tw-transform` is not defined in base

### ISSUE THREAD

**Issue by yannickoo** [tailwindlabs/tailwindcss#6604] opened 2021-12-18 03:43 UTC
**What version of Tailwind CSS are you using?**

v3.0.7

**What build tool (or framework if it abstracts the build tool) are you using?**

tailwindcss-cli 3.0.7

**What version of Node.js are you using?**

v16.13.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/iVIJhwfSBR – Funny thing here: `--tw-transform` gets directly added to `div:after` and there is no global definition of that variable. Maybe v3.0.1 is the reason for that 😕 

**Describe your issue**

Edit: It seems like this relates to https://github.com/tailwindlabs/tailwindcss/pull/6500

I am using web components which import a shared CSS file that only contains `@tailwind base`. When trying to use transform utilities I can also see `transform: var(--tw-transform);`.

The problem is that the variable is not defined since that does not live in Tailwind base:

```
*, ::before, ::after {
  ...

  --tw-transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  ...
}
```

Is it possible that we get this moved like the other globals like shadows or content?

```
*, ::before, ::after {
  --tw-ring-offset-shadow: 0 0 #0000;
  --tw-ring-shadow: 0 0 #0000;
  --tw-shadow: 0 0 #0000;
  --tw-shadow-colored: 0 0 #0000;
}
```

```
::before,
::after {
  --tw-content: '';
}
```

Thank you!

**Comment by adamwathan** [comment] 2021-12-18 21:20
Hey! In Tailwind 3, those variables are only assigned to the selectors that need them, not the universal selector. This is for performance reasons — in our testing assigning too many variables to the universal selector causes major initial paint performance issues in Safari on large sites (say > 5000 DOM nodes).

No plans to change this I'm afraid, but you can of course add that CSS to your own CSS.

That said, unless I'm misunderstanding you, adding classes like `rotate-90` or whatever should still work, because Tailwind will see where you are adding them and generate the appropriate base rules. Is the problem that using the shadow DOM or whatever the universal selector _does_ cascade into the web component, but regular selectors like `.rotate-90` don't?

**Comment by AmruthPillai** [comment] 2021-12-20 07:56
I'm not sure if this is the same issue, but didn't want to create a new one. I'm facing the same problem with many of the modifier classes in tailwind. Utilities like rotate, scale, grayscale (filter) are unusable, as in, they just don't work.

<img width="352" alt="Screenshot 2021-12-20 at 8 53 08 AM" src="https://user-images.githubusercontent.com/1134738/146732037-0424fae2-b72a-448e-ad20-56fb12dfbf95.png">
<img width="290" alt="Screenshot 2021-12-20 at 8 52 55 AM" src="https://user-images.githubusercontent.com/1134738/146732042-d6a6b460-3813-49a1-8bbe-a8d2648265be.png">

The variables just don't seem to add up here. Not sure if I should be using it differently. The docs say that they should work by just adding the `rotate-90` class or `grayscale` class, but they don't.

Currently on Tailwind 3.0.5.

**Comment by yannickoo** [comment] 2021-12-21 03:01
@adamwathan thanks for your response! The problem in my case is that `--tw-transform` is not defined. When trying to use `rotate-90` I get CSS like this ⬇️ 

```
div {
  --tw-rotate: 90deg;
  -webkit-transform: var(--tw-transform);
          transform: var(--tw-transform)
}
```

**Comment by adamwathan** [comment] 2021-12-21 11:24
@yannickoo Can you provide a GitHub repo I can clone and look at? Those universal rules are gone as of v3 like I mentioned, and replaced with rules that target only the elements that need to be targeted.

https://play.tailwindcss.com/GqMJCvWdip

Can see the rules here:

![image](https://user-images.githubusercontent.com/4323180/146922189-f69980de-245e-4b79-bf3a-ab67a94bbc77.png)

 Need to see an actual reproduction to have any more insight here, I can't get this to not work.

**Comment by AbdelrhmanAmin** [comment] 2021-12-27 08:54
@adamwathan I am sorry I can't provide a GitHub repo. my team is using tailwindcss: "^3.0.7".
Both of `tansform` and `backdrop` are not working.
![image](https://user-images.githubusercontent.com/37663043/147453592-afd2d9ab-f6c9-4754-a52c-1d0461da0fe9.png)
![image](https://user-images.githubusercontent.com/37663043/147453668-cef8dcce-e7c6-44c3-90bc-7e5199bd83f4.png)
![image](https://user-images.githubusercontent.com/37663043/147453732-9e375bd1-c09d-4d24-9ac9-0790978fd923.png)

**Comment by AbdelrhmanAmin** [comment] 2021-12-27 10:44
@adamwathan I have the same problem with `transform` is not defined.
I am using Nextjs: "^12.0.7" and tailwindcss: "^3.0.0".
I did upgrade to "^3.0.7", however, the issue is still persisting.
I also noticed the same issue with `backdrop-filter`.
![image](https://user-images.githubusercontent.com/37663043/147464194-2a433980-03fa-43ce-b652-221bfb0b85d3.png)

**Comment by rikgirbes** [comment] 2021-12-27 15:32
@adamwathan Same issue here, when using the `rotate-` classes through `@apply`

e.g. 
```css
.ribbon {
    @apply rotate-45;
}
```

creates:
```css
.ribbon {
    --tw-rotate: 45deg;
    transform: var(--tw-transform);
}
```

with `--tw-transform` being undefined

**Comment by AmruthPillai** [comment] 2021-12-28 08:42
I believe this issue is recurring only in NextJS. I tried the same on Svelte and seemed to work as expected. Maybe there's some overridden postcss config that's stopping Tailwind to work as it should?

**Comment by AbdelrhmanAmin** [comment] 2021-12-28 08:45
@AmruthPillai I agree. I also tried on a new "create-react-app" and it worked fine.

**Comment by rikgirbes** [comment] 2021-12-28 10:06
@AmruthPillai I'm not using NextJS or any js-framework for that matter.

tailwind.scss (included in `main.ts` and as simple as can be)
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

tailwind.config.js
```js
module.exports = {
	content: [
		'./templates/**/*.{tpl,html}',
		'./src/**/*.{js,ts,jsx,tsx,vue}',
		'./index.html',
	],
	plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};
```

postcss.config.js
```js
module.exports = {
    plugins: {
        tailwindcss: {},
        autoprefixer: {},
    }
}
```

rollup.config.js (only the interesting parts)
```js
export default {
    input: './src/main.ts',
    output: {
        file: './dist/main.js',
        format: 'iife',
        plugins: [
            production && terser()
        ],
    },
    plugins: [
        resolve(),
        json(),
        typescript({
            allowSyntheticDefaultImports: true,
            resolveJsonModule: true,
            moduleResolution: 'node',
        }),
        commonjs(),
        babel({
            babelHelpers: 'bundled',
            exclude: 'node_modules/**'
        }),
        postcss({
            extract: true,
            minimize: production
        }),
        replace({
            'process.env.NODE_ENV': JSON.stringify('development'),
            'preventAssignment' : true
        }),
    ]
}
```

**Comment by nstgeorge** [comment] 2022-01-02 21:57
> @AmruthPillai I agree. I also tried on a new "create-react-app" and it worked fine.

My CRA app is having this issue with `blur` classes, it seems universal (or at least not connected to CRA vs Next.js).

<img width="221" alt="Screen Shot 2022-01-02 at 2 56 42 PM" src="https://user-images.githubusercontent.com/9936817/147890474-1f185f2d-c6c2-4742-ae24-b15ff4e5258f.png">

**Comment by AmruthPillai** [comment] 2022-01-03 04:47
@nstgeorge Could you confirm that the file you have used the `blur` class is covered by the content array in tailwind.config.css?

**Comment by jshimkoski** [comment] 2022-01-03 14:47
I ran into this issue as well while upgrading a codebase from Tailwind 2 -> Tailwind 3.

To fix the issue, I wound up removing the `@apply` CSS referencing transform changes and instead used the tailwind classes directly on the element(s) in question.

This definitely made the upgrade process a bit painful as it's not a cut and dry issue to correct in all codebases.

If this behavior can't be changed for performance reasons, it might be a good idea to update the "[Automatic transforms and filters](https://tailwindcss.com/docs/upgrade-guide#automatic-transforms-and-filters)" section in the upgrade guide to indicate this `@apply` shortcoming.

**Comment by irsooti** [comment] 2022-01-03 15:04
same here.

Now I'm bashing my head for a while.
I'm using the latest version of react-scripts with CSS module and in order to let work utility classes I've included `./src/**/*.module.css` into `tailwind.config.js` file: 

```js
const colors = require('tailwindcss/colors');

module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './public/index.html',
    './src/**/*.module.css', <-- here
  ],
  theme: {
    colors: {
      primary: colors.orange,
      gray: colors.gray,
      red: colors.red,
      blue: colors.blue,
      yellow: colors.yellow,
      white: colors.white,
      green: colors.green,
    },
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};

```

Now I'm trying to figure out why some other stuff doesn't work properly, it seems to be there are some breaking changes here

**Comment by thecrypticace** [comment] 2022-01-03 20:59
I cannot reproduce this in an isolated environment on the latest version of tailwind. A cloneable reproduction would be **significantly** helpful here. As far as I can get, output-wise, `--tw-transform` is always defined.

Could someone provide a reproduction we can clone to triage the issue?

When I pass tailwind this:

tailwind.config.js
```js
module.exports = {
    content: [{ raw: html`<div class="foo"></div>` }],
  }
```

input.css
```css
@tailwind utilities;

.foo {
    @apply rotate-90;
}
```

I get this:

output.css
```css
.foo {
        --tw-translate-x: 0;
        --tw-translate-y: 0;
        --tw-skew-x: 0;
        --tw-skew-y: 0;
        --tw-scale-x: 1;
        --tw-scale-y: 1;
        --tw-transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y))
          rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y))
          scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
        --tw-rotate: 90deg;
        transform: var(--tw-transform);
}
```

Which has `--tw-transform`.

**Closed** 2022-01-04 16:29 UTC

**Comment by miftahalrasyid** [comment] 2022-01-26 12:45
if you want to load transform function in .module.css file you have to point out the the path in tailwind.config js

example:

    content: [
      "./pages/**/*.{js,ts,jsx,tsx}",
      "./components/**/*.{js,ts,jsx,tsx,css}",
    ],

i add render tailwind in ./components file with all the extension mention above

cheers

**Comment by adeel-ali-atp** [comment] 2022-01-26 15:07
In my case, @tailwind base; was not added. After adding transform started working

**Comment by v-dawg** [comment] 2022-04-13 20:11
I have this problem too, running Vite + Svelte

**Comment by Shaker-Hamdi** [comment] 2022-05-15 17:18
I have the same issue. I'm using Next.js, Tailwind CSS, twin.macro, and styled-components.

When applying the classes inside the styled-component Div like this, it doesn't work (with or without the `transform` class) ...

```
.div {
    ${tw`transform -translate-y-1/2`}
}
```

However, applying the class `-translate-y-1/2` directly to the `<div>` element inside the component does work perfectly 😕 

`<div className="-translate-y-1/2">`

I'm not sure if it's a twin.macro issue in my case or what.

**Comment by jaydiablo** [comment] 2022-06-09 15:44
Also ran into this issue, in my case, the transform/translate rules are defined in an `@apply` directive that's in a postcss CSS file that ends up getting included in the main css file where the `@tailwind` directives are (via an `@import`).

There were two ways to fix this, one, was to add `@tailwind base` at the top of this imported file (thanks @adeel-ali-atp for the suggestion), however, this approach seems to duplicate all of the CSS that `@tailwind base` provides, as the size of the compiled CSS file increased substantially.

The other option was to move the rules into the same file where the `@tailwind` directives live rather than importing the file, this only increased the output CSS size a little bit and the transforms work as expected.

So it seems to be when `@apply` is used for these transforms/translates, as @jshimkoski suggested, but only when the `@apply` is used in a file that also doesn't contain `@tailwind base`.

**Comment by wsz7777** [comment] 2024-09-06 15:44
must link base style ？
