### ISSUE TITLE
Custom color not working

### ISSUE THREAD

**Issue by federicocappellotto97** [tailwindlabs/tailwindcss#6568] opened 2021-12-16 15:39 UTC
**What version of Tailwind CSS are you using?**

v3.0.5

**What build tool (or framework if it abstracts the build tool) are you using?**

webpack 2.2.1

**What version of Node.js are you using?**

14

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Describe your issue**

After updating from v2 to 3.0.5 just one custom color (brown-light) is not working anymore.

My config:
```
prefix: 'tw-',
theme: {
    extend: {
      colors: {
        brown: {
          DEFAULT: '#352C24',
          light: '#9A8A7B' //This is not working
        },
        pink: {
          DEFAULT: '#D5A0BD',
          light: '#F8E7F1'
        },
        gray: {
          200: '#F4F4F4',
          300: '#DADADA',
          400: '#D8D8D8',
          800: '#A0A0A0'
        }
      },
    }   
}

//tailwind.css
.done {
  @apply tw-text-brown-light;
}
```
It returns: `CssSyntaxError: tailwindcss: _dev/css/tailwind.css:273:3: The **tw-text-brown-light** class does not exist. If **tw-text-brown-light** is a custom class, make sure it is defined within a @layer directive.`

**Comment by reinink** [comment] 2021-12-16 17:09
Hey! So, I've just tried this myself in Tailwind Play, and I am not able to reproduce this issue. See here: https://play.tailwindcss.com/Df1ivcc5yR

In these situations we *really need* a minimal reproduction as required in the issue template:

> A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

I am going to close this — but feel free to provide a minimal reproduction, and I'd be happy to have another look 👍

**Closed by reinink** 2021-12-16 17:09 UTC

**Comment by federicocappellotto97** [comment] 2021-12-17 09:34
> Hey! So, I've just tried this myself in Tailwind Play, and I am not able to reproduce this issue. See here: https://play.tailwindcss.com/Df1ivcc5yR
> 
> In these situations we _really need_ a minimal reproduction as required in the issue template:
> 
> > A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.
> 
> I am going to close this — but feel free to provide a minimal reproduction, and I'd be happy to have another look 👍

Hello, i just created a public repo with some files of my project to reproduce the issue
https://gitlab.com/federicocappellotto/tailwind-bug

Just use **watch:tailwind** to compile only tailwind file
Thanks!

**Comment by federicocappellotto97** [comment] 2021-12-23 15:57
> Hey! So, I've just tried this myself in Tailwind Play, and I am not able to reproduce this issue. See here: https://play.tailwindcss.com/Df1ivcc5yR
> 
> In these situations we _really need_ a minimal reproduction as required in the issue template:
> 
> > A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.
> 
> I am going to close this — but feel free to provide a minimal reproduction, and I'd be happy to have another look 👍

Hello @reinink any news?

**Comment by donuts-are-good** [comment] 2021-12-28 19:46
I'm going through this same issue currently. No changes to config, yet overnight I am no longer able to start the watcher because of a custom color.

**Comment by federicocappellotto97** [comment] 2021-12-29 10:07
> I'm going through this same issue currently. No changes to config, yet overnight I am no longer able to start the watcher because of a custom color.

Try with Tailwind 3.0.7, it seems to be resolved

**Comment by andorfermichael** [comment] 2022-04-08 07:02
Same issue for me.
