### ISSUE TITLE
Blur text while using shadow in parent div

### ISSUE THREAD

**Issue by AzadKshitij** [tailwindlabs/tailwindcss#4070] opened 2021-04-14 08:09 UTC
### What version of Tailwind CSS are you using?

2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

"autoprefixer": "^10.2.5", "postcss": "^8.2.10", "next": "10.1.3",

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

Firefox

### What operating system are you using?

Windows

### Reproduction repository

https://gist.github.com/AzadKshitij/4951429c46eb6f0ea50010b5a94d3c66

**Comment by AzadKshitij** [comment] 2021-04-14 08:10
![image](https://user-images.githubusercontent.com/54288405/114676502-413d5a00-9d01-11eb-9258-ee6e3f61a3f0.png)

**Comment by adamwathan** [comment] 2021-04-17 18:41
Not sure what the issue is here since no explanation was provided. I don't see any blur classes being used and can't make sense of what you are looking for sorry. Closing, please provide more information in a new issue if this is still a problem, can't help when the issue is empty.

**Closed by adamwathan** 2021-04-17 18:41 UTC
