### ISSUE TITLE
tailwind config crashing chrome devtools

### ISSUE THREAD

**Issue by randyridge** [tailwindlabs/tailwindcss#2418] opened 2020-09-21 01:17 UTC
### Describe the problem:

The following tailwind config crashes chrome's devtools (chrome 85 windows), removing either the experiment or the portrait config allows devtools to continue working.

```
module.exports = {
  experimental: {
    extendedSpacingScale: true,
  },
  future: {
  },
  plugins: [
  ],
  purge: {},
  theme: {
    extend: {
      screens: {
        'portrait': {'raw': '(orientation: portrait)'},
      }
    }
  },
  variants: {
  },
};
```

### Link to a minimal reproduction:

[Minimal repro svite app](https://github.com/randyridge/tailwind-repro)

```
pnpm install
pnpm dev
```

Inspect an element.

![image](https://user-images.githubusercontent.com/476061/93726894-6d876280-fb86-11ea-9a70-c49ebcebcb52.png)

###

If I had to guess the problem originates here:

[maxWidth importing screens breakpoints](https://github.com/tailwindlabs/tailwindcss/blob/0221f2f003875fde44395cecc12cca61b5168231/src/flagged/extendedSpacingScale.js#L104)

**Comment by simonswiss** [comment] 2020-09-21 06:38
Whoaaa.. the dev tools _died_ indeed 😅

I don't have a Windows machine, but I can confirm that the dev tools are crashing on Chrome for Windows in BrowserStack:

![image](https://user-images.githubusercontent.com/485747/93737962-e25ea900-fc27-11ea-97ad-7de45d0bac96.png)

I also asked a friend who owns a PC to try and reproduce, and they said they could consistently crash the dev tools as well.

In their case, the cache storage was showing to be over capacity:

![image](https://user-images.githubusercontent.com/485747/93738085-3b2e4180-fc28-11ea-9dbd-9d371ccf6ac8.png)

I cannot reproduce this crash on Mac OS, where Chrome seems to handle that config file (and resulting file size) without a problem, at least _on my machine_ 😅

@randyridge are you able to break the dev tools with other things than `screens` (aka just building a fairly large CSS file by enabling more breakpoints, variants etc? This would help determine if the problem is the generated file size, rather than specific to the screens/extended spacing scale combination you have in your config file.

**Comment by randyridge** [comment] 2020-09-21 14:12
I don't believe cache storage is related, I can repro after emptying cache.  Here's some sizes I see for my config:

5.8MB with extendedSpacingScale dies
4.0MB without extendedSpacingScale works
3.5MB with extendedSpacingScale works

Various fiddling seems to indicate somewhere above 4MB causes devtools to crash and as you can see above I was able to get extendedSpacingScale enabled without crashing by disabling a bunch of other stuff (gradients, etc).

**Comment by adamwathan** [comment] 2020-09-21 19:45
Test this out and let me know if it fixes your issue:

https://github.com/randyridge/tailwind-repro/pull/1

**Comment by randyridge** [comment] 2020-09-21 20:07
yep looks good. thank you.

**Comment by adamwathan** [comment] 2020-09-22 13:00
Closing as the underlying problem here is a performance issue in Chrome 85 after introducing the ability to edit [constructable stylesheets](https://developers.google.com/web/updates/2019/02/constructable-stylesheets) in dev tools.

This shows up most often in vite projects (or svite in this case) as they use constructable stylesheets under the hood when possible, because it does have performance benefits until the CSS reaches a certain size threshold.

The hacky work around for now is to add a comment to your CSS with `@import` in it, which will trick Vite into not using constructable stylesheets. Hopefully we can get a more robust solution implemented in Vite until the issue with Chrome itself is resolved.

```css
/*! @import */
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Closed by adamwathan** 2020-09-22 13:00 UTC

**Comment by gino** [comment] 2020-10-03 23:26
I am also having this issue, but I am using Nuxt.js instead. I actually thought it would be a [Nuxt.js issue](https://github.com/nuxt-community/tailwindcss-module/issues/167), since there is a TailwindCSS module for Nuxt. But I recently installed TailwindCSS manually into my project and still got this issue, which brought me to this issue.

Is there a way to fix this issue in Nuxt.js projects? I am not sure if `/*! @import */` is also possible to use.

I am importing all requirements using this way though:

```css
/* purgecss start ignore */
@import "tailwindcss/base";
@import "tailwindcss/components";
/* purgecss end ignore */
@import "tailwindcss/utilities";
```

**Comment by defusevenue** [comment] 2020-10-06 12:56
> 
> 
> Closing as the underlying problem here is a performance issue in Chrome 85 after introducing the ability to edit [constructable stylesheets](https://developers.google.com/web/updates/2019/02/constructable-stylesheets) in dev tools.
> 
> This shows up most often in vite projects (or svite in this case) as they use constructable stylesheets under the hood when possible, because it does have performance benefits until the CSS reaches a certain size threshold.
> 
> The hacky work around for now is to add a comment to your CSS with `@import` in it, which will trick Vite into not using constructable stylesheets. Hopefully we can get a more robust solution implemented in Vite until the issue with Chrome itself is resolved.
> 
> ```css
> /*! @import */
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```

Doesn't seem to be working for Nuxt.js projects

**Comment by 2ne** [comment] 2020-11-06 10:02
> Closing as the underlying problem here is a performance issue in Chrome 85 after introducing the ability to edit [constructable stylesheets](https://developers.google.com/web/updates/2019/02/constructable-stylesheets) in dev tools.
> 
> This shows up most often in vite projects (or svite in this case) as they use constructable stylesheets under the hood when possible, because it does have performance benefits until the CSS reaches a certain size threshold.
> 
> The hacky work around for now is to add a comment to your CSS with `@import` in it, which will trick Vite into not using constructable stylesheets. Hopefully we can get a more robust solution implemented in Vite until the issue with Chrome itself is resolved.
> 
> ```css
> /*! @import */
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> ```

This fix does not work within an Angular 10 project using webpack.

**Comment by Yori-Mirano** [comment] 2021-02-04 08:36
I don't know if this will help you, but I just discovered by chance that for me, it was having to activate the option of Chrome which allows to display a visual representation of the breakpoints of the media queries. See the capture.

It is absolutely necessary to deactivate this option.

![image](https://user-images.githubusercontent.com/1879222/106866180-722f5c00-66cc-11eb-9e52-8d9945905340.png)

![image](https://user-images.githubusercontent.com/1879222/106866197-765b7980-66cc-11eb-9d9a-ae55d9b8cdbc.png)

**Comment by mmartinovich** [comment] 2021-02-16 10:30
None of the thing above worked. Still freezing on angular 10. :/

**Comment by eliasrosales88** [comment] 2021-02-18 23:44
> None of the thing above worked. Still freezing on angular 10. :/

Enabling purge in tailwind config did the trick for me. I'm using Angular 11 with the recently updated tailwindcss v2.0.3 and postcss 8.

**Comment by anasak-dev** [comment] 2021-12-01 02:58
I also ran into same issue but looks like tailwind 'JIT' feature solved it,
take a look at https://tailwindcss.com/docs/just-in-time-mode and give it a try if you are having chrome crash issues.

**Comment by jjstanton** [comment] 2021-12-15 06:44
> I also ran into same issue but looks like tailwind 'JIT' feature solved it, take a look at https://tailwindcss.com/docs/just-in-time-mode and give it a try if you are having chrome crash issues.

Thank you! This solved the issue for me.

**Comment by plungarini** [comment] 2024-11-06 22:28
This happened to me too. A simple fix is to disable overwrites in the source panel of the Chrome or Edge Dev Tools. This worked for me

**Comment by tiagoboeing** [comment] 2025-01-28 14:43
> This happened to me too. A simple fix is to disable overwrites in the source panel of the Chrome or Edge Dev Tools. This worked for me

The same thing here, after disable "Enable Local Overrides" worked. 

![Image](https://github.com/user-attachments/assets/79dec888-93f7-4977-a924-970222b89b33)
