### ISSUE TITLE
v3.0: JIT crashes on startup trying to find preflight.

### ISSUE THREAD

**Issue by halotest** [tailwindlabs/tailwindcss#6330] opened 2021-12-10 04:26 UTC
**What version of Tailwind CSS are you using?**

For example: 3.0.0

**What build tool (or framework if it abstracts the build tool) are you using?**

For example: NextJS 12.0.1

**What version of Node.js are you using?**

For example: v16.6

**What browser are you using?**

For example: Chrome

**What operating system are you using?**

For example: macOS

**Reproduction URL**
-

**Describe your issue**

<img width="906" alt="Снимок экрана 2021-12-10 в 11 18 51" src="https://user-images.githubusercontent.com/8064916/145516839-ae6dab93-d37e-40d5-8d86-d1f73529d9d9.png">

**Comment by adamwathan** [comment] 2021-12-10 11:26
Closing since a reproduction is not included, as is explained in the issue template. Please open a new issue and include a reproduction if this is still a problem.

**Closed by adamwathan** 2021-12-10 11:26 UTC

**Comment by gardinermichael** [comment] 2022-05-25 20:56
I realize this issue is closed, but did you have any luck with this @halotest? I’m having the exact same issue and believe it may be related to upgrading from Tailwind 2. The files exist in their proper place.
