### ISSUE TITLE
npx tailwindcss init not working

### ISSUE THREAD

**Issue by CreateSean** [tailwindlabs/tailwindcss#2831] opened 2020-11-19 22:49 UTC
### Describe the problem:

Using tailwind in post-css compatibility mode

 I've got tailwind 2.0 installed and the build process runs, however now I want to set up a config file so I can add custom colors etcetera. I run the `npx tailwindcss init` command and it fails with this output.

```
λ npx tailwindcss init
npx: installed 86 in 8.321s
Cannot find module 'autoprefixer'
```

I can see autoprefix in both package.json `"autoprefixer": "^9.8.6",` and the autoprefixer folder in the node_modules folder. 

Not sure how to resolve this, please advise.

**Comment by JackWatling** [comment] 2020-11-20 09:01
I had trouble generating the configuration file while using the compatibility package. I managed to generate one after updating my tailwindcss, postcss, and autoprefixer packages to the latest versions. After doing this I downgraded my packages back to the compatibilty versions.

`npm uninstall tailwindcss postcss autoprefixer
npm install tailwindcss@latest postcss@latest autoprefixer@latest

npx tailwindcss init -p

npm uninstall tailwindcss postcss autoprefixer
npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9`

**Comment by jayspecies** [comment] 2020-11-20 10:19
Thanks, @JackWatling ... That was enough to get me up and running on v2.

**Comment by Obiwarn** [comment] 2020-11-20 10:37
can confirm. 
there is a bug with compat mode and
`npx tailwindcss init`

**Comment by CreateSean** [comment] 2020-11-20 13:51
> I had trouble generating the configuration file while using the compatibility package. I updated my tailwindcss, postcss, and autoprefixer packages to the latest versions and this allowed me to generate a configuration successfully. I then downgraded my packages back to the compatibility versions.
> 
> ```
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@latest postcss@latest autoprefixer@latest
> 
> npx tailwindcss init -p
> 
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```

This worked for me. Hacky but it worked

**Comment by adamwathan** [comment] 2020-11-20 22:50
Can't seem to reproduce here, here is the output I get running the steps in the instructions for the compat build from scratch:

**Comment by saint-matt** [comment] 2020-11-20 23:00
If I follow the exact steps you posted above then I get the "Cannot find module 'autoprefixer'" error shown in the original post.  What debug can I provide you to help further?

**Comment by saint-matt** [comment] 2020-11-20 23:02
I got some warnings when I installed the packages, so maybe I need to update node actually

`➜  compat-test npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for @tailwindcss/postcss7-compat@2.0.1: wanted: {"node":">=12.13.0"} (current: {"node":"11.6.0","npm":"6.14.9"})
npm WARN notsup Not compatible with your version of node/npm: @tailwindcss/postcss7-compat@2.0.1
npm WARN compat-test@1.0.0 No description
npm WARN compat-test@1.0.0 No repository field.`

**Comment by saint-matt** [comment] 2020-11-20 23:09
Yep, I updated to the latest version of node using

nvm install node --reinstall-packages-from=node

and then when I reran the steps @adamwathan posted, everything worked fine

**Comment by GarrettWeinberg** [comment] 2020-11-21 16:26
updating to node v15 and `yarn add autoprefixer` solved this issue for me

**Comment by JackWatling** [comment] 2020-11-21 17:59
I've stepped through the same commands Adam used above in a fresh directory and can confirm I had no issues this time. Prior, I was running an outdated node version when I was generating the configuration, so the upgrade to node v14 seems to have sorted it.

**Comment by adamwathan** [comment] 2020-11-21 18:23
Alright so one thing we know for sure is you need to be on Node >= 12, since that's the minimum version requirement for Tailwind CSS v2.0.

I'm going to close this as resolved since it seems like the steps I outlined above are working for everyone who has the correct Node version installed. If someone sees this and is still having this issues despite updating Node and following the exact instructions outlined above, please open a new issue 👍🏻

**Closed by adamwathan** 2020-11-21 18:23 UTC

**Comment by thepurpleblob** [comment] 2020-12-02 20:39
Just to note that I had node 12.8 with Ubuntu 20.10 and it didn't work as described above. 

I junked it, installed nvm and the latest node (15.3.0) and then it worked fine. So possibly 12 isn't new enough. Certainly the stock versions that come with the latest Ubuntu (20.10) won't cut it.

**Comment by Gitsack** [comment] 2020-12-03 05:19
Upgrading to node 15 fixed it for me, 14.xx wasn't working.

**Comment by satyakresna** [comment] 2020-12-04 13:51
I have been run `npx tailwindcss init` and it shows **Cannot find module 'autoprefixer'**.

Node version: 14.15.1 LTS
NPM version: 6.14.9
OS: macOS Big Sur

<img width="591" alt="Screen Shot 2020-12-04 at 21 50 47" src="https://user-images.githubusercontent.com/11099186/101171513-d73de580-367a-11eb-8e16-ac55ff5bc72a.png">

**Comment by thepurpleblob** [comment] 2020-12-04 13:53
@satyakresna - it would appear that upgrading to the latest (v15) node may be your answer.

**Comment by vickoman** [comment] 2020-12-04 16:44
> I had trouble generating the configuration file while using the compatibility package. I updated my tailwindcss, postcss, and autoprefixer packages to the latest versions and this allowed me to generate a configuration successfully. I then downgraded my packages back to the compatibility versions.
> 
> ```
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@latest postcss@latest autoprefixer@latest
> 
> npx tailwindcss init -p
> 
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```

It worked! Thanks a lot

**Comment by satyakresna** [comment] 2020-12-04 22:48
> @satyakresna - it would appear that upgrading to the latest (v15) node may be your answer.

Yes, I think so. Thank you.

**Comment by SamuelKinuthiaK** [comment] 2020-12-05 07:24
Thanks a lot, @JackWatling you've really saved me from time wastage. Very handy.

**Comment by jamik0900** [comment] 2020-12-05 18:22
> I had trouble generating the configuration file while using the compatibility package. I updated my tailwindcss, postcss, and autoprefixer packages to the latest versions and this allowed me to generate a configuration successfully. I then downgraded my packages back to the compatibility versions.
> 
> ```
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@latest postcss@latest autoprefixer@latest
> 
> npx tailwindcss init -p
> 
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```

It works, thanks.

**Comment by weerd** [comment] 2020-12-09 23:51
Just noting, I had the same issues as others are reporting here. I was on Node v10.x and hadn't realized I needed to upgrade until seeing [Adam's comment](https://github.com/tailwindlabs/tailwindcss/issues/2831#issuecomment-731616851). I jumped to Node v14.x and while the output was slightly different it still had pretty much the same error.

So confirming what others have stated and seems like the TailwindCSS compat version needs Node 15.x to work right. I ended up going with @JackWatling's recommendation since I want to stick to an LTS release of Node and 14.x is the latest LTS available.

**Comment by javag97** [comment] 2020-12-11 18:05
How would one do this with yarn v2?

**Comment by emran899dev** [comment] 2020-12-12 15:09
Please tell, problems
$ npx tailwindcss init
Error: EPERM: operation not permitted, mkdir 'C:\Users\Emran'
command not found: tailwindcss

**Comment by Ade-Joshe** [comment] 2020-12-28 16:36
I ran into it some minutes ago and I just had to go through tailwind's documentation [here](https://tailwindcss.com/docs/guides/nextjs) and realised I skipped some installations @postcss and @autoprefix.

**Comment by weerd** [comment] 2021-01-04 05:43
Just an additional follow-up! [Laravel Mix v6 with support for PostCSS v8 is out](https://github.com/JeffreyWay/laravel-mix/releases/tag/v6.0.6) so you shouldn't need to bother installing Tailwind using the PostCSS v7 compatibility mode 🙌

Just use the latest versions:

```
npm install tailwindcss@latest postcss@latest autoprefixer@latest

npx tailwindcss init
```

Worked great! For reference, I'm on Node 14.x LTS.

**Comment by IamLizu** [comment] 2021-05-06 14:40
> I had trouble generating the configuration file while using the compatibility package. I updated my tailwindcss, postcss, and autoprefixer packages to the latest versions and this allowed me to generate a configuration successfully. I then downgraded my packages back to the compatibility versions.
> 
> ```
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@latest postcss@latest autoprefixer@latest
> 
> npx tailwindcss init -p
> 
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```

I am experiencing this wired issue. `width` and `height` on a image is not working, here's how I wrote it,

```
<img
        src="/didun.jpg"
        alt="A name here"
        width="250"
        height="250"
        className="rounded-full"
/>
```

And this is how it is showing in app source,

![image](https://user-images.githubusercontent.com/26184316/117316953-e4216800-aeaa-11eb-9068-e507683b0ca4.png)

But I don't see or wrote any rule to override the CSS.

**Comment by Adityakushwaha142** [comment] 2021-05-07 18:21
> I had trouble generating the configuration file while using the compatibility package. I updated my tailwindcss, postcss, and autoprefixer packages to the latest versions and this allowed me to generate a configuration successfully. I then downgraded my packages back to the compatibility versions.
> 
> ```
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@latest postcss@latest autoprefixer@latest
> 
> npx tailwindcss init -p
> 
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```

Thanx a lot buddy it worked

**Comment by Behruz0129** [comment] 2021-05-09 10:05
If i am going to install tailwindcss in React. On npx tailwindcss init comand i have many problems. Autoprefixer isn't find

**Comment by tadzyla** [comment] 2021-05-10 11:27
Tailwind CSS requires Node.js 12.13.0 or higher.

for me it worker this way

npm uninstall tailwindcss postcss autoprefixer
npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
npx tailwindcss init

**Comment by joshuaoyerinde** [comment] 2021-05-26 00:43
though is not showing me any error but the class is not working and i follow the normal procedure ... i did exactly what you did
 @JackWatling

**Comment by joshuaoyerinde** [comment] 2021-05-26 00:44
thanks to you is now working

**Comment by Marvelxy** [comment] 2021-06-03 04:20
> How would one do this with yarn v2?

    $ yarn add tailwindcss
    $ yarn add postcss 
    $ autoprefixer

Updating to node 15 fixed my issue while running this
   
    $ npx tailwindcss init

**Comment by eyooooo** [comment] 2021-06-04 16:24
Just to comment on this unfortunately closed issue - Node 15 is NOT a LTS version. Node 14, as far as i know, is the most popular LTS version at this time. Tailwind UI not working straight out of the box with Node 14 is pretty insane.

**Comment by adamwathan** [comment] 2021-06-04 16:30
@eyooooo Hey! Not sure what problem you are having but the CLI works as expected on node 14:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/4323180/120834041-811a0400-c530-11eb-97f8-c27fd5f948b6.png">

I'm confused though because you are talking about "Tailwind UI not working" which feels like a very different problem then "the CLI tool fails and doesn't generate a tailwind.config.js file".

If you are having some sort of issue with Tailwind UI + Node 14 please open an issue and explain the problem, happy to help.

**Comment by eyooooo** [comment] 2021-06-04 16:37
> 
> 
> @eyooooo Hey! Not sure what problem you are having but the CLI works as expected on node 14:
> 
> <img alt="image" width="899" src="https://user-images.githubusercontent.com/4323180/120834041-811a0400-c530-11eb-97f8-c27fd5f948b6.png">
> 
> I'm confused though because you are talking about "Tailwind UI not working" which feels like a very different problem then "the CLI tool fails and doesn't generate a tailwind.config.js file".
> 
> If you are having some sort of issue with Tailwind UI + Node 14 please open an issue and explain the problem, happy to help.

Thanks so much for your reply @adamwathan. Following the instructions from tailwind, using node 14, i am unable to generate the tailwind.config.js file without doing the hacky version swapping and npm uninstall/install the diff versions. I am on Ubuntu 18.04 if that makes any difference. 

My comments are just that of slight annoyance regarding this working properly with Node 15, and not 14 :) I have not tested that myself though. 

Thanks.

**Comment by Marvelxy** [comment] 2021-06-04 16:43
> > @eyooooo Hey! Not sure what problem you are having but the CLI works as expected on node 14:
> > <img alt="image" width="899" src="https://user-images.githubusercontent.com/4323180/120834041-811a0400-c530-11eb-97f8-c27fd5f948b6.png">
> > I'm confused though because you are talking about "Tailwind UI not working" which feels like a very different problem then "the CLI tool fails and doesn't generate a tailwind.config.js file".
> > If you are having some sort of issue with Tailwind UI + Node 14 please open an issue and explain the problem, happy to help.
> 
> Thanks so much for your reply @adamwathan. Following the instructions from tailwind, using node 14, i am unable to generate the tailwind.config.js file without doing the hacky version swapping and npm uninstall/install the diff versions. I am on Ubuntu 18.04 if that makes any difference.
> 
> My comments are just that of slight annoyance regarding this working properly with Node 15, and not 14 :) I have not tested that myself though.
> 
> Thanks.

How did you install node? If you use nvm, you can easily switch between node versions.

**Comment by adamwathan** [comment] 2021-06-04 16:45
One thing that should work for sure is if you use the dedicated separate CLI package:

```
npx tailwindcss-cli@latest init
```

If you are using the compat build, everything is unfortunately a huge pain in the ass. The root cause of all these problems is the CLI depends on peer-dependencies being installed, and npx doesn't automatically install peer dependencies, and different versions of node seem to treat npx + peer-dependencies + package aliases differently.

I suspect we will drop support for the PostCSS 7 compat build completely very soon — PostCSS 8 is almost a year old and very few tools are left that are still stuck on PostCSS 7. What tool are you using that doesn't support PostCSS 8 currently?

**Comment by eyooooo** [comment] 2021-06-04 16:46
> 
> 
> > > @eyooooo Hey! Not sure what problem you are having but the CLI works as expected on node 14:
> > > <img alt="image" width="899" src="https://user-images.githubusercontent.com/4323180/120834041-811a0400-c530-11eb-97f8-c27fd5f948b6.png">
> > > I'm confused though because you are talking about "Tailwind UI not working" which feels like a very different problem then "the CLI tool fails and doesn't generate a tailwind.config.js file".
> > > If you are having some sort of issue with Tailwind UI + Node 14 please open an issue and explain the problem, happy to help.
> > 
> > 
> > Thanks so much for your reply @adamwathan. Following the instructions from tailwind, using node 14, i am unable to generate the tailwind.config.js file without doing the hacky version swapping and npm uninstall/install the diff versions. I am on Ubuntu 18.04 if that makes any difference.
> > My comments are just that of slight annoyance regarding this working properly with Node 15, and not 14 :) I have not tested that myself though.
> > Thanks.
> 
> How did you install node? If you use nvm, you can easily switch between node versions.

using the standard install methods: https://github.com/nodesource/distributions/blob/master/README.md

I just dont think the issue should be closed because if users are following the exact instructions from TailWind and finding issues, thats bad. At the very least the tailwind docs should account for or document this stuff. I dont want to use tailwind at this point if I cant just install it and have it work right out the gate. 

Finding the solution to my problems in a closed github issue doesnt make me feel good. Just a user perception comment.

**Comment by eyooooo** [comment] 2021-06-04 16:48
@Marvelxy @adamwathan I am just following this guide https://tailwindcss.com/docs/guides/create-react-app where i just want to setup tailwind with a base react project.

**Comment by Marvelxy** [comment] 2021-06-04 16:50
> > > > @eyooooo Hey! Not sure what problem you are having but the CLI works as expected on node 14:
> > > > <img alt="image" width="899" src="https://user-images.githubusercontent.com/4323180/120834041-811a0400-c530-11eb-97f8-c27fd5f948b6.png">
> > > > I'm confused though because you are talking about "Tailwind UI not working" which feels like a very different problem then "the CLI tool fails and doesn't generate a tailwind.config.js file".
> > > > If you are having some sort of issue with Tailwind UI + Node 14 please open an issue and explain the problem, happy to help.
> > > 
> > > 
> > > Thanks so much for your reply @adamwathan. Following the instructions from tailwind, using node 14, i am unable to generate the tailwind.config.js file without doing the hacky version swapping and npm uninstall/install the diff versions. I am on Ubuntu 18.04 if that makes any difference.
> > > My comments are just that of slight annoyance regarding this working properly with Node 15, and not 14 :) I have not tested that myself though.
> > > Thanks.
> > 
> > 
> > How did you install node? If you use nvm, you can easily switch between node versions.
> 
> using the standard install methods: https://github.com/nodesource/distributions/blob/master/README.md
> 
> I just dont think the issue should be closed because if users are following the exact instructions from TailWind and finding issues, thats bad. At the very least the tailwind docs should account for or document this stuff. I dont want to use tailwind at this point if I cant just install it and have it work right out the gate.
> 
> Finding the solution to my problems in a closed github issue doesnt make me feel good. Just a user perception comment.

I agree!

**Comment by adamwathan** [comment] 2021-06-04 17:21
Got it I see where people would run into this now! Updated the CRA instructions to use `tailwindcss-cli` instead of `tailwindcss` which should make it always work no matter what for everyone.

**Comment by eyooooo** [comment] 2021-06-04 17:24
> 
> 
> Got it I see where people would run into this now! Updated the CRA instructions to use `tailwindcss-cli` instead of `tailwindcss` which should make it always work no matter what for everyone.

you're a friggin rockstar @adamwathan i will test and if you dont hear back from me assume all is good!!! thanks so much and have a wonderful weekend.

**Comment by eyooooo** [comment] 2021-06-05 01:23
Just want to confirm that all is good now. Thanks so much.

**Comment by Hamdrive** [comment] 2021-06-07 17:19
Glad to see that the solution has been found! Thank you Adam!

**Comment by Hossain-Bin-Ishak** [comment] 2021-06-09 06:22
> I had trouble generating the configuration file while using the compatibility package. I updated my tailwindcss, postcss, and autoprefixer packages to the latest versions and this allowed me to generate a configuration successfully. I then downgraded my packages back to the compatibility versions.
> 
> ```
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@latest postcss@latest autoprefixer@latest
> 
> npx tailwindcss init -p
> 
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```

I have followed the steps but still having the following error when I go to run npx tailwindcss-cli@latest init

These are the errors:

$ npx tailwindcss-cli@latest init -p
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Hossain\AppData\Roaming\npm-cache\_npx\14852" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\I'm Hossain\AppData\Roaming\npm-cache\_logs\2021-06-09T06_19_24_000Z-debug.log
Install for [ 'tailwindcss-cli@latest' ] failed with code 1

Can anybody please help me to solve this problem? 

Thanks in advanced.

**Comment by MouadAmzil** [comment] 2022-01-11 13:37
`npm install tailwindcss@latest postcss@latest autoprefixer@latest
`add this command before 
and check your **### package.json**

```
  "dependencies": {
      "autoprefixer": "^10.4.2",
      "postcss": "^8.4.5"
    }
```
add commend ### **$ npx tailwindcss init**
**result -->**
Created Tailwind CSS config file: tailwind.config.js

**Comment by Ps00007** [comment] 2022-01-21 20:36
'tailwind' is not recognized as an internal or external command,
operable program or batch file

**Comment by sherwinmartin** [comment] 2022-01-29 18:33
i ran into a similar issue. i fixed it by installing a more recent version of nodejs. the environment i was using is ubuntu but installed the nodejs using the default repo which has v10.x. i installed LTS v16.x and it works.

**Comment by KarmaBlackshaw** [comment] 2022-09-05 04:24
Still running the same issue with vue2

Node: v14.18.3
```json
{
  "vue": "^2.5.17",
  "autoprefixer": "^10.4.8",
  "postcss": "^8.4.16",
  "postcss-loader": "^4.3.0",
  "tailwindcss": "^3.1.8",
}
```

**Comment by valeria-daffarra** [comment] 2022-11-21 16:44
> I had trouble generating the configuration file while using the compatibility package. I updated my tailwindcss, postcss, and autoprefixer packages to the latest versions and this allowed me to generate a configuration successfully. I then downgraded my packages back to the compatibility versions.
> 
> ```
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@latest postcss@latest autoprefixer@latest
> 
> npx tailwindcss init -p
> 
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```

I LOVE YOU, thanks a lot!!

**Comment by RodrigoVieira19** [comment] 2023-05-18 23:06
> I have been run `npx tailwindcss init` and it shows **Cannot find module 'autoprefixer'**.
> 
> Node version: 14.15.1 LTS NPM version: 6.14.9 OS: macOS Big Sur
> 
> <img alt="Screen Shot 2020-12-04 at 21 50 47" width="591" src="https://user-images.githubusercontent.com/11099186/101171513-d73de580-367a-11eb-8e16-ac55ff5bc72a.png">
> 
> **UPDATE**
> 
> I run instruction what @JackWatling said below and it works well.
> 
> ```
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@latest postcss@latest autoprefixer@latest
> 
> npx tailwindcss init -p
> 
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```

it worked. thank you very much

**Comment by RodrigoVieira19** [comment] 2023-05-18 23:07
> I had trouble generating the configuration file while using the compatibility package. I updated my tailwindcss, postcss, and autoprefixer packages to the latest versions and this allowed me to generate a configuration successfully. I then downgraded my packages back to the compatibility versions.
> 
> ```
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@latest postcss@latest autoprefixer@latest
> 
> npx tailwindcss init -p
> 
> npm uninstall tailwindcss postcss autoprefixer
> npm install tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9
> ```

it worked. thank you very much

**Comment by MurakawaTakuya** [comment] 2025-02-08 15:47
# Problem
In my case, I was trying to init tailwindcss in the Next.js project and faced this problem as below.
```bash
> npm install tailwindcss @tailwindcss/postcss postcss

> npx tailwindcss init -p  
npm error could not determine executable to run
npm error A complete log of this run can be found in: ###
```
And adding `@latest` didn't solve the problem this time. > https://github.com/tailwindlabs/tailwindcss/issues/2831#issuecomment-731038281

Node.js: v22.13.1
npm: 11.1.0

# Solution
Tried this init command and this worked in this case.
```bash
> npx tailwindcss-cli@latest init
Created Tailwind CSS config file: tailwind.config.js
```

Hope this also helps
