### ISSUE TITLE
Tailwind CSS (PostCSS Plugin) with Next.js 10.0.3 gives Javascript heap out of memory error in dev environment

### ISSUE THREAD

**Issue by ceodigvijay** [tailwindlabs/tailwindcss#3149] opened 2020-12-20 12:19 UTC
### Describe the problem:

I am using TailwindCSS 2.0.2 with Next.js 10.0.3.
TailwindCSS plugin is causing very high memory requirement for Next.js, sometimes it also throws Javascript heap out of memory error.

Hot reloading is slow (even if I manage it in some way) but the real pain is Next.js+tailwinds setup takes 2-3x memory compared to others (like I was using Bulma)
With Next.js+Bulma/Bootstrap setup = 250mb
With Next.js+TailwindCSS as PostCSS plugin = 720mb-1.5gb memory

### Link to a minimal reproduction:

Clone this repo.
https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss

and run it in next.js dev environment and watch out your memory usage (generally it remains around 200-300MB but with Tailwinds 1.2gb). 

* I tried to debug it and as soon as I disable tailwinds plugin in PostCSS everything again goes normal. *

The real problem seems to be in tailwinds PostCSS Plugin.

PS: DO NOT RECOMMEND TO INCREASE NODE.js MEMORY LIMITS as we do not have supercomputers online to host applications.

**Comment by mrroll** [comment] 2020-12-20 18:46
I can confirm this from my end as well. Was playing around with tailwind this weekend and noticed that fast refresh was slow. Running the NextJS development server for a some time does trigger an OOM error eventually. Haven't had time to do profiling to get a clue on what's actually causing it though.

**Comment by navicstein** [comment] 2021-01-07 21:42
I can also confirm this, I thought it was from node, as a workaround I added this to my `~/.zshrc`
```sh
NODE_OPTIONS=--max_old_space_size=4024 # or less
```

**Comment by marvinkome** [comment] 2021-01-08 05:29
I experience this too and it's pretty annoying

**Comment by yakovlevyuri** [comment] 2021-02-24 17:33
Same here :(

**Comment by danielfilho** [comment] 2021-03-01 00:24
I had this problem, researched everything everywhere and nothing was working.

It turns out, was my own fault: I was calling a component inside itself, because of my vscode code complete, like:

```js
const Foobar = ({ children }) => ( 
  <Foobar>
    { children }
  </Foobar>
)
```

I think it's worth checking if this happens, and I feel really stupid for wasting so much time on it 🤦‍♂️ 

One of THOSE issues :)

**Comment by adamwathan** [comment] 2021-03-17 13:58
Tailwind generates a ton of CSS so depending on how much stuff you have in your config file, it can require a lot of memory for webpack to process it. This is expected although of course not ideal, which is why we have been working on a new engine:

https://blog.tailwindcss.com/just-in-time-the-next-generation-of-tailwind-css

Going to close this as the new engine is the solution, and is available to try at https://github.com/tailwindlabs/tailwindcss-jit 👍🏻

**Closed by adamwathan** 2021-03-17 13:58 UTC

**Comment by kioltk** [comment] 2021-05-05 18:29
However version 2.1.2 still has out of memory error.
```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(18:5) /var/www/resources/css/app/components/select.css The `` class does not exist. If you're sure that `` exists, make sure that any `@import` statements are being properly processed before Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  16 |
  17 |   .react-select__indicator {
> 18 |     @apply
     |     ^
  19 |   }
  20 |

    at processResult (/var/www/node_modules/webpack/lib/NormalModule.js:676:19)
    at /var/www/node_modules/webpack/lib/NormalModule.js:778:5
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/var/www/node_modules/postcss-loader/dist/index.js:94:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
ℹ Compiling Mix

<--- Last few GCs --->

[25:0xaaab20ffb260]   529705 ms: Mark-sweep 2033.2 (2061.1) -> 2028.1 (2061.4) MB, 502.3 / 0.0 ms  (average mu = 0.133, current mu = 0.022) allocation failure scavenge might not succeed
[25:0xaaab20ffb260]   530219 ms: Mark-sweep 2036.1 (2061.4) -> 2030.9 (2063.9) MB, 504.1 / 0.0 ms  (average mu = 0.083, current mu = 0.019) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ hot: `mix watch --hot`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ hot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-05T18_26_05_865Z-debug.log
```
