### ISSUE TITLE
"Doubled" CSS output when purge includes "./**/*.md"

### ISSUE THREAD

**Issue by vladdu** [tailwindlabs/tailwindcss#4714] opened 2021-06-19 12:58 UTC
### What version of Tailwind CSS are you using?

2.2.2

### What build tool (or framework if it abstracts the build tool) are you using?

tailwind-cli 2.2.2

### What version of Node.js are you using?

14.17.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows

### Reproduction repository

https://github.com/vladdu/tw_bug_doubled_css

### Describe your issue

If the purge list includes "./**/*.{html,md}", it will pick all HTML and markdown files from node_modules. This keeps some unexpected classes from being purged, which is not a big deal, but the JIT compiler will "double" the CSS from the @tailwind pragmas, like the excerpt below. Note the additional lines with !important. I don't know if that is a real problem, but it was confusing to me.

The generated file in the reproduction repo is in out/main_jit.css

```
/*! tailwindcss v2.2.2 | MIT License | https://tailwindcss.com */

/*! tailwindcss v2.2.2 | MIT License | https://tailwindcss.com */

/*! modern-normalize v1.1.0 | MIT License | https://github.com/sindresorhus/modern-normalize */

/*! modern-normalize v1.1.0 | MIT License | https://github.com/sindresorhus/modern-normalize */

/*
Document
========
*/

/*
Document
========
*/

/**
Use a better box model (opinionated).
*/

/**
Use a better box model (opinionated).
*/

*,
::before,
::after {
  box-sizing: border-box;
  box-sizing: border-box !important;
}
```

**Comment by tleish** [comment] 2021-06-20 20:09
May be related to #4701

**Comment by jskorlol** [comment] 2021-06-21 02:35
https://github.com/tailwindlabs/tailwindcss/discussions/4721

I'm having the same problem.

**Comment by bradlc** [comment] 2021-06-21 14:12
Hey @vladdu. Thanks for reporting this. I looked into your reproduction and it turns out that it's actually related to `!*` being found in one of the `.md` files. I hope you don't mind but I am going to close this issue in favour of [a new one](https://github.com/tailwindlabs/tailwindcss/issues/4746) with a more specific and minimal reproduction. Thanks again!

**Closed by bradlc** 2021-06-21 14:12 UTC

**Comment by vladdu** [comment] 2021-06-21 14:14
Sure, no problem! Thanks!
