### ISSUE TITLE
Can't get TailwindCSS emmet abbreviation to work

### ISSUE THREAD

**Issue by zozok3rr** [tailwindlabs/tailwindcss#6158] opened 2021-11-21 14:29 UTC
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/6157

<div type='discussions-op-text'>

<sup>Originally posted by **zozok3rr** November 21, 2021</sup>
Hello there!

I am a novice and a beginner to this amazing framework, and for the first time ever I also have decided to start learning a framework for Javascript - React.

I cant seem to get emmet abbreviation working with Tailwind and React. 
Instead, it just gives me a list of properties it will have I suppose, and after I press ENTER it still doesn't do anything. 

I did download the Intellisense, an extension for VSCode, I tried adding settings to the JSON file. 
It shows just properties, but not a shortcut to an abbreviated style
Can someone assist please ?
Edit: Sorry. I am super new to all things programming
![image](https://user-images.githubusercontent.com/69513287/142765944-d8d3ceb1-197e-4de9-a09d-2a5d2458b30d.png)

</div>

**Comment by aggreggator** [comment] 2021-11-21 14:47
Try to press TAB instead ENTER.

**Comment by adamwathan** [comment] 2021-11-21 15:23
Closing in favor of the discussion thread you already created since this is not a bug with the framework.

**Closed by adamwathan** 2021-11-21 15:23 UTC
