### ISSUE TITLE
No rebuild css in jit mode using watch on postcss 7

### ISSUE THREAD

**Issue by huibizhang** [tailwindlabs/tailwindcss#5132] opened 2021-08-01 10:11 UTC
### What version of Tailwind CSS are you using?

v2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

postcss 7

### What version of Node.js are you using?

14.17.3

### What browser are you using?

N/A

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/huibizhang/create-react-app

### Describe your issue

This problem is occurring at postcss 7 environment, like Vue-CLI and Create React App.

Tailwind's version over 2.1.4 and come to 2.2, use following steps of document [Installation](https://tailwindcss.com/docs/installtation) to install and setup jit mode are invalid.

When add a new class after tailwind first build on dev server opened, it not works. I have to reopen dev server, and the class well be actived.

For example: on cra, use following step to setup jit mode with tailwind 2.1.4, its running very well. 
But, when everything as same as 2.1.4 that I do,  just tailwind version comes to 2.2, jit's rebuild is not working.

Ummm ... I'm trying to use tailwindcss-cli to watch files and include output file in js
```shell
tailwindcss-cli -i tailwind.css -o index.css -w
```
It works, but tailwindcss-cli dependent postcss 8, but project just can using postcss 7, I'm worry that maybe something will getting wrong in feature.

That's all my questions, thank you!

**Comment by adamwathan** [comment] 2021-08-01 11:33
Hey! Please provide a reproduction otherwise I can't help.

**Comment by huibizhang** [comment] 2021-08-01 12:14
> Hey! Please provide a reproduction otherwise I can't help.

Thanks your for your remind. I undated.

**Comment by huibizhang** [comment] 2021-08-01 12:14
@adamwathan Thanks your for your remind. I undated.

**Comment by shantiscript** [comment] 2021-08-03 12:25
just had the same issue setting up a new create-react-app. In jit mode new classes where only added when restarting the node dev server. 
Downgrading Taiwlind to below 2.1.4 solved the issue for now

**Comment by huibizhang** [comment] 2021-08-03 23:04
@shantiscript  , thanks for replied !
That's truly a solution.

Yes, I know 2.1.4 is okay, but I need some new variants in 2.2 like before and after.

I'm popularizing and teaching Tailwind in Taiwan. And recently, sometimes student ask me how to watching css successful in jit mode of tailwind 2.2

This is the temporary solution for me.
I try to mix postcss7 and postcss8, it works, but it's so dangerous XD
https://github.com/huibizhang/template-cra-tailwind-jit-v2.2

**Comment by huibizhang** [comment] 2021-08-06 22:31
@adamwathan , @shantiscript thanks a ton,
I find the solution for this.

At postcss 7, set enviornment variables `TAILWIND_MODE=watch` can prefectally work.
```diff
  "scripts": {
+   "start": "cross-env TAILWIND_MODE=watch craco start",
    "build": "craco build",
    "test": "craco test",
    "eject": "react-scripts eject"
  },
```
linux based can only `"start": "TAILWIND_MODE=watch craco start"`
but I'm using Windows, so I need to install package `cross-env`, 
`cross-env` also can works on linux based.
It's same problem on vue-cli 4, and this solution can resolved too.

This is my test:
https://github.com/huibizhang/create-react-app/tree/resolved

**Comment by bradlc** [comment] 2021-08-12 12:19
Hey @huibizhang. It looks like you found the solution so I'm going to close this 👍 If you haven't already, check out the JIT documentation that explains why you might need `TAILWIND_MODE=watch`: https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files

**Closed by bradlc** 2021-08-12 12:19 UTC

**Comment by Yellow-cxq** [comment] 2023-09-20 03:39
> @adamwathan , @shantiscript thanks a ton. I find the solution for this.
> 
> on postcss 7, set enviornment variables `TAILWIND_MODE=watch` can prefectally work.
> 
> ```diff
>   "scripts": {
> +   "start": "cross-env TAILWIND_MODE=watch craco start",
>     "build": "craco build",
>     "test": "craco test",
>     "eject": "react-scripts eject"
>   },
> ```
> 
> linux based can only `"start": "TAILWIND_MODE=watch craco start"` but I'm using Windows, so I need to install package `cross-env`, `cross-env` also can works on linux based. It's same problem on vue-cli 4, and this solution can resolved too.
> 
> This is my test: https://github.com/huibizhang/create-react-app/tree/resolved

in Umi , It's useless
