### ISSUE TITLE
ModuleBuildError: Module build failed by postcss-loader and getTailwindConfig

### ISSUE THREAD

**Issue by iSuslov** [tailwindlabs/tailwindcss#11294] opened 2023-05-26 06:28 UTC
**What version of Tailwind CSS are you using?**

For example: v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 13.4.3

**What version of Node.js are you using?**

For example: v18.15.0

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

1. create a new next app with tailwind `npx create-next-app@latest`
2. run it in firebase hosting emulator:
- `firebase init`
-  `firebase emulators:start`

**Describe your issue**
Here:
https://github.com/tailwindlabs/tailwindcss/blob/0917fcaa338d13dff7ca66b8dbeacb1df8df75a0/src/lib/setupTrackingContext.js#L64-L70

Line 66 you have question mark property accessor `?.config`. But somehow it gets compiled to:

```
   let newConfig = (0, _resolveconfig.default)(configOrPath.config === undefined ? configOrPath : configOrPath.config);
```

which causes an error when no config found:

```
Server Error
ModuleBuildError: Module build failed (from ./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js):
TypeError: Cannot read properties of undefined (reading 'config')
    at getTailwindConfig (/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:87:62)
    at /Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:99:92
    at /Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/processTailwindFeatures.js:48:11
    at plugins (/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/plugin.js:38:63)
    at LazyResult.runOnRoot (/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js:206:17)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:447:9)

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
getTailwindConfig
/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/lib/setupTrackingContext.js (87:62)
<unknown>
/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/lib/setupTrackingContext.js (99:92)
<unknown>
/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/processTailwindFeatures.js (48:11)
plugins
/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/plugin.js (38:63)
LazyResult.runOnRoot
/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js (339:16)
LazyResult.runAsync
/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js (393:26)
LazyResult.async
/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js (221:30)
LazyResult.then
/Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js (206:17)
processTicksAndRejections
node:internal/process/task_queues (95:5)
runNextTicks
node:internal/process/task_queues (64:3)
process.processImmediate
node:internal/timers (447:9)
getTailwindConfig
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/lib/setupTrackingContext.js (87:62)
<unknown>
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/lib/setupTrackingContext.js (99:92)
<unknown>
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/processTailwindFeatures.js (48:11)
plugins
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/tailwindcss/lib/plugin.js (38:63)
LazyResult.runOnRoot
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js (339:16)
LazyResult.runAsync
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js (393:26)
LazyResult.async
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js (221:30)
LazyResult.then
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/node_modules/postcss/lib/lazy-result.js (206:17)
processTicksAndRejections
node:internal/process/task_queues (95:5)
runNextTicks
node:internal/process/task_queues (64:3)
process.processImmediate
node:internal/timers (447:9)
processResult
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/dist/compiled/webpack/bundle5.js (28:394802)
<unknown>
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/dist/compiled/webpack/bundle5.js (28:396519)
<unknown>
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js (1:8645)
<unknown>
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js (1:5828)
r.callback
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/dist/compiled/loader-runner/LoaderRunner.js (1:4039)
<unknown>
file:///Users/zuzel/Projects/hs/_testingNext/n13/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js (113:37)
processTicksAndRejections
node:internal/process/task_queues (95:5)
runNextTicks
node:internal/process/task_queues (64:3)
process.processImmediate
node:internal/timers (447:9)
```

**Comment by adamwathan** [comment] 2023-05-26 10:01
Hey! This error was recently fixed in `master` and only happened when forgetting to create a `tailwind.config.js` file. Can you ensure you have a `tailwind.config.js` file? If it's happening even with a config file can you please provide a reproduction? We require reproductions in order to address issues as per the issue template.

**Comment by iSuslov** [comment] 2023-05-27 03:54
Hey, I'm absolutely positive that `tailwind.config.js` is present in my app folder, however I'm not sure this is actually an issue with tailwind, because it happens only with firebase emulators and somehow related to emulated folder structure. I created an issue here https://github.com/firebase/firebase-tools/issues/5903

Maybe emulators screw up file system if started from outside dir. Feel free to close this issue if you agree.

**Comment by Hollywilson90** [comment] 2023-06-22 11:56
Thanks for the information.

**Comment by t6adev** [comment] 2023-07-06 07:29
I also faced almost the same issue, `TypeError: Cannot read properties of undefined (reading 'config') `, with a combination of TS + ESM("type": "module") + Vite middleware.
I gave up this issue then when I tried using Vite@4.4.0-beta.4 with lightningcss instead of postcss, I could resolve it.
https://main.vitejs.dev/config/shared-options.html#css-transformer

So, this issue is related to postcss, not tailwindcss.

**Comment by smyja** [comment] 2023-07-18 10:27
i am still facing this isssue

**Comment by thecrypticace** [comment] 2023-08-02 17:12
@t6adev @smyja Hey, could either of you provide reproduction repos that we can look at?

**Comment by reinink** [comment] 2023-08-17 20:55
Hey folks! I'm going to close this issue as there hasn't been any updates here in a couple of weeks. If you're still experiencing this issue, could you please provide a minimal reproduction as a Git repo for us to reproduce this on our end? Thanks! 🙏

**Closed by reinink** 2023-08-17 20:55 UTC

**Comment by bebbi** [comment] 2023-09-01 06:09
@adamwathan FWIW we have a design system with tailwind components and therefore have to export its `tailwind.config.ts` too, moving it into `src/`.
`tsc` builds do work but storybook failed with the OP error. Our work-around was to symlink `src/tailwind.config.ts` to the package root. I'm sure there are better ways for this though.

**Comment by Danishkhan79059** [comment] 2024-12-11 10:50
Module build failed (from ./node_modules/react-scripts/node_modules/postcss-loader/dist/cjs.js):  when i stasrt my react js frontend project i got this error how can i  sovle this issue if any plese send methe solution in this khandanish30599@gmail.com mail

**Comment by Sethmaurice** [comment] 2025-05-07 08:51
ERROR in ./src/index.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/index.css)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: It looks like you're trying to use `tailwindcss` directly as a PostCSS plugin. The PostCSS plugin has moved to a separate package, so to continue using Tailwind CSS with PostCSS you'll need to install `@tailwindcss/postcss` and update your PostCSS configuration.
    at Le (C:\Users\HP\Desktop\har\harambeef\node_modules\tailwindcss\dist\lib.js:36:1984)
    at LazyResult.runOnRoot (C:\Users\HP\Desktop\har\harambeef\node_modules\postcss\lib\lazy-result.js:361:16)
    at LazyResult.runAsync (C:\Users\HP\Desktop\har\harambeef\node_modules\postcss\lib\lazy-result.js:290:26)
    at LazyResult.async (C:\Users\HP\Desktop\har\harambeef\node_modules\postcss\lib\lazy-result.js:192:30)
    at LazyResult.then (C:\Users\HP\Desktop\har\harambeef\node_modules\postcss\lib\lazy-result.js:436:17)

React+Typescript
email: sethmaurice1@gmail.com if you can solve it for me thanks
