### ISSUE TITLE
Tailwind not working properly with laravel mix

### ISSUE THREAD

**Issue by jenishshrestha** [tailwindlabs/tailwindcss#4833] opened 2021-06-30 13:45 UTC
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

laravel mix 6.0.6

### What version of Node.js are you using?

v 15.11.0

### What browser are you using?

Chrome / Brave

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/jenishshrestha/wp-tailwind-theme

### Describe your issue

1.  The first issue I am facing is whenever I run **npm run watch** I am getting infinite compilation. Issue is probably in this line in config file:
`"./*.php",`
  `mode: 'jit'`, is enabled FYI.

2. After a while tailwind classes stopped working properly. For example some of the base css stopped working like h2 h3 font sizes etc.

3. If I use a css class, **-rotate-90**, expected css outcome would be 
`--tw-rotate: -90deg;
transform: rotate(-90deg);`
but instead its only
`--tw-rotate: -90deg;`

I am stucked, cant progress further.

**Comment by RockSharabShrestha** [comment] 2021-06-30 14:00
Don't send me mail please.

**Comment by jenishshrestha** [comment] 2021-06-30 14:10
Ok

**Comment by RockSharabShrestha** [comment] 2021-06-30 14:13
Then remove that comment.

**Comment by jenishshrestha** [comment] 2021-06-30 14:22
What's happening here? Isn't this the repo where you are suppose to get help related with tailwind?
Also I don't know who you are and how you are getting email from this issue.

Thanks,

**Comment by adamwathan** [comment] 2021-07-01 10:06
@RockSharabShrestha You have probably subscribed to notifications on this repo somehow, just go to GitHub and disable it:

https://github.com/tailwindlabs/tailwindcss

<img width="513" alt="image" src="https://user-images.githubusercontent.com/4323180/124106636-61dc9c80-da32-11eb-988e-89313176ed68.png">

**Comment by adamwathan** [comment] 2021-07-01 10:08
@jenishshrestha For the infinite loop problem see the docs here:

https://tailwindcss.com/docs/just-in-time-mode#styles-rebuild-in-an-infinite-loop

Will try to find time to look into the other stuff soon.

One option you can use in the mean time is to just switch to the Tailwind CLI for compiling your CSS, as we have full control over that and can guarantee it is reliable. Mix is awesome but when you have a lot of things kind of working together sometimes it's hard to get the integrations just right, so you might be hitting a bug we haven't found yet.

**Comment by federicocappellotto97** [comment] 2021-07-07 09:39
> @jenishshrestha For the infinite loop problem see the docs here:
> 
> https://tailwindcss.com/docs/just-in-time-mode#styles-rebuild-in-an-infinite-loop
> 
> Will try to find time to look into the other stuff soon.
> 
> One option you can use in the mean time is to just switch to the Tailwind CLI for compiling your CSS, as we have full control over that and can guarantee it is reliable. Mix is awesome but when you have a lot of things kind of working together sometimes it's hard to get the integrations just right, so you might be hitting a bug we haven't found yet.

I have the same problem, with Mix and watch i got infinite loop. But i can't use tailwind CLI because with that i can't use tailwind plugin. Any solution?

**Comment by adamwathan** [comment] 2021-07-07 10:08
@federicocappellotto97 Hey! The docs explain how to avoid the infinite loop problem:

https://tailwindcss.com/docs/just-in-time-mode#styles-rebuild-in-an-infinite-loop

You _can_ use Tailwind plugins with Tailwind CLI though, just install them and configure them in your `tailwind.config.js` file as usual.

**Comment by federicocappellotto97** [comment] 2021-07-07 10:24
> @federicocappellotto97 Hey! The docs explain how to avoid the infinite loop problem:
> 
> https://tailwindcss.com/docs/just-in-time-mode#styles-rebuild-in-an-infinite-loop
> 
> You _can_ use Tailwind plugins with Tailwind CLI though, just install them and configure them in your `tailwind.config.js` file as usual.

Can i choose Tailwind version with Tailwind CLI?

**Comment by federicocappellotto97** [comment] 2021-07-07 11:49
> @federicocappellotto97 Hey! The docs explain how to avoid the infinite loop problem:
> 
> https://tailwindcss.com/docs/just-in-time-mode#styles-rebuild-in-an-infinite-loop
> 
> You _can_ use Tailwind plugins with Tailwind CLI though, just install them and configure them in your `tailwind.config.js` file as usual.

Thanks! I resolved compiling my sass with Mix and Tailwind with Tailwind CLI

**Comment by jenishshrestha** [comment] 2021-07-14 04:01
For now, I am manually adding the files from the root directly instead of this `"./*.php",`. Its working perfectly.

**Comment by adamwathan** [comment] 2021-09-27 13:28
I'm going to close this because there hasn't been any activity since July so I'm guessing this is working better in recent versions. If still an issue of course please open a new issue with a reproduction and we will do our best to figure it out, thanks! 🍻

**Closed by adamwathan** 2021-09-27 13:28 UTC

**Comment by f-liva** [comment] 2021-12-20 17:18
Issue still here, you can reopen please

**Comment by nashki** [comment] 2021-12-22 18:40
I have the same problem, tailwind is not working properly when using a certain class.

for example, when I want to change the background color, it doesn't work at first.
then i try to add manual in tailwind.config.js file theme section. 
it's working

**Comment by younesftaich** [comment] 2021-12-23 15:06
same issue

**Comment by joshuafredrickson** [comment] 2022-02-16 18:51
For those arriving from Google, this solution allows you to use glob patterns, even in tools like Laravel Mix:
https://github.com/laravel-mix/laravel-mix/issues/1942#issuecomment-998148038
