### ISSUE TITLE
Putting html classes with `dark:` variant doesn't work if `darkMode: 'class'`

### ISSUE THREAD

**Issue by ymatuhin** [tailwindlabs/tailwindcss#3655] opened 2021-02-25 23:44 UTC
Dark-mode as class.
Add to html tag any class with `dark:`.
No effect.

**Comment by bradlc** [comment] 2021-02-26 11:09
Hey @ymatuhin. There's a couple of things to check here:

- By default, dark variants are only generated for color-related classes, which includes text color, background color, border color, gradients, and placeholder color. If you want to use it with other classes you will need to ensure that you have [enabled it in your variants config](https://tailwindcss.com/docs/configuring-variants).
- Since you are using the `class` mode, check that you have added the `dark` class to a parent element. [Take a look at the docs for more information](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually).

If you've checked these and it's still not working please could you share a project which reproduces the issue? Much easier to debug that way 👍

**Comment by ymatuhin** [comment] 2021-02-26 11:36
> Since you are using the class mode, check that you have added the dark class to a parent element. Take a look at the docs for more information.

HTML has no parent tag, that's the issue. HTML with classes `dark bg-white dark:bg-black` doesn't apply dark background.
I understand why it doesn't work, but it looks like it should, because it's recommended to do this way.

<img width="842" alt="Screenshot 2021-02-26 at 14 34 15" src="https://user-images.githubusercontent.com/3757971/109295373-b6cb9480-783f-11eb-99b5-99cef78ad33d.png">

**Comment by bradlc** [comment] 2021-02-26 11:40
Ah sorry I didn't realise you meant the `<html>` element itself! In that case you can move your classes to the `<body>` element and put the `dark` class on `<html>`:

```html
<!DOCTYPE html>
<html lang="en" class="dark">
  <!-- ... -->
  <body class="bg-white text-black dark:bg-black dark:text-white"></body>
  <!-- ... -->
</html>
```

**Comment by ymatuhin** [comment] 2021-02-27 16:20
Yeah, but `body` and `html` kinda different with background handling. I actually need to set it to html to work properly on macOS when scroll. Sure there are some workarounds but docs are missleading us here.

**Comment by bradlc** [comment] 2021-02-27 16:38
> Yeah, but body and html kinda different with background handling. I actually need to set it to html to work properly on macOS when scroll.

Can you provide an example? [As long as you don't set a background on `<html>` you shouldn't have any issues.](https://css-tricks.com/just-one-of-those-weird-things-about-css-background-on-body/)

**Comment by ymatuhin** [comment] 2021-02-27 16:54
Holy moly, you are right. I'm totally fine to move classes from html to body and this can be closed.
Just an opinion that it should be described somewhere in docs. In screenshot above you actually set background on body, but don't tell why :)
Thanks for your help.

**Comment by benji014628** [comment] 2021-03-01 00:57
> Holy moly, you are right. I'm totally fine to move classes from html to body and this can be closed.
> Just an opinion that it should be described somewhere in docs. In screenshot above you actually set background on body, but don't tell why :)
> Thanks for your help.

wait so why isn't this closed then...

**Comment by ymatuhin** [comment] 2021-03-01 12:40
> Just an opinion that it should be described somewhere in docs.
If you think it shouldn't, feel free to close this. Otherwise, it may serve as a reminder.

**Comment by benji014628** [comment] 2021-03-01 15:27
> > Just an opinion that it should be described somewhere in docs.
> 
> If you think it shouldn't, feel free to close this. Otherwise, it may serve as a reminder.

Umm only you can close it....

**Closed** 2021-03-02 13:24 UTC
