### ISSUE TITLE
Negative values not compiled in TW v3

### ISSUE THREAD

**Issue by usernotnull** [tailwindlabs/tailwindcss#6463] opened 2021-12-13 15:55 UTC
**What version of Tailwind CSS are you using?**
TW v3.0.2
laravel mix 6.0.39

**What operating system are you using?**
Windows, wsl2

**Describe your issue**
After migrating to TW v3, none of the negative values are being compiled into app.css,
such as -mt-8, -bottom-2, etc...

**Comment by reinink** [comment] 2021-12-15 14:51
Hey! I just tried this, and it seems to work. Here's a Tailwind Play illustrating this:

https://play.tailwindcss.com/Vi2oUbnmlA

In these situations we *really need* a minimal reproduction as required in the issue template:

> A Tailwind Play link or public GitHub repo that includes a minimal reproduction of the bug. **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we can't provide support without a reproduction, and your issue will be closed with no comment if this is not provided.

I am going to close this — but feel free to provide a minimal reproduction, and I'd be happy to have another look 👍

**Closed by reinink** 2021-12-15 14:51 UTC

**Comment by usernotnull** [comment] 2021-12-18 06:14
The issue was the below line, which was added for the lib yassinebridi/tailwind-direction

```
presets: [
  require("tailwind-direction").configPreset,
],
```

I'll move the discussion there.

**Comment by reinink** [comment] 2021-12-20 12:57
@usernotnull Glad you figured out the cause of the issue 👍
