### ISSUE TITLE
Tailwind not purgin without mode: 'all'

### ISSUE THREAD

**Issue by cfinnberg** [tailwindlabs/tailwindcss#3869] opened 2021-03-29 08:08 UTC
### What version of Tailwind CSS are you using?

v.2.0.4

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

N/A

### What operating system are you using?

Linux

### Reproduction repository

-

Tailwind seems to not purge **anything** unless **mode: 'all'** is added to the purge config. I am just trying Tailwind with the simplest configuration: Not using any library/tool (not even PostCSS).
I have this configuration file:
```config.js
// tailwind.config.js
module.exports = {
  purge: {
    enabled: true,
    content: ['./src/**/*.html',],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```
As source file I have `src/test.html`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="tailwind.css">
    <title>Tailwind test</title>
</head>
<body>
    <h1 class="text-center">Tailwind test</h1>
</body>
</html>
```
The build result is almost the same file (only some spacing stripped):
```
> npx tailwindcss-cli@latest build ./src/tailwind.css -o ./tailwind_prod.css
npx: installed 89 in 3.124s
  
   tailwindcss 2.0.4
  
   🚀 Building: src/tailwind.css
  
   ✅ Finished in 1.93 s
   📦 Size: 3.74MB
   💾 Saved to tailwind_prod.css
```

But if I add the `mode:'all`' to the configuration...:
```config.js
module.exports = {
  purge: {
    enabled: true,
    mode: 'all',
    content: ['./src/**/*.html',],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

Then it works as expected:
```
> npx tailwindcss-cli@latest build ./src/tailwind.css -o ./tailwind_prod.css
npx: installed 89 in 3.396s
  
   tailwindcss 2.0.4
  
   🚀 Building: src/tailwind.css
  
   ✅ Finished in 1.87 s
   📦 Size: 10.62KB
   💾 Saved to tailwind_prod.css
```

Maybe I'm understanding something terribly wrong, but from the documentation I understood that mode: 'all' is for 3rd party modules/libraries and my Tailwind CSS file should be purged without it.

**Comment by adamwathan** [comment] 2021-03-30 10:50
Please provide a reproduction repository, this definitely works since we use the default mode on all of our own sites so there must be some kind of configuration issue.

I've recreated locally based on the information you shared and it works here:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/4323180/112977554-3214b480-9124-11eb-924b-6f9c17be7200.png">

**Comment by mjtbkh** [comment] 2021-04-02 11:47
Try using a simple purge array, just do:

```
purge: [ './src/**/*.html', ],
```

**Comment by mjtbkh** [comment] 2021-04-02 11:50
Try setting 'NODE_ENV' to 'production', do like:

`NODE_ENV=production npx tailwindcss-cli@latest build ./src/tailwind.css -o ./tailwind_prod.css`

**Comment by adamwathan** [comment] 2021-04-02 11:54
Closing since no reproduction was provided and I cannot reproduce locally, please open a new issue with a reproduction though if you think you've found a real bug 👍🏻

**Closed by adamwathan** 2021-04-02 11:54 UTC
