### ISSUE TITLE
Edge Case: PurgeCSS + Keyframes

### ISSUE THREAD

**Issue by EvilLooney** [tailwindlabs/tailwindcss#1755] opened 2020-05-12 13:15 UTC
Hi,

I found myself in a condition where it might be helpful to perhaps add this to the documentation as a warning or something.

Background: I was manually running PurgeCSS prior to version 1.4; with the latest version, I decided to let Tailwind handle it.

Since PurgeCSS is now included, we can run into issues if your tailwind config resembles this and compiling for production:
```
purge: {
    enabled: true, /* this can be omitted when compiling for production */
    mode: 'conservative', /* this can be omitted */
    options: {
        keyframes: true
    }
}
```
and your CSS looks like:
```
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'my-file-with-keyframes.pcss';
@import 'tailwindcss/utilities';
```
For a reason I am unaware of, PurgeCSS will remove ALL keyframes in your own imported css files, regardless if they are used or not, even though we have selected `mode:'conservative'` (the default setting) that should only affect Tailwind's utilities.

Of course I initially made a mistake on my end and didn't select `mode:'all'` but was still dumbfounded why my keyframes disappeared.

**Comment by adamwathan** [comment] 2020-06-27 23:36
Interesting, wonder why this happens. Those styles should exist within a `purgecss start/end ignore` block at the time Purge runs so I wonder if this is something weird within Purge itself. Any chance you could create a simple test project that reproduces so I can troubleshoot it a bit faster?

**Comment by EvilLooney** [comment] 2020-07-08 00:52
Will do.

Give me a few weeks to do this as I am away on vacation.

**Comment by adamwathan** [comment] 2020-09-01 17:52
Going to close this since hasn't been any updates in a few months. Feel free to open a new issue with a reproduction if this is still an issue.

**Closed by adamwathan** 2020-09-01 17:52 UTC
Labels: needs reproduction
