### ISSUE TITLE
Latest version breaks application `v2.2.12`

### ISSUE THREAD

**Issue by Sebastma** [tailwindlabs/tailwindcss#5441] opened 2021-09-08 11:30 UTC
### What version of Tailwind CSS are you using?

2.2.12

### What build tool (or framework if it abstracts the build tool) are you using?

None

### What version of Node.js are you using?

v14.16.1

### What browser are you using?

chrome

### What operating system are you using?

w10

### Reproduction repository

https://unpkg.com/tailwindcss@2.2.12/dist/tailwind.min.css

### Describe your issue

using tailwind css from https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css breaks application. No css is rendered.
got version listed above. reverting to .2.2.11 fixed issue

**Comment by Adrion** [comment] 2021-09-08 11:49
Confirmed. 
I was calling https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css 
And new version breaks everything.

**Comment by enkota** [comment] 2021-09-08 11:56
Same issue here as @Adrion - broke quite a few sites that are using CDN versions.

**Comment by 0xEmma** [comment] 2021-09-08 11:59
Same issue here, set the link to `https://unpkg.com/tailwindcss@2.2.10/dist/tailwind.min.css` and it worked fine

**Comment by spaceemotion** [comment] 2021-09-08 12:20
Can also confirm. Only 2.2.10 seems to work for now when using the CDN release

**Comment by zack2** [comment] 2021-09-08 12:35
I have the same issue with this CDN https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css

**Comment by morwal-pawan** [comment] 2021-09-08 12:42
use this CDN  https://unpkg.com/tailwindcss@2.2.10/dist/tailwind.min.css , it wroks for me 

> Same issue here, set the link to `https://unpkg.com/tailwindcss@2.2.10/dist/tailwind.min.css` and it worked fine

thanks

**Comment by morwal-pawan** [comment] 2021-09-08 12:43
> Same issue here, set the link to `https://unpkg.com/tailwindcss@2.2.10/dist/tailwind.min.css` and it worked fine

thanks. it works for me

**Comment by chou666** [comment] 2021-09-08 12:52
As a workaround, I use previous version: 
https://unpkg.com/tailwindcss@2.2.11/dist/tailwind.min.css

**Comment by milosptr** [comment] 2021-09-08 13:00
There are two problems:
1. you have unclosed comment on the 3rd line
2. on each `@defaults border-width` property, there is unclosed tag of its parent


First problem: `/*,::after` this is the error

**In code:**
`/*! tailwindcss v2.2.12 | MIT License | https://tailwindcss.com */
/*! modern-normalize v1.1.0 | MIT License | https://github.com/sindresorhus/modern-normalize *
/*,::after,::before{
    box-sizing:border-box
}`



Second problem:` @defaults border-width {  ;  }` <-- here you are missing unclosed bracket, and mising some style

**In code:**
`.sm\:divide-x-2>:not([hidden])~:not([hidden]){  @defaults border-width {
                ;
            }
            .sm\:divide-dashed>:not([hidden])~:not([hidden]){
                border-style:dashed
            }
            `

**Comment by wongjn** [comment] 2021-09-08 13:40
This invalid `@defaults` syntax also shows up in final CSS when using the tailwind postcss plugin too, in `2.2.12` and `2.2.13`.

**Comment by vinayakkulkarni** [comment] 2021-09-08 13:57
Facing the same issue! reverting to 2.2.10 solves it temporarily though

**Comment by reinink** [comment] 2021-09-08 14:56
Hey there folks, the CDN build should be fixed in [v2.2.13](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.13).

**Comment by reinink** [comment] 2021-09-08 17:02
@wongjn We've just pushed another release ([v2.2.14](https://github.com/tailwindlabs/tailwindcss/releases/tag/v2.2.14)) which I'm hoping solves the issue you're running into. Can you please confirm?

**Comment by wongjn** [comment] 2021-09-08 17:09
@reinink Yep, seems to be fixed now, thank you!

**Comment by reinink** [comment] 2021-09-08 17:10
Awesome, thanks! 🤟

**Closed by reinink** 2021-09-08 17:10 UTC
