### ISSUE TITLE
undefined is not an object (evaluating 'originalFactory.call')

### ISSUE THREAD

**Issue by mrassili** [tailwindlabs/tailwindcss#7430] opened 2022-02-12 01:30 UTC
**What version of Tailwind CSS are you using?**

v3.0.22

**What build tool (or framework if it abstracts the build tool) are you using?**

gatsby

**What version of Node.js are you using?**

v16.14.0

**What browser are you using?**

Safari

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/gatsbyjs/gatsby-starter-landing-page + https://tailwindcss.com/docs/guides/gatsby

**Describe your issue**

I'm getting a runtime error after following the instructions to setup Tailwind with Gatsby [here](https://tailwindcss.com/docs/guides/gatsby)
Using this gatsby starter: https://github.com/gatsbyjs/gatsby-starter-landing-page

The issue is apparently triggered by the import of css (even though an empty css file)

Can someone please give me a hint on what could be the culprit ?

Tried two postcss configs:

```
module.exports = {
  plugins: [
    require("tailwindcss"),
    require("autoprefixer"),
  ],
};
```
&
```
const tailwindcss = require(`tailwindcss`);

module.exports = {
  plugins: [
    tailwindcss(`./tailwind.config.js`),
    require(`autoprefixer`),
  ]
};
```

**Comment by adamwathan** [comment] 2022-02-12 12:09
Hey! I have to close this as a reproduction was not provided. Asking us to create our own reproduction takes a lot more time and if everyone does that it’s impossible for us to keep up with the amount of questions we get, so we can only help with issues where reproductions are included.

If this is still an issue for you, please open a new issue but include a proper reproduction — a repo where you have already everything all set up so we can clone it and immediately see the issue without configuring everything by hand.

Sorry, we have to be strict about our issue policies though or we can’t keep up with the workload.

**Closed by adamwathan** 2022-02-12 12:09 UTC

**Comment by mrassili** [comment] 2022-02-13 20:35
For anyone encountering this error in the future, the issue was that I was importing the `./src/styles.css` file inside `gatsby-browser.js`, I needed to create a new css file `./src/styles/global.css` (as suggested in [tailwind guide](https://tailwindcss.com/docs/guides/gatsby)) and import it instead (not sure why though but it worked 🤷🏻 )

**Comment by samansayar** [comment] 2024-02-18 16:23
I think the problem is with the browser cache.
Clear the cache to solve your problem.

**Comment by 6f5** [comment] 2024-11-04 17:38
If you're getting the error after adding the `wrapElement()` hook to add a layout, make sure you're not using the same layout component on your pages. For example:

File: /gatsby-browser.js
```jsx
import * as React from "react";
import Layout from "./src/components/Layout";

export function wrapPageElement({ props, element }) {
  return <Layout {...props}>{element}</Layout>;
}
```

**Don't use the Layout component on the pages**
File:  /src/pages/index.jsx
```jsx
import * as React from "react"
import Layout from "../components/Layout"

function HomePage() {
  return <>
    <p>Hello, this is the Home Page!</p>
  </>
}


export const Head = () => <title>Home Page</title>

export default HomePage
```
