### ISSUE TITLE
Custom components and utilities not working with @apply in v4 beta

### ISSUE THREAD

**Issue by msfragala** [tailwindlabs/tailwindcss#15139] opened 2024-11-23 15:28 UTC
**What version of Tailwind CSS are you using?**

v4.0.0-beta.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Next.js 15.0.3

**What version of Node.js are you using?**

v20.11.1

**What browser are you using?**

N/A

**What operating system are you using?**

macOS

**Reproduction URL**

- [Codesandbox 1](https://codesandbox.io/p/devbox/tailwind-v4-bug-repro-1-kvr8rs)
- [Codesandbox 2](https://codesandbox.io/p/devbox/8yrwt5)

**Describe your issue**

Custom components and utilities defined in a JS config file do not work with `@apply` and result in a compile error that reads `Error: Cannot apply unknown utility class`. This is a regression from v3 since components and utilities were globally available in `@apply` before. This issue makes migrating to v4 quite difficult in codebases using `@apply`.

Likewise, utilities defined using `@utility` are only available in the file they are defined in. I didn't use `@layer utilities` in v3 so I don't know if this is a regression in behavior, but this does make `@utility` difficult to use in CSS modules. There is a workaround available since it _does_ work if you move your utilities into a separate file (e.g. `utilities.css`) and import that into the CSS module you want to use a utility in. But this feels obtuse.

From what I can tell, there is no workaround for utilities defined in JavaScript though. Those don't seem to work in either normal CSS or in CSS modules.

**Comment by aaronbushnell** [comment] 2024-11-23 16:30
Having similar experiences, too! I wind up making things that *feel* like components a utility to ensure they can be used in `@apply`. Which feels a bit peculiar compared to the pre-v4 behavior.

**Comment by msfragala** [comment] 2024-11-23 16:36
Like switching `addComponents` to `addUtilities` in your config file? When I tested that, it resulted in the same compile error

**Comment by msfragala** [comment] 2024-11-23 20:02
@RobinMalfait This issue isn't actually solved. 😅 I'd read through the v4 docs, just forgot to add that line copying things over to the repro sandbox. The error still happens when trying to use a utility defined in a JS config inside CSS Modules. I've fixed the [second Codesandbox](https://codesandbox.io/p/devbox/8yrwt5) to demonstrate

<img src="https://github.com/user-attachments/assets/b63ef60e-3849-4cb1-ad3d-36e25e8bc0c2" width="600">

**Comment by mryechkin** [comment] 2024-11-25 02:31
I'm running into this issue as well, but for custom classes defined in the `base` layer.

Something like this doesn't work anymore:

```css
@layer base {
  .foo {
    /* ... */
  }
  
  .bar {
    @apply foo;
  }
}
```

To make this work I have to define `foo` as a utility:

```css
@utility foo {
  /* ... */
}

@layer base {
  .bar {
    @apply foo;
  }
}
```

**Comment by RobinMalfait** [comment] 2024-11-25 09:45
@mryechkin only custom utilities defined via `@utility` can be used and are turned into utilities. So the second example you shared is how you have to do it in v4 👍

**Comment by philipp-spiess** [comment] 2024-11-25 09:53
@msfragala Heya! Your example doesn't work because the `page.module.css` file does not import the config properly. In Tailwind v4 there is no concept of a global config, instead each Tailwind CSS file will need to import the theme. We do have an API to avoid generating the Theme CSS variables though, so if you add this to your `page.module.css`, it will work as expected:


```css
@import "tailwindcss/theme" theme(reference);
@config "../tailwind.config.ts";

.test {
  @apply test-component;
}

```

Here's the repro: https://codesandbox.io/p/devbox/8yrwt5

Going to close this one as it's not a bug in Tailwind v4 right now but please feel free to reach out again if you find any issues.

**Closed by philipp-spiess** 2024-11-25 09:53 UTC

**Comment by msfragala** [comment] 2024-11-25 11:47
This behavior makes it difficult to migrate codebases that previously had ample use of CSS modules before using Tailwind — we used `@apply` in these files to still share Tailwind utilities without having to migrate 4 years of legacy code.

If v4 is going to break code that current works, I recommend at this calling it out more explicitly in [this section](https://tailwindcss.com/docs/v4-beta#using-apply-in-vue-svelte). Only Vue and Svelte are named, but there's no mention of the same behavior in CSS Modules in React and other frameworks using them

**Comment by typical-developer** [comment] 2025-09-30 13:21
Has this issue been properly solved?
I'm very new to tailwind and I'm just learning about custom utility classes but every tutorial I've worked with is outdated and the docs don't seem to be updated or I am missing somthing

#### My code (It doesn't work)

```css
@import 'tailwindcss';

.btn {
  @apply py-2 px-4 text-base bg-black text-white transition-normal duration-150 ease-out hover:bg-white hover:text-black font-medium;
}


@utility hide {
  display: none;
}
```

**Comment by typical-developer** [comment] 2025-09-30 15:06
> Has this issue been properly solved? I'm very new to tailwind and I'm just learning about custom utility classes but every tutorial I've worked with is outdated and the docs don't seem to be updated or I am missing somthing
> 
> #### My code (It doesn't work)
> @import 'tailwindcss';
> 
> .btn {
>   @apply py-2 px-4 text-base bg-black text-white transition-normal duration-150 ease-out hover:bg-white hover:text-black font-medium;
> }
> 
> 
> @utility hide {
>   display: none;
> }

Ok problem solved!
This is for whoever needs this in the future 
The issue here was I didn't use `@apply`

For Tailwind V4 this works to create custom utility classes

```css
@import 'tailwindcss';

@utility flex-center {
  @apply flex items-center justify-center gap-2
}
```
