### ISSUE TITLE
Error: EMFILE: too many open files, open error with version 3.3.3

### ISSUE THREAD

**Issue by last-Programmer** [tailwindlabs/tailwindcss#12003] opened 2023-09-14 08:35 UTC
**What version of Tailwind CSS are you using?**

3.3.3

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss: 0.11.0, postcss-cli: 10.1.0

**What version of Node.js are you using?**

18.4.0

**What browser are you using?**

Chrome, Edge, FireFox

**What operating system are you using?**

Windows

**Reproduction URL**

Sorry unable to provide the reproduction url since our project is private. The error is not happening with tailwind version 3.3.2

**Describe your issue**

We have upgraded our project to tailwind 3.3.3 and we started getting this error

[Error: EMFILE: too many open files, open 
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',

The error is not happening with version 3.3.2

Thanks in advance for the help.

**Comment by RobinMalfait** [comment] 2023-09-14 10:58
Hey!

I have to close this as a reproduction was not provided. We also don't need access to a full private repo, but prefer small isolated reproductions where the issue is present. Trying to create a reproduction ourselves from the information in an issue drastically increases the amount of time it takes for us to provide a solution and if we have do that for every issue it’s impossible for us to keep up.

One thing you could check is if your `content` configuration contains a _lot_ of files (e.g.: when you include node_modules or other large folders). If so, make sure they are not included in the content array.

Sorry, not trying to be dismissive and definitely want to fix the issue if there is one, but we have to be strict about this one or there's no way we could keep up with the number of questions we get and the quality of the library would suffer as a result. Hope that's understandable!

**Closed by RobinMalfait** 2023-09-14 10:58 UTC
