### ISSUE TITLE
`dark` modifier in HTML can cause circular dependency issue

### ISSUE THREAD

**Issue by simonhmadsen** [tailwindlabs/tailwindcss#7980] opened 2022-03-29 06:37 UTC
**What version of Tailwind CSS are you using?**

v.3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.4.7

**What version of Node.js are you using?**

v14.18.0

**What browser are you using?**

Chrome (Version 99.0.4844.83 (Official Build) (x86_64))

**What operating system are you using?**

macOS Big Sur (11.6.5)

**Reproduction URL**

[Tailwind Play](https://play.tailwindcss.com/TmkNE8kwNr)

**Describe your issue**

**Current behavior**

_This issue applies to projects using the `class` darkMode strategy._

When using the `dark` modifier on an custom utility on a HTML element, and that custom utility also contains a `dark` modifier, you get the following error message:

```bash
<css input>: You cannot `@apply` the `dark:bg-green-700` utility here because it creates a circular dependency.
```

Example:

Custom utility:
```css
.a {
    dark:text-sm
}
```

HTML
```
<div class="dark:a">Error</div>
```

This only applies to the `dark` modifier.

**Expected behavior**

1. This shouldn't produce an error - it should behave like other modifiers and avoid creating a circular dependency
2. The error message should point at the usage of the custom utility rather that the implementation of the utility itself. Most likely the problem isn't with the utility but with the usage.

**Comment by adamwathan** [comment] 2022-03-29 13:16
Will have to dig in to this one to really understand the expected behavior because I think there's a chance this really is a circular dependency, but I have to ask first what output you actually expect in this case?

Given this input for example:

```css
.example {
  @apply bg-white dark:bg-black;
}
```

...this is the generated output:

```css
.example {
  background-color: #fff;
}
.dark .example {
  background-color: #000;
}
```

So what CSS should `dark:example` be generating? In my mind, the "correct" output based on how `@apply` is intended to work is this:

```css
.dark .dark\:example {
  background-color: #fff;
}
.dark .dark .dark\:example {
  background-color: #000;
}
```

...but that just kinda seems like nonsense. You can see why it might trigger a circular dependency though, by trying to stack dark on top of dark.

**Comment by simonhmadsen** [comment] 2022-03-29 19:01
Well i think that depends on the direction you want to go - one way would be to merge all declarations of the dark:modifier as it (probably) never makes sense to have duplicate identifiers.

I haven't looked into the implementation, so i don't know how large of a task that would be, or if it is even possible.

Another way of going about this would just be to change the error message. The error suggests changing the utility - i would believe it to be more logical to change the use of the utility. So instead of indicating that the `@apply` function creates a circular dependency, maybe indicate that the use of the custom utility in the HTML creates a circular dependency.

I just tried out what the generated code looks like if you use a different modifier, and it actually isn't much better:
```css
.test {
    @apply focus:bg-black;
}
```

output:
```css
.focus\:test:focus:focus {
  background-color: #000;
}
```

Maybe it would make sense to look into merging duplicate modifiers?

**Comment by Farr69** [comment] 2022-05-03 05:25
I see that your decorator doesn't actually modify the constructor, it merely runs some side-effect code to add some metadata entry. Thus the @decorator syntax isn't a must.

**Comment by dfallman** [comment] 2022-05-30 23:57
I've seen this too lately. I'm pretty sure it was the same problem, i.e. where I had something this defined:

```
.text-subtle {
   @apply text-gray-400 dark:text-gray-600;
}
```

...that was used like this: `<div class="dark:text-subtle"...` by someone somewhere in the code base.

From the error message though it sounds like this is a mistake in the configuration file or in main.css where in fact the problem is in code base. It took me a while to figure out what was going on. So I concur with the last reply, that there seems to be two separate issues here. The first is if this really is a circular dependency? 

But to me, the more pressing issue is to change the error message to a warning that points the user in the right direction, i.e. that the problem is how a custom class is used in thre code where it creates a circular dependency. Right now the error message doesn't make any sense.

**Comment by Alfred854** [comment] 2022-06-20 10:10
Thank you so much for the solution Paul.

**Comment by Holthaus789** [comment] 2022-07-27 10:22
It there already an Solution to this problem? I have the same problem.

**Comment by Rodney65856** [comment] 2022-08-04 07:45
Thank you for helping people get the information they need. Great stuff as usual. Keep up the great work!!!

**Comment by Rodney65856** [comment] 2022-08-05 04:25
Glad you like it. We have been using this for several weeks now and it seems to be going nicely.
[GoMedicare](https://www.gomedicare.care/)

**Comment by adamwathan** [comment] 2022-08-20 13:42
Going to close this as a "won't fix" — to me it just doesn't make sense to be trying to add a `dark` modifier to a class that is already applying the `dark` modifier internally. Agree in a perfect world we'd come up with a way to detect exactly what the source of the problem is and provide a more instructive error, would happily look at a PR that tried to do that, but just don't have any plans to invest time in that myself.

Doing something like this is just not the intended usage of the framework at all:

```css
.text-subtle {
   @apply text-gray-400 dark:text-gray-600;
}
```

```html
<div class="dark:text-subtle"...
```

...so I just can't justify spending my time on it when it's not a problem you should run into when using the framework as intended. I think this type of usage is going to throw an error in v4 with some of the more strict `@apply` behavior we are working on: 

https://github.com/tailwindlabs/tailwindcss/blob/ffef5e2c44252282cc7230287cfb402679f3fd8d/tests/apply.test.js#L1811-L1966

**Closed by adamwathan** 2022-08-20 13:42 UTC

**Comment by gabrielboeker** [comment] 2022-09-13 19:09
I am running in the same error as well but I can't really follow your explaination @adamwathan. While it is true, that the rules of the framework have to be followed in order to get it to work correctly, users always find a way to modify things for themselves.

For me it was pretty intuitively to create custom classes that do have the appropriate dark mode as well. 

```
  .text-primary{
    @apply text-neutral-800 dark:text-neutral-50;
  }
```
feels right to me. I understand the way tailwind is handling this but how would you recommend implementing regarding custom classes? That issue breaks the whole `apply` method for me since I now have to rewrite everything like 

```
  .text-primary{
    @apply text-neutral-800;
  }

.dark-text-primary{
    @apply text-neutral-50;
  }
```
```
<div class="text-primary dark:dark-textprimary"></div>
```
which is anything but convenient. 

PLUS:
The initial issue does NOT occur for me when removing the manual dark mode class config from `tailwind.config.js` (`darkMode: 'class',`).

**Comment by dfallman** [comment] 2022-09-13 22:28
> .text-primary{
>     @apply text-neutral-800 dark:text-neutral-50;
>   }

Hi @gabrielboeker, this is the strategy we're using as well and is working great for us. I'm actually not sure why this would not be the "intended use" of the framework (?) That seems strange, as this strategy reduces HTML markup clutter significantly! For instance, in our case we use:

```
<div class="btn-normal">Some text</div>
```

Where btn-normal is defined as:

```
@apply px-2 py-1 rounded cursor-pointer bg-white dark:bg-gray-900 border-gray-300 dark:border-gray-700 text-gray-500 dark:text-gray-600 focus:[etc...];
```

...and even if this makes use of Tailwind a little more like using traditional CSS there's no getting around that this saves an _unbelievable_ amount of markup in the code base, plus that you only have to change it in one place and it changes everywhere, and if you need a one-off special case you can always override something in `btn-normal`` such as:

```
...class="!bg-yellow-200 dark:!btn-bg-yellow-800/50"
```

In practice you don't need the `!` here if you put the new color before the 

The problem reported above is actually NOT a problem with using Tailwind this way @adamwathan. It is when you erroneously try to use `btn-normal` (in this case) with `dark:btn-normal`. 

This then creates a circular dependency as you can't apply dark: to dark:, as in `dark:dark:bg-gray-900`. Fair enough. But that's not to say the strategy itself is necessarily wrong.

As I wrote earlier in this thread, I believe the postprocessor should give a different error message or at least warn the user about the possibility of using `dark:dark:` somewhere and, if possible, what file/row that error occured.

**Comment by gabrielboeker** [comment] 2022-09-14 06:40
Hey @dfallman thanks for your reply. 
since i was already using that strategy before, it was fairly odd to me that it did not work until i found the issue. 

the problem indeed occurs when you (in my case accidentally) assign the dark modifier on a custom class. Somewhere in my code i had a `dark:text-primary` 😅

I can imagine that more people will do this mistake so I consider that as the solution. Thanks!
