### ISSUE TITLE
Why does Utilities add so much memory to the bundle output?

### ISSUE THREAD

**Issue by y04nqt** [tailwindlabs/tailwindcss#8760] opened 2022-07-01 20:16 UTC
**What version of Tailwind CSS are you using?**

 v3.0.23

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss-cli 8.4.12,  webpack 5.72.0, @nrwl/web 14.3.5

**What version of Node.js are you using?**

 v16.8.0

**What browser are you using?**

Chrome, Safari, but doesn't matter

**What operating system are you using?**

macOS

**Reproduction IMG**
![Screen Shot 2022-07-01 at 11 07 14 AM](https://user-images.githubusercontent.com/10656995/176960010-6ffd3b0e-38d8-454a-947c-6008e5e31075.png)
![Screen Shot 2022-07-01 at 11 07 30 AM](https://user-images.githubusercontent.com/10656995/176960011-85b158b5-16ee-4e38-ac38-fa3c4e80c3c4.png)

**Describe your issue**

When I remove utilities from my tailwind import, my bundle loses quite a bit of weight. The only thing I can tell I really need utilities for is the one animate-bounce call I'm using. If I remove utilities then the bounce animation fails to happen. I'm wondering why the utilities import is so large in size. I only import it once, then the other CSS files have tailwind classes using @apply. Either, utilities need to be this size or it is over importing. Because the one animate-bounce animation shouldn't require that amount of code, but I could see if other class variations could be an issue.

**Comment by adamwathan** [comment] 2022-07-01 20:18
Hey! Sorry I'm going to have to ask you to open a new issue and include an actual reproduction (a repository we can clone to actually take a look at), can't really help from a screenshot. Tailwind shouldn't be impacting the size of your JS bundle at all so need a project to play with.

Going to close this since as we mention in the issue template a reproduction is required, but please do submit a new issue with a proper reproduction and we can take a look.

**Closed by adamwathan** 2022-07-01 20:18 UTC
