### ISSUE TITLE
tailwindcss/plugin doesn't support ES6 import

### ISSUE THREAD

**Issue by andrecasal** [tailwindlabs/tailwindcss#13294] opened 2024-03-20 22:15 UTC
TailwindCSS v3.4.1, Node v20.11.0, macOS

Reproduction URL: https://play.tailwindcss.com/h8NaZER00q?file=config
Same as this 👇:
```ts
import { type Config } from 'tailwindcss'
import plugin from 'tailwindcss/plugin'

export default {
	content: ['./app/**/*.{ts,tsx,jsx,js}'],
	darkMode: 'class',
	plugins: [
		plugin(function ({ addUtilities, addComponents, e, config }) {
			// Add your custom styles here
		}),
	],
} satisfies Config
```

Issue:
TS complains about `import plugin from 'tailwindcss/plugin'` with `Cannot find module 'tailwindcss/plugin' or its corresponding type declarations.`.

**Comment by RobinMalfait** [comment] 2024-03-21 13:23
Hey!

Can you share a minimal reproduction repo that showcases this issue? My gut says that this is related to how your project is setup and potentially how your `tsconfig.json` looks.

I can't seem to introduce this in a `tailwind.config.ts` file:

<img width="765" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/1834413/8c42cbe0-563c-43f1-9577-33f3d7b7738f">

**Comment by andrecasal** [comment] 2024-03-22 14:19
Here's my tsconfig.json:

```json
{
	"include": [
		"**/*.ts",
		"**/*.tsx"
	],
	"compilerOptions": {
		"lib": [
			"DOM",
			"DOM.Iterable",
			"ES2022"
		],
		"isolatedModules": true,
		"esModuleInterop": true,
		"jsx": "react-jsx",
		"module": "nodenext",
		"moduleResolution": "nodenext",
		"resolveJsonModule": true,
		"target": "ES2022",
		"strict": true,
		"noImplicitAny": true,
		"allowJs": true,
		"forceConsistentCasingInFileNames": true,
		"paths": {
			"#*": [
				"./*"
			],
			"@/icon-name": [
				"./app/old_components/ui/icons/name.d.ts",
				"./types/icon-name.d.ts"
			]
		},
		"skipLibCheck": true,
		"allowImportingTsExtensions": true,
		"noEmit": true
	}
}

```

**Comment by RobinMalfait** [comment] 2024-03-23 01:25
Nothing obvious jumps out, and I can't reproduce it either. Can you share an actual minimal repo that has the issue so that we can take a look?

<img width="1549" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/1834413/28717f78-ea34-48bf-9f4f-c39eec5efd1f">

**Comment by RobinMalfait** [comment] 2024-03-26 14:32
Hey!

Going to close this issue for now, but if you are still running into this, feel free to open a new issue with a minimal reproduction repo attached that contains the full setup required to reproduce this issue.

Would love to figure out what's going on but need a bit more info unfortunately.

**Closed by RobinMalfait** 2024-03-26 14:32 UTC
Labels: needs reproduction
