### ISSUE TITLE
Tailwind config changes don't get detected when using `plugin.withOptions`

### ISSUE THREAD

**Issue by benjamindavid** [tailwindlabs/tailwindcss#2436] opened 2020-09-23 10:22 UTC
### Describe the problem:

I'm having an issue where changes don't get detected when I'm making changes to the plugin function part of some plugin in my tailwind config.

I've tracked it down to the point where using `plugin.withOptions` seems to be the problem.

Is there a way to make Tailwind/webpack detect changes made to the plugin function when using `plugin.withOptions`?

### Link to a minimal reproduction:

When using `plugin.withOptions`, only changes made to the config function get detected:

    //tailwind.config.js
    const plugin = require('tailwindcss/plugin')
    module.exports = {
        plugins: [
            plugin.withOptions(
                function() {
                    return function(pluginApi) {
                        const {addBase} = pluginApi
                        addBase({
                            'body': {
                                backgroundColor: 'green' // Changes made here are not detected
                            },
                        })
                    }
                },
                function() {
                    return {
                        theme: {
                            colors: {
                                blue: {
                                    '500': 'blue', // Changes made here are detected
                                },
                            }
                        }
                    }
                }
            )
        ],
    }

When using `plugin` without options, changes made to the plugin and config function get detected:

    //tailwind.config.js
    const plugin = require('tailwindcss/plugin')
    module.exports = {
        plugins: [
            plugin(
                function(pluginApi) {
                    const {addBase} = pluginApi

                    addBase({
                        'body': {
                            backgroundColor: 'green' // Changes made here are detected
                        },
                    })
                },
                function() {
                    return {
                        theme: {
                            colors: {
                                blue: {
                                    '500': 'blue', // Changes made here are detected
                                },
                            }
                        }
                    }
                }
            )
        ],
    }

**Comment by adamwathan** [comment] 2020-10-09 11:59
Hey! Can you create a simple project that reproduces the issue? We got a lot of issues that require me to manually recreate someone's project from scratch and I unfortunately just don't have time for that so things end up going unfixed. If you can provide something I can clone and start troubleshooting with right away it's much easier for me to find time to diagnose and fix the issue.

**Comment by adamwathan** [comment] 2020-10-17 16:18
Have reproduced this, the issue is that the `object-hash` library we use to detect changes doesn't seem to product a different hash when things change using that signature. I don't have time to fix this right this second so just leaving some notes for future Adam...

Likely we need to make the comparison more sophisticated, where we check if the hash is the same, but even if it is the same we may need to do some extra comparisons of specific sections of the config. I'm guessing we may need to iterate over the plugins array and see if each entry `===` the previous value. Might still not work because maybe that will always be false. We may need to do some stupid crap like store a version/hash inside the actual plugin object so we have some identifier to compare.

**Comment by adamwathan** [comment] 2020-10-17 16:58
Fixed in v1.9.4 👍 

https://github.com/tailwindlabs/tailwindcss/commit/d3717279f9d25d2d02114156987d9b91ff4aa0e6

**Closed by adamwathan** 2020-10-17 16:58 UTC
Labels: needs reproduction
