### ISSUE TITLE
Tailwind CLI fails with "Cannot find module postcss" since v3.0.11

### ISSUE THREAD

**Issue by jmotes** [tailwindlabs/tailwindcss#7008] opened 2022-01-11 04:57 UTC
**What version of Tailwind CSS are you using?**

v3.0.11/12

**What build tool (or framework if it abstracts the build tool) are you using?**

Only using the CLI

**What version of Node.js are you using?**

v14.18.1 (we're matching what Vercel runs in production)

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS (Monterey)

**Describe your issue**

Run the CLI command:

> npx tailwindcss@3.0.12

This is the result:
```
npx: installed 85 in 5.148s
Cannot find module 'postcss'
Require stack:
- /Users/USERNAME/.npm/_npx/35470/lib/node_modules/tailwindcss/lib/lib/generateRules.js
- /Users/USERNAME/.npm/_npx/35470/lib/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js
- /Users/USERNAME/.npm/_npx/35470/lib/node_modules/tailwindcss/lib/processTailwindFeatures.js
- /Users/USERNAME/.npm/_npx/35470/lib/node_modules/tailwindcss/lib/cli.js
```
Installing postcss globally or locally does not help.

**Comment by jmotes** [comment] 2022-01-11 05:25
Nevermind, this turned out to be an issue with my NODE_PATH. 

It somehow got cleared out...Not sure what's different about the last two versions that would cause them to not work for me, but nevertheless 3.0.12 is fine now that I've explicitly defined it in my .zshrc.

If anyone else runs into this, see:

https://stackoverflow.com/questions/27876557/node-js-configuring-node-path-with-nvm

**Comment by stivaugoin** [comment] 2022-02-01 00:09
I have the same problem but no issue with my NODE_PATH 🤔. I try anything from the answers on stackoverflow. 

I don't have any issue on other projects using v3.0.7.

**Comment by jmotes** [comment] 2022-02-01 00:37
@stivaugoin I'll re-open my ticket for you then!

**Comment by benyrfg** [comment] 2022-02-03 22:26
Same issue, Tailwind v3.0.18, Node v14.16.1, Windows 10

**Comment by ArnaudLigny** [comment] 2022-02-06 01:11
Same here with Tailwind 3.0.18 + Node 12.16.3:
```bash
Cannot find module 'postcss'
Require stack:
- /opt/build/repo/node_modules/tailwindcss/lib/lib/generateRules.js
- /opt/build/repo/node_modules/tailwindcss/lib/lib/expandTailwindAtRules.js
- /opt/build/repo/node_modules/tailwindcss/lib/processTailwindFeatures.js
- /opt/build/repo/node_modules/tailwindcss/lib/cli.js
```

**Comment by mattrossman** [comment] 2022-02-09 04:44
Taking a look at the diff: https://github.com/tailwindlabs/tailwindcss/compare/v3.0.10...v3.0.11

There's not very many changes, the only thing that jumps out at me is the major version upgrade to `postcss-js`

**Comment by keckelt** [comment] 2022-02-10 16:44
same issue as https://github.com/tailwindlabs/tailwindcss/issues/6916

**Comment by thecrypticace** [comment] 2022-02-10 20:02
Can someone provide a repo that we can clone to reproduce this issue?

**Comment by mattrossman** [comment] 2022-02-10 20:23
@thecrypticace Your steps work for me as well. Perhaps the "on-the-fly" version of npx behaves differently than executing npx with tailwindcss as a local dependency.

Here is a repro: https://github.com/mattrossman/tailwind-postcss-dep

**Comment by thecrypticace** [comment] 2022-02-10 20:31
I can totally reproduce with that repo but NPM installs peer deps by default now. It seems strange to me that the on-the-fly version works for you while a manually set up version does not.

What version of NPM are you using?

**Comment by mattrossman** [comment] 2022-02-10 20:35
I have npm 7.19.1 and yarn 1.22.15 (same issue with both)

**Comment by thecrypticace** [comment] 2022-02-10 20:37
I think npm v7 is also supposed to install peer deps unless you have it configured to be turned off. I'm running npm v8 but only recently upgraded. Yarn would indeed have this issue.

The culprit here is the `postcss-js` upgrade because it previously had postcss listed in its own dependencies. It moved these to `peerDependencies` per the postcss plugin guidelines (https://github.com/postcss/postcss/blob/main/docs/guidelines/plugin.md#14-keep-postcss-to-peerdependencies). It wasn't supposed to have been included. My recommendation is that we upgrade the CLI guide but I'll start the discussion internally to see what steps we need to take. Thanks!

**Comment by thecrypticace** [comment] 2022-02-11 15:48
Alright, we pushed out v3.0.22 with a temporary fix for this while we come up with a better solution. All the guides and stuff should be working again. Thanks for the report and sorry for all the trouble!

**Closed by thecrypticace** 2022-02-11 15:48 UTC

**Comment by harvanchik** [comment] 2022-02-18 01:29
I am getting this issue on v3.0.23.
