### ISSUE TITLE
Installation into Laravel 8 following documentation fails at `npx tailwindcss` stage

### ISSUE THREAD

**Issue by adamhopkinson** [tailwindlabs/tailwindcss#2936] opened 2020-11-28 18:36 UTC
### Describe the problem:

Installing using the Laravel-specific installation guide fails when creating tailwind.config.js file with error `Cannot find module 'autoprefixer'`.

### Minimal reproduction:

```
> laravel new twtest

> cd twtest

> npm install

> npm install -D tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9

> npx tailwindcss init
npx: installed 84 in 5.511s
Cannot find module 'autoprefixer'
Require stack:
- /Users/adam/.npm/_npx/16279/lib/node_modules/tailwindcss/lib/cli/commands/build.js
- /Users/adam/.npm/_npx/16279/lib/node_modules/tailwindcss/lib/cli/commands/index.js
- /Users/adam/.npm/_npx/16279/lib/node_modules/tailwindcss/lib/cli/main.js
- /Users/adam/.npm/_npx/16279/lib/node_modules/tailwindcss/lib/cli.js
```

### Versions:
```
> npm -v
6.14.8
> php artisan -V
Laravel Framework 8.16.1
> cat package.json
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "autoprefixer": "^9.8.6",
        "axios": "^0.19",
        "cross-env": "^7.0",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.19",
        "postcss": "^7.0.35",
        "resolve-url-loader": "^3.1.0",
        "tailwindcss": "npm:@tailwindcss/postcss7-compat@^2.0.1"
    }
}
```

**Comment by DasdWaller** [comment] 2020-11-29 03:32
I install breeze witch include tailwind 2 and installed successfully. Check the [commit](https://github.com/laravel/breeze/commit/35f5e8697e417bcecfec1cb359f2cf32a253f5d0) of breeze.

**Comment by adamhopkinson** [comment] 2020-11-29 13:27
@DasdWaller the `package.json` in that commit shows the same packages & versions as my `package.json` above. The only other relevant file I see in the commit is `webpack.mix.js` - which comes in after the `npx tailwindcss init` stage at which my minimal reproduction above is failing.

**Comment by DasdWaller** [comment] 2020-11-29 14:28
@adamhopkinson sorry I was so sleepy last night. I don't read correctly.
The problem is tailwindcss cant create the config file. I run `npx tailwindcss init` and I have the same error.
Sorry @adamwathan but you can help here.

**Comment by ivaneliasoo** [comment] 2020-11-29 23:08
I'm experiencing this issue with vuevite and nuxtjs

**Comment by rmahmood19** [comment] 2020-11-29 23:30
I had the same issue. But updating to node 15 , then running `npm install` allowed me to run the `npx tailwindcss init` command without any problem and created the tailwind.config.js file .

**Comment by ivaneliasoo** [comment] 2020-11-30 00:38
thanks @rmahmood19 that solved the issue for me

**Comment by adamhopkinson** [comment] 2020-11-30 10:21
@rmahmood19 that also worked for me, thank you.

This does feel a bit wrong, though - the latest version of node is v14.15.1 (according to `n stable`).

** Instructions for upgrading node **

1. Install n, node's version manager: `npm install -g n`
2. Install the latest version of node: `n latest`

**Comment by jiaming10** [comment] 2020-12-04 01:48
If you don't want to upgrade NodeJS/NPM, you may try running `npx tailwindcss-cli@latest init -p`.

**Comment by RobinMalfait** [comment] 2020-12-07 13:08
Hey! Thank you for your issue!
Much appreciated! 🙏

Glad it all worked out!
Going to close this issue for now, if you have other issues, feel free to open a new one!

**Closed by RobinMalfait** 2020-12-07 13:08 UTC
