### ISSUE TITLE
Tailwind V3: `@apply ring...` does not work anymore

### ISSUE THREAD

**Issue by madebyfabian** [tailwindlabs/tailwindcss#6391] opened 2021-12-11 09:47 UTC
**What version of Tailwind CSS are you using?**

For example: v3.0.1

**What build tool (or framework if it abstracts the build tool) are you using?**

vite.js 2, vue 3

```json
"@tailwindcss/line-clamp": "^0.3.0",
"@types/tailwindcss": "^2.2.4",
"@vitejs/plugin-vue": "^1.6.0",
"autoprefixer": "^10.4.0",
"postcss-nested-ancestors": "^2.0.0",
"tailwindcss": "^3.0.1",
"vite": "^2.5.3",
```

**What version of Node.js are you using?**

v15.8.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Reproduction URL**

Can't be reproduced in Tailwind Play, since it works there. https://play.tailwindcss.com/Ft82oCeXrQ?file=css 

**Describe your issue**

The issue is that all the ring-* utilities don't work anymore in Tailwind v3, when using `@apply` inside a Vue.js SFC. My code:
`
.classname {
  @apply ring ring-offset-2 ring-green-700 ring-offset-gray-800;
}
`
In Tailwind v2, this showed me the ring. In v3, this shows nothing. It's similar to the issue https://github.com/tailwindlabs/tailwindcss/issues/6342 This is how the output looks in v2:
<img width="631" alt="Bildschirmfoto 2021-12-11 um 10 43 22" src="https://user-images.githubusercontent.com/32813692/145672045-b8dad50c-5de3-46e6-b0d3-41d6c275e11e.png">
with computed looking like this:
<img width="1013" alt="Bildschirmfoto 2021-12-11 um 10 46 03" src="https://user-images.githubusercontent.com/32813692/145672100-025e953f-a328-4d20-bba7-73e4779695cb.png">

**In v3 however, it looks like this:**
<img width="631" alt="Bildschirmfoto 2021-12-11 um 10 44 15" src="https://user-images.githubusercontent.com/32813692/145672067-8d55c1e9-3da0-4cc9-a6cb-702ac05d6aca.png">
with computed looking like this:
<img width="1013" alt="Bildschirmfoto 2021-12-11 um 10 46 37" src="https://user-images.githubusercontent.com/32813692/145672112-42b5d33f-3c16-443d-83ca-88c2f571b974.png">

so similar to issue https://github.com/tailwindlabs/tailwindcss/issues/6342, it never gets applied actually, though not visible.

**Comment by RobinMalfait** [comment] 2021-12-11 10:55
Hey! Thank you for your bug report!
Much appreciated! 🙏

It's hard to tell without looking at actual source code, can you create a minimal reproduction repo and share it?

In the meantime, my guess is that you don't have `@tailwind base;`, you should make sure that exists. Upgrade guide: https://tailwindcss.com/docs/upgrade-guide#base-layer-must-be-present

**Comment by madebyfabian** [comment] 2021-12-11 11:03
@RobinMalfait Hey, thanks so much for the quick response! I was really happy to see Tailwind v3 being released and I was going through the upgrade guide very accurately. My CSS starts with

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
...
```

I will be sure to create a reproduction repo as soon as possible and will add it to here.

**Comment by agusterodin** [comment] 2021-12-11 22:08
Same issue here. Broke after 3.0alpha-1

**Comment by talkenson** [comment] 2021-12-12 08:55
Same issue. Can reproduce on 3.0.1. 
Simply applying these rules breaks all the ring.
![image](https://user-images.githubusercontent.com/24260024/145706161-ba0b3a5f-6167-483c-9102-eacf788d4e70.png)

**IMPORTANT!!!**
In previous case shadow won't be applied
So, to add shadows I need to delete all ring-* rules

![image](https://user-images.githubusercontent.com/24260024/145706218-3f339fb4-4b7d-4acb-a977-59a3facb1a6d.png)
![image](https://user-images.githubusercontent.com/24260024/145706240-da6f7c02-ca78-40a7-afcb-dee9e06966f9.png)

**Comment by stevelacey** [comment] 2021-12-12 09:28
I am also seeing ring issues that I'm yet to fully understand, what seems to be happening is that nothing works unless you also make the ring inset and supply offset classes, this works, and looks the same as what I had before, except the ring is inset:

```
ring-2 ring-white ring-inset ring-offset-0 ring-offset-white
```

As far as I can tell from the css generated, it seems that if any one of the css variables is undefined, the `box-shadow` rule is kaput.

**Comment by adamwathan** [comment] 2021-12-13 21:08
Hey folks! We've patched a fix for this in v3.0.2 👍  It involved disabling this new `optimizeUniversalDefaults` feature which is a meaningful performance boost in the browser on huge pages with _lots_ of HTML, so that sucks, but we almost have a fix in place that will allow us to re-enable it for v3.0.3.

Ultimately this is the same as this issue: https://github.com/tailwindlabs/tailwindcss/issues/6409

**Closed by adamwathan** 2021-12-13 21:08 UTC

**Comment by madebyfabian** [comment] 2021-12-13 21:10
@adamwathan awesome, thank you all so much!

**Comment by stevelacey** [comment] 2021-12-15 02:21
@adamwathan worked perfect, thank you! 🙏🏼

**Comment by pthompson** [comment] 2022-06-01 23:48
I'm having the same issue. Ring does not work in prod with Tailwind 3.0.24. Downgrading to 3.0.10 does not help.

**Comment by ShawnFarsai** [comment] 2023-03-08 22:03
Hey @adamwathan ,

I'm guessing things have changed since 2021.

I'm running into an issue where using the `border` utility class on it's own doesn't work and `border-solid` needs to be applied. Conclusion is `border-style: solid` for the preflight is not getting applied- even though the rest of preflight works.

Additionally, `ring` utility classes outright don't work.

I saw you mention disabling `optimizeUniversalDefaults` in 2021. For the heck of it i tried setting it to `true` in my `tailwind.config` and that fixed our problem. But I have no idea why... hahaha
