### ISSUE TITLE
TailwindCSS does not update styles on Hot Reload (React + JIT mode)

### ISSUE THREAD

**Issue by dospolov** [tailwindlabs/tailwindcss#4940] opened 2021-07-09 21:48 UTC
### What version of Tailwind CSS are you using?

2.2.4

### What build tool (or framework if it abstracts the build tool) are you using?

React 17.0.2

### What version of Node.js are you using?

14.16.1

### What browser are you using?

Chrome Stable latest

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/dospolov/tailwind-jit-issue-repo

### Describe your issue

After the latest updates, JIT is not applying styles. Previously it worked fine.
A whole dynamic CSS file is not reacting on CLASS/CLASSNAME attribute changing.

**Comment by dospolov** [comment] 2021-07-09 21:57
@adamwathan btw, everything works fine on 2.2.2

**Comment by dospolov** [comment] 2021-07-09 22:06
unfortunately, after some time (8-10 minutes), it stops working on 2.2.2 as well

**Comment by octokatherine** [comment] 2021-07-11 05:27
I'm having the same issue on 2.2.4

**Comment by adamwathan** [comment] 2021-07-11 14:26
Hey! This is because you are using create-react-app/react-scripts and they use very outdated versions of many dependencies. The problem in this case is postcss-loader, which need to be on the latest version to be compatible with the new dependency tracking system in Tailwind CSS v2.2. This wouldn't have worked in v2.2.2, maybe you were on v2.1 before which used a different dependency tracking system?

You can see here where the old version of postcss-loader is being pulled in:

https://github.com/dospolov/tailwind-jit-issue-repo/blob/main/yarn.lock#L8569

Check our troubleshooting documentation for more information:

https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files

Your options for resolving it are:

1. Use the `TAILWIND_MODE=watch` environment variable to switch back to the old dependency tracking system, but this will eventually go away.
2. Eject so you can specify the dependency versions yourself instead of having to use what CRA wants you to use.
3. Switch to a tool like [Vite](https://vitejs.dev) which does everything CRA does but is more actively maintained.

@octokatherine based on your messages on Twitter I believe you are using Next.js right? If so then this won't be the same issue — if you can open a new issue with a reproduction we should be able to figure it out! We use Next every day for our work (tailwindcss.com is built with Next for example) and haven't hit this issue yet ourselves so it's going to be hard to solve without a reproduction.

**Comment by ahmedosama7450** [comment] 2021-07-11 18:31
@adamwathan I experienced this issue with nextjs a week ago. I tried removing `node_modules` and reinstalling but It didn't work.
I ended up creating a new nextjs project and moving everything there, It's been a week and It works fine.

Maybe the problem is related to caching or something like that, Idk

**Comment by octokatherine** [comment] 2021-07-11 23:27
Thanks @adamwathan, it started working for me again after restarting the server (I had tried that before... don't really know what caused the issue still.) If it comes up again, I'll create a repro repo

**Comment by dospolov** [comment] 2021-07-12 08:23
@adamwathan what about specifying `resolutions` in `package.json` for postcss-loader?

**Comment by productfrontenddeveloper** [comment] 2021-07-13 02:58
some problem nuxt-vue -> https://github.com/nuxt-community/tailwindcss-module/issues/357

**Comment by phifa** [comment] 2021-07-13 06:52
same here with new nextjs 10 set up. restarting server helps

**Comment by adamwathan** [comment] 2021-07-13 10:35
@phifa Make sure you are on the newest version of everything, for example use Next 11 not 10.

Going to close this since the solution was provided for the original question and the other issues here are not the same. Can anyone having a problem please open a new issue and most importantly include a reproduction? Thanks.

**Closed by adamwathan** 2021-07-13 10:35 UTC
