### ISSUE TITLE
Including `presets: []` in `tailwind.config.js` causes build to fail

### ISSUE THREAD

**Issue by nothinghalosix** [tailwindlabs/tailwindcss#5054] opened 2021-07-23 10:20 UTC
### What version of Tailwind CSS are you using?

2.1.2

### What build tool (or framework if it abstracts the build tool) are you using?

node

### What version of Node.js are you using?

14.16.0

### What browser are you using?

Firefox

### What operating system are you using?

macOS 11.5

### Reproduction repository

https://gitlab.com/nothinghalosix/wordpress-tailwindcss-2

### Describe your issue

my build process gives me an error, other projects too

**it is a WP application**
build command -> npx tailwindcss-cli@latest build themes/nothing/css/tailwind.css -o themes/nothing/scss/partials/tailwind-styles.scss -c themes/nothing/tailwind.config.js

**error**
npx: installed 136 in 17.378s
[deprecation] Running tailwindcss without -i, please provide an input file.
(node:74080) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
at Function.entries ()
at matchUtilities (/Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/lib/util/processPlugins.js:131:37)
at /Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/lib/util/createUtilityPlugin.js:30:7
at /Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/lib/util/processPlugins.js:99:5
at Array.forEach ()
at _default (/Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/lib/util/processPlugins.js:93:11)
at /Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/lib/processTailwindFeatures.js:64:54
at LazyResult.runOnRoot (/Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/peers/index.js:61625:16)
at LazyResult.runAsync (/Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/peers/index.js:61677:26)
at LazyResult.async (/Users/edv004/.npm/_npx/74080/lib/node_modules/tailwindcss-cli/node_modules/tailwindcss/peers/index.js:61507:30)
(Use node --trace-warnings ... to show where the warning was created)
(node:74080) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:74080) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

maybe since macOS 11.5 update

**Comment by adamwathan** [comment] 2021-07-23 11:26
Thanks! The issue is the `preset: []` line in your config file, if you remove that it will build successfully 👍🏻 This has come up a few times though so I need to investigate the underlying issue and figure out what's going on, because that _should_ still work. Going to rename this issue and leave it open until we have a chance to look into it.

**Comment by nothinghalosix** [comment] 2021-07-23 20:14
hi Adam, thanks. working fine

**Comment by xzfd1010** [comment] 2021-08-06 10:46
I also encountered this problem. I need to set `preset: []` because the `tailwindcss-intellisense` plugin shows classNames that won't generated in my dist css. You can find more detail in the [discussion](https://github.com/tailwindlabs/tailwindcss/discussions/4871).

**Comment by adamwathan** [comment] 2021-09-10 23:54
This is fixed in the latest release 🥳

**Closed by adamwathan** 2021-09-10 23:54 UTC
