### ISSUE TITLE
Using 2xl:text-5xl seems to override leading-snug

### ISSUE THREAD

**Issue by abdusfauzi** [tailwindlabs/tailwindcss#2852] opened 2020-11-21 06:05 UTC
### Describe the problem:

I used `2xl:text-5xl` and `leading-snug` together, but it seems leading snug unable to override the line-height that came together with font-size. The only way to re-apply the `leading-snug` is by add `2xl:leading-snug`.

### Link to a minimal reproduction:

https://play.tailwindcss.com/H9O6ICSUkQ

**Comment by fedeci** [comment] 2020-11-21 07:59
Duplicate of #2603

**Comment by abdusfauzi** [comment] 2020-11-21 18:06
my bad. thank you @fedeci

**Closed** 2020-11-21 18:05 UTC
