### ISSUE TITLE
Tailwind does not purge keyframes that are unused in the application codebase.

### ISSUE THREAD

**Issue by redsuperbat** [tailwindlabs/tailwindcss#2937] opened 2020-11-28 21:10 UTC
### Describe the problem:

Tailwind does not purge keyframes that are unused in the application codebase.

### Link to a minimal reproduction:

- Create a vue projekt and install tailwindcss.
- Add custom keyframes and animations to tailwind.config.js
- Use animations in code.

Now if you build the project you will see that your keyframes are included in the build css-file as well as all of the base keyframes even though you have not used them in the vue project.

**Comment by adamwathan** [comment] 2020-11-28 21:21
Hey! This is a duplicate of #2847, can find the solution there 👍🏻

**Closed by adamwathan** 2020-11-28 21:21 UTC
