### ISSUE TITLE
Arbitrary values in arrays not picked up

### ISSUE THREAD

**Issue by gukj** [tailwindlabs/tailwindcss#11387] opened 2023-06-07 11:49 UTC
**What version of Tailwind CSS are you using?**

v3.3.2

**What build tool (or framework if it abstracts the build tool) are you using?**

postcss 8.4.24, Next.js 13.4.4, react 18.2.0

**What version of Node.js are you using?**

v20.1.0

**What browser are you using?**

Chrome, Safari, Firefox

**What operating system are you using?**

macOS 13.13.1 (a)

**Reproduction URL**

[Tailwind Play with repro](https://play.tailwindcss.com/UvHltQ4mfE). `from-black/[85]` appears in the snippet but does not appear in the css output.

```
[a:"[]]from-black/[85]
```

**Describe your issue**

I'm using a package of components that uses `cva` for some styles. The styles are sometimes structured like:

```tsx
export const imageOverlayClasses = cva(
  [
    'w-full',
    'bg-gradient-to-t',
    'from-black/[85]',
    'to-transparent',
  ]
)
```
Which is compiled to a `index.js` where the styles show up as `... dx=se(["w-full","bg-gradient-to-t","from-black/[85]","to-transparent"] ...`. For some reason, `from-black[85]` isn't picked up by tailwind, while `w-full`, `bg-gradient-to-t` and `to-transparent` is.

Makes me think that the regex is missing arbitrary styles when they're nested in brackets.

Might be related to #11241

**Comment by adamwathan** [comment] 2023-06-07 12:29
Hey! Can you please provide a reproduction? Definitely is applicable 🫣

**Comment by adamwathan** [comment] 2023-06-07 13:04
I pasted your code into Tailwind Play and it looks like all of the classes are picked up:

https://play.tailwindcss.com/UGlr6X9Xvm

<img width="745" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/4323180/b4bf33cc-7195-46d1-bcfb-0786111a1667">

Are you scanning the source file for classes or the compiled file? I tested both and both are working here. Really need a reproduction to be able to help more.

**Comment by gukj** [comment] 2023-06-07 15:16
> Hey! Can you please provide a reproduction? Definitely is applicable 🫣

Of course — my bad!

I tried using a larger snippet from `index.js` in the playground and I can't find `.from-black\/\[85\]` in the css (should be at line 210 in the generated css.

The snippet I tried (`from-black/[85]` appears at 1:3358):
```
"M12 12L22 2",strokeWidth:"2","stroke-linecap":"round",className:zt(e?"rotate-90":"rotate-0",t==="black"?"stroke-black":"stroke-white","origin-[17px_7px] translate-y-0 transition-transform")})]})}),ix=se("gudl-accordion-item cursor-pointer border-b pb-4 pt-6",{variants:{intent:{black:"border-neutral-300",white:"border-neutral-50"}},defaultVariants:{intent:"black"}}),ox=se("gudl-accordion-item-title desktop-h5-bold",{variants:{intent:{black:"text-black",white:"text-white"}},defaultVariants:{intent:"black"}}),lx=({className:e,data:t,startsOpen:r,intent:n="black"})=>{const[a,o]=R.useState(r?0:null);return q.jsx("div",{className:e,children:t.map((l,c)=>q.jsx(sx,{title:l.title,setActiveIndex:o,index:c,activeIndex:a,intent:n,children:l.children},c))})},sx=({className:e,title:t,children:r,index:n,activeIndex:a,setActiveIndex:o,intent:l="black"})=>{const c=u=>{o(a!==u?u:null)};return q.jsxs("div",{className:de(ix({intent:l}),e),onClick:()=>c(n),children:[q.jsx("h3",{className:"max-w-none",children:q.jsxs("button",{className:"flex w-full items-center justify-between gap-4 pb-2 text-start","aria-expanded":n===a?"true":"false","aria-controls":`sect${n+1}`,id:`accordion${n+1}id`,children:[q.jsx("span",{className:ox({intent:l}),children:t}),q.jsx(qd,{open:n===a,intent:l})]})}),q.jsx("section",{className:zt(n===a?"ease-expressive max-h-96":"max-h-0  ease-[cubic-bezier(0,1,0,1)]","duration-medium transition-height -mx-2 -mb-2 overflow-hidden pb-2 motion-reduce:transition-none"),id:`sect${n+1}`,"aria-labelledby":`accordion${n+1}id`,children:typeof r=="string"?q.jsx("p",{className:zt(l==="black"?"text-black":"text-white","text-body m-2 max-w-none"),children:r}):q.jsx("div",{className:"m-2 max-w-none",children:r})})]})},Nn={"4/3":"","3/4":"","5/3":"","7/5":"","5/7":"","16/9":"","9/16":"","21/9":"","1/1":""},Zd={"4/3":["aspect-4/3"],"3/4":["aspect-3/4"],"5/3":["aspect-5/3"],"7/5":["aspect-7/5"],"5/7":["aspect-5/7"],"16/9":["aspect-16/9"],"9/16":["aspect-9/16"],"21/9":["aspect-21/9"],"1/1":["aspect-1/1"]},cx=se(["projectName-card","grid","rounded-lg","w-full","self-start"],{variants:{retro:{true:["p-4"]},backgroundColor:{white:["bg-white","shadow"],transparent:["bg-transparent"]},aspectRatio:Zd,fullImage:{true:["grid-rows-[auto_1fr_max-content]"],false:["grid-rows-[minmax(min-content,max-content)]"]},clickableCard:{true:["cursor-pointer"]}},compoundVariants:[{aspectRatio:"21/9",fullImage:!0,class:["md:grid-cols-[1fr_max-content_1fr]","gap-10","grid-rows-[auto]"]}]}),ux=se(["projectName-card-image","h-full","w-full","overflow-hidden"],{variants:{retro:{false:["rounded-t-lg"]},fullImage:{true:["col-start-1","row-span-full"],false:["row-start-1","col-start-1"]},aspectRatio:Zd},compoundVariants:[{aspectRatio:"21/9",fullImage:!0,class:["md:col-span-full","md:row-span-full","md:h-full"]},{retro:!1,fullImage:!0,class:["rounded-b-lg"]}]}),fx=se("projectName-card-content",{variants:{fullImage:{true:["z-10","relative [&>*]:text-white col-span-full","row-start-3","self-end"]},retro:{true:["pt-8"],false:["px-6","py-8"]},aspectRatio:Nn},compoundVariants:[{fullImage:!0,retro:!0,class:["px-6","py-8"]},{aspectRatio:"21/9",fullImage:!0,class:["md:col-start-3","md:row-span-full","md:self-center","md:pl-0"]}]}),dx=se(["projectName-card-image-overlay","col-span-full","row-span-full","h-full","w-full","bg-gradient-to-t","from-black/[85]","to-transparent"],{variants:{aspectRatio:Nn,fullImage:{true:""},retro:{false:""}},compoundVariants:[{fullImage:!0,aspectRatio:"21/9",class:["md:bg-gradient-to-l"]},{retro:!1,fullImage:!0,class:["rounded-b-lg"]}]}),hx=se(["projectName-card-tags","z-10","col-span-full","row-start-1","inline-flex","h-max","flex-wrap","gap-2","pt-4"],{variants:{fullImage:{true:""},aspectRatio:Nn},compoundVariants:[{fullImage:!0,aspectRatio:"21/9",class:["w-1/2"]}]}),px=se(["projectName-card-video-button","col-span-full","place-self-center"],{variants:{fullImage:{true:"row-start-2",false:"row-start-1"},aspectRatio:Nn},compoundVariants:[{fullImage:!0,aspectRatio:"21/9",class:"col-span-1 md:col-start-2 md:col-end-3 row-start-1"}]}),vx=({title:e,backgroundColor:t="white",cardClassName:r,contentClassName:n,href:a,"aria-label":o,tags:l=[],image:c,description:u,eyebrow:p,fullImage:v=!1,retro:z=!1,aspectRatio:$,onCardPress:S,onVideoPress:O,children:M})=>{const A=l?.length>0,H=e||u||p||M,B=a?"a":"article";let V={};return a&&(V={target:"_blank"}),q.jsxs(B,{href:a,onClick:S&&!a?S:void 0,className:de(cx({retro:z,aspectRatio:$,fullImage:v,clickableCard:!!a||!!S,backgroundColor:t}),r),"aria-label":o,...V,children:[A&&q.jsx("div",{className:de(hx({aspectRatio:$,fullImage:v})),children:l.slice(0,2).map(T=>T&&q.jsx(Mu,{size:"sm",iconName:T.iconName,intent:T.variant,children:T.text}))}),c&&q.jsxs(q.Fragment,{children:[q.jsx("figure",{className:de(ux({fullImage:v,aspectRatio:$,retro:z})),children:q.jsx("img",{className:"h-full w-full object-cover object-center",src:c.url,alt:c.alt})}),v&&q.jsx("div",{className:de(dx({aspectRatio:$,fullImage:v,retro:z}))})]}),O&&q.jsx(kn,{className:de(px({fullImage:v,aspectRatio:$})),iconName:"play",onPress:O,intent:"primary-white","aria-label":"Play video"}),H&&q.jsxs("div",{className:de(fx({fullImage:v,aspectRatio:$,retro:z,className:n})),children:[p&&q.jsx(cn,{className:"projectName-card-eyebrow mb-2",variant:"special-eyebrow",children:p}),e&&q.jsx(cn,{className:"projectName-card-title mb-2",variant:"heading-5",children:e}),u&&q.jsx(cn,{className:"projectName-card-description mb-4",variant:"paragraph-small-body",children:u}),M]})]})};var Gd={},Yd={},he={},mx=function(t,r,n){var a=document.head||document.getElementsByTagName("head")[0],o=document.createElement("script");typeof r=="function"&&(n=r,r={}),r=r||{},n=n||function(){},o.type=r.type||"text/javascript",o.charset=r.charset||"utf8",o.async="async"in r?!!r.async:!0,o.src=t,r.attrs&&yx(o,r.attrs),r.text&&(o.text=""+r.text);var l="onload"in o?Ac:gx;l(o,n),o.onload||Ac(o,n),a.appendChild(o)};function yx(e,t){for(var r in t)e.setAttribute(r,t[r])}function Ac(e,t){e.onload=function(){this.onerror=this.onload=null,t(null,e)},e.onerror=function(){this.onerror=this.onload=null,t(new Error("Failed to load "+this.src),e)}}function gx(e,t){e.onreadystatechange=function(){this.readyState!="complete"&&this.readyState!="loaded"||(this.onreadystatechange=null,t(null,e))}}var wx=function(t){return bx(t)&&!Ex(t)};function bx(e){return!!e&&typeof e=="object"}function Ex(e){var t=Object.prototype.toString.call(e);return t==="[object RegExp]"||t==="[object Date]"||zx(e)}var xx=typeof Symbol=="function"&&Symbol.for,Px=xx?Symbol.for("react.element"):60103;function zx(e){return e.$$typeof===Px}function Sx(e){return Array.isArray(e)?[]:{}}function xr(e,t){return t.clone!==!1&&t.isMergeableObject(e)?Zt(Sx(e),e,t):e}function Ox(e,t,r){return e.concat(t).map(function(n){return xr(n,r)})}function Cx(e,t){if(!t.customMerge)return Zt;var r=t.customMerge(e);return typeof r=="function"?r:Zt}function kx(e){return Object.getOwnPropertySymbols?Object.getOwnPropertySymbols(e).filter(function(t){return Object.propertyIsEnumerable.call(e,t)}):[]}function Ic(e){return Object.keys(e).concat(kx(e))}function Xd(e,t){try{return t in e}catch{return!1}}function $x(e,t){return Xd(e,t)&&!(Object.hasOwnProperty.call(e,t)&&Object.propertyIsEnumerable.call(e,t))}function Tx(e,t,r){var n={};return r.isMergeableObject(e)&&Ic(e).forEach(function(a){n[a]=xr(e[a],r)}),Ic(t).forEach(function(a){$x(e,a)||(Xd(e,a)&&r.isMergeableObject(t[a])?n[a]=Cx(a,r)(e[a],t[a],r):n[a]=xr(t[a],r))}),n}function Zt(e,t,r){r=r||{},r.arrayMerge=r.arrayMerge||Ox,r.isMergeableObject=r.isMergeableObject||wx,r.clone
```

**Comment by RobinMalfait** [comment] 2023-07-05 13:23
Hey @gukj I'm struggling to see how you end up in that scenario exactly.

The long version:
```js
export const imageOverlayClasses = cva(
  [
    'w-full',
    'bg-gradient-to-t',
    'from-black/[85]',
    'to-transparent',
  ]
)
```
Should work fine.

The minified version should work fine as well:
```js
dx=se(["w-full","bg-gradient-to-t","from-black/[85]","to-transparent"])
```

But I'm struggling to see how you end up at:
```js
[a:"[]]from-black/[85]
```

If you simplify the minified version by dropping classes that aren't relevant I would expect to end up with something like this:
```js
dx=se(["w-full","bg-gradient-to-t","from-black/[85]","to-transparent"])
se(["w-full","bg-gradient-to-t","from-black/[85]","to-transparent"])
x(["w-full","bg-gradient-to-t","from-black/[85]","to-transparent"])
x(["from-black/[85]"])
```

We did do some fixes that will be available in the next release, but you can already try them in the insiders version:
- `npm install tailwindcss@insiders`

That said, I have 2 questions for you:
1. Does the error still occur if you use the insiders version?
2. If it still occurs, can you share the exact case that is failing?

**Comment by RobinMalfait** [comment] 2023-07-14 11:42
Going to close this issue for now, feel free to comment if the issue still occurs using the insiders built.

I know this version fails right now: `[a:"[]]from-black/[85]` but I don't see how you got into that state apart from trying to manually reducing the example. So if it works with the minified code that you mentioned earlier:

```js
dx=se(["w-full","bg-gradient-to-t","from-black/[85]","to-transparent"])
se(["w-full","bg-gradient-to-t","from-black/[85]","to-transparent"])
x(["w-full","bg-gradient-to-t","from-black/[85]","to-transparent"])
x(["from-black/[85]"])
```

Then I think this is not an issue to worry about.

**Closed by RobinMalfait** 2023-07-14 11:42 UTC

**Comment by gukj** [comment] 2023-08-10 11:37
@RobinMalfait I got to that state by just reducing the original string, so worries there. Looks like 3.3.3 fixes the issue I had with the original minified source — thanks! 🎉

**Comment by RobinMalfait** [comment] 2023-08-10 11:43
Aha beautiful, glad its working!
