### ISSUE TITLE
info and warn console messages duplicated

### ISSUE THREAD

**Issue by exodusanto** [tailwindlabs/tailwindcss#2186] opened 2020-08-18 21:07 UTC
### Describe the problem:

Using the new version **1.7**, with `future` or `experimental` flags, 
in console the `warn` and `info` messages are duplicated during build or using `npm run hot`

![image](https://user-images.githubusercontent.com/13484843/90565351-1406cf00-e1a7-11ea-8621-fabe009853b6.png)

**Comment by akturatech** [comment] 2020-08-18 22:03
I also have the same issue using Tailwind with Angular without any flags set. I tried setting `removeDeprecatedGapUtilities: true` in future setting but this just changes the warnings in to info messages. The messages are repeated over 200 times. The previous version works without issue.

![image](https://user-images.githubusercontent.com/23112857/90569992-36720a00-e1f2-11ea-91aa-57f1773e1966.png)

**Comment by LandGod** [comment] 2020-08-18 22:30
I am facing a similar issue to this, however, in my case, the message is somehow being attached to the top of my minified css file during build, which causes the browser to no be able to read it and thus removes all css from my website. I realize there is something else at play in this case, but allowing an option to simply silence all console messages during build would be incredibly helpful here.

**Comment by wongmjane** [comment] 2020-08-18 23:04
It looks like the amount of the duplicated warning messages scales as the amount of CSS modules

I created a sample project for consistently reproducing this duplication: https://github.com/wongmjane/sampletail

The build log is available here: https://vercel.com/wongmjane/sampletail/g2vnyrd05

**Comment by adamwathan** [comment] 2020-08-19 01:17
Fixed in v1.7.1, might be able to improve the fix but wanted to get something out quickly to at least stop annoying people for now :)

**Comment by mustafawm** [comment] 2020-08-19 01:17
The [upcoming page](https://tailwindcss.com/docs/upcoming-changes) says that `gap-x/y-` should replace `col/row-gap-` but it's warning me about files where i'm only suing `gap-`! has this also been depricated?

**Closed** 2020-08-19 01:17 UTC

**Comment by adamwathan** [comment] 2020-08-19 01:30
Tailwind doesn't read your HTML files at all to detect usage, it simply warns you until you explicitly opt-in saying you are comfortable disabling the old utilities. You will continue to see that warning forever unless you add `removeDeprecatedGapUtilities: true`, even if you are only using the new utility names.

**Comment by mustafawm** [comment] 2020-08-19 04:27
Updated to 1.7.1, added `removeDeprecatedGapUtilities: true`, now I'm only getting this once:
```
info - You have opted-in to future-facing breaking changes: removeDeprecatedGapUtilities
info - These changes are stable and will be the default behavior in the next major version of Tailwind.
```
