### ISSUE TITLE
[Bug]: Text opacity stopped working

### ISSUE THREAD

**Issue by SimonPrague** [tailwindlabs/tailwindcss#4424] opened 2021-05-21 12:34 UTC
**What component**
- URL for category:  https://tailwindui.com/components/marketing/page-examples/landing-pages
- Component name:  Simple with offset screenshot hero

**Describe the bug**
Text opacity was working fine and without any change in my code it stopped working on a recent update. I'm not sure if it's Tailwind CSS or some other dependency but it must be a bug as it's very clearly working on development and not when compiled for production.

* Seems like it's just `text-opacity-*` and `opacity-*` is still working
* Note that the original component was red but I changed the colors to green. It's mostly the same component.
* I'm providing just one example but it broke all over the site ... it's not an isolated incident
* I tried to trace to which dependency like postcss or something is responsible but I was not able to figure it out
* I understand that this might be bug with Tailwind CSS and not UI but I felt this is more relevant place to post it, feel free to move it to the right place
* I don't have ` extend: { opacity: { '30': '0.3', }, },` in my `tailwind.config.js` as it was not necessary. I tried adding it and it did not help.

**To Reproduce**
1. Compile project for production
4. Transparency is missing in resulted CSS

Example of a page when it used to work: 
https://dynamitejobs.com/SimonPayne
Example of a page where it's already broken: 
https://2021-may-20-thu-23-05-56-dot-djplatform.uc.r.appspot.com/SimonPayne

**Expected behavior**
I expect the text transparency to still be there :) The final value is not calculated correctly.

**Screenshots**
The part of code in question:
![Screenshot_2021-kvě-21-Pá_14-06-27](https://user-images.githubusercontent.com/47515740/119135784-2b792e00-ba3f-11eb-8a28-5df7cdcb9241.png)
This is how the development vs production build looks like in inspector:
![Screenshot_2021-kvě-21-Pá_14-12-14](https://user-images.githubusercontent.com/47515740/119135794-2e741e80-ba3f-11eb-9209-2d2eb3fba41e.png)

**Browser/Device (if applicable)**
 - OS: Fedora 33 (Workstation Edition)
 - Browser Chromium
 - Version 90.0.4430.85 (RPM Fusion Build) (64-bit)
 - Vue 3
 - Vue Cli 5.0.0-beta.1
 - Tailwind 2.1.2 with JIT
 - Typescript 4.2.4

**Additional context**
Development CSS from inspector:
```css
.text-opacity-30 {
    --tw-text-opacity: 0.3;
}
.text-cyan-400 {
    --tw-text-opacity: 1;
    color: rgba(34, 211, 238, var(--tw-text-opacity));
}
```
Production build CSS from inspector:
```css
.text-opacity-30 {
    --tw-text-opacity: 0.3;
}
.text-cyan-400 {
    --tw-text-opacity: 1;
    color: #22d3ee;
}
```
**Config files**

<details>
<summary>package.json</summary>

```json
{
  "name": "djplatform",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build --dest dist --report",
    "test:unit": "vue-cli-service test:unit src/**/*/*.{ts,vue} src/**/*.spec.ts",
    "lint": "vue-cli-service lint"
  },
  "importSort": {
    ".js, .jsx, .es6, .es, .mjs, .ts, .tsx, .vue": {
      "parser": "import-sort-parser-babel-vue",
      "style": "import-sort-style-module-scoped",
      "options": {}
    }
  },
  "dependencies": {
    "@firebase/auth-types": "^0.10.3",
    "@firebase/firestore-types": "^2.3.0",
    "@foundernest/namecase": "^1.0.2",
    "@heroicons/vue": "^1.0.1",
    "@tailwindcss/line-clamp": "^0.2.0",
    "@tiptap/core": "^2.0.0-beta.66",
    "@tiptap/extension-blockquote": "^2.0.0-beta.13",
    "@tiptap/extension-bold": "^2.0.0-beta.13",
    "@tiptap/extension-bullet-list": "^2.0.0-beta.13",
    "@tiptap/extension-document": "^2.0.0-beta.12",
    "@tiptap/extension-dropcursor": "^2.0.0-beta.13",
    "@tiptap/extension-gapcursor": "^2.0.0-beta.17",
    "@tiptap/extension-hard-break": "^2.0.0-beta.13",
    "@tiptap/extension-heading": "^2.0.0-beta.13",
    "@tiptap/extension-highlight": "^2.0.0-beta.13",
    "@tiptap/extension-history": "^2.0.0-beta.12",
    "@tiptap/extension-italic": "^2.0.0-beta.13",
    "@tiptap/extension-list-item": "^2.0.0-beta.13",
    "@tiptap/extension-ordered-list": "^2.0.0-beta.13",
    "@tiptap/extension-paragraph": "^2.0.0-beta.14",
    "@tiptap/extension-text": "^2.0.0-beta.12",
    "@tiptap/extension-typography": "^2.0.0-beta.12",
    "@tiptap/vue-3": "^2.0.0-beta.37",
    "await-to-js": "^3.0.0",
    "axios": "^0.21.1",
    "firebase": "9.0.0-beta.1",
    "logrocket": "^1.2.0",
    "sanitize-html": "^2.4.0",
    "transliteration": "^2.2.0",
    "uuid": "^8.3.2",
    "vue": "^3.0.11",
    "vue-router": "^4.0.8",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.14.2",
    "@babel/plugin-proposal-optional-chaining": "^7.14.2",
    "@stripe/stripe-js": "^1.15.0",
    "@tailwindcss/aspect-ratio": "^0.2.0",
    "@tailwindcss/forms": "^0.3.2",
    "@tailwindcss/typography": "^0.4.0",
    "@types/chai": "^4.2.18",
    "@types/mocha": "^8.2.2",
    "@types/sanitize-html": "^2.3.1",
    "@types/uuid": "^8.3.0",
    "@types/webpack": "^5.28.0",
    "@types/webpack-assets-manifest": "^5.0.0",
    "@types/yup": "^0.29.11",
    "@typescript-eslint/eslint-plugin": "^4.24.0",
    "@typescript-eslint/parser": "^4.24.0",
    "@vue/cli-plugin-babel": "~4.5.13",
    "@vue/cli-plugin-eslint": "~4.5.13",
    "@vue/cli-plugin-router": "~4.5.13",
    "@vue/cli-plugin-typescript": "~4.5.13",
    "@vue/cli-plugin-unit-mocha": "~4.5.13",
    "@vue/cli-service": "~5.0.0-beta.1",
    "@vue/compiler-sfc": "^3.0.11",
    "@vue/eslint-config-typescript": "^7.0.0",
    "@vue/test-utils": "^2.0.0-beta.11",
    "autoprefixer": "^10.2.5",
    "chai": "^4.3.4",
    "eslint": "^7.26.0",
    "eslint-plugin-vue": "^7.9.0",
    "import-sort": "^6.0.0",
    "import-sort-parser-babel-vue": "^1.0.6",
    "postcss": "8.3.0",
    "source-map-support": "^0.5.19",
    "tailwindcss": "^2.1.2",
    "typescript": "~4.2.4",
    "vue-cli-plugin-postcss-preset": "^1.0.2",
    "vue-cli-plugin-tailwind": "~2.0.6",
    "vue-eslint-parser": "^7.6.0",
    "webpack-assets-manifest": "^5.0.6"
  }
}
```
</details>

<details>
<summary>tailwind.config.js</summary>

```js
// eslint-disable-next-line @typescript-eslint/no-var-requires
const defaultTheme = require('tailwindcss/defaultTheme')

// eslint-disable-next-line @typescript-eslint/no-var-requires
const colors = require('tailwindcss/colors')

let containerScreens = Object.assign({}, defaultTheme.screens)

// Delete the 2xl breakpoint from the object
// delete containerScreens['2xl']

// containerScreens['2xl'] = '1336px'

// Default theme values
// https://github.com/tailwindlabs/tailwindcss/blob/master/stubs/defaultConfig.stub.js#L5

module.exports = {
  mode: 'jit',
  purge: [
    './public/**/*.html',
    './src/**/*.{js,ts,vue}',
  ],
  // purge: {
  //   enabled: process.env.NODE_ENV === 'production',
  //   preserveHtmlElements: process.env.NODE_ENV !== 'production',
  //   content: [
  //     './public/**/*.html',
  //     './src/**/*.vue',
  //   ],
  //   options: {
  //     defaultExtractor(content) {
  //       const contentWithoutStyleBlocks = content.replace(/<style[^]+?<\/style>/gi, '')
  //       return contentWithoutStyleBlocks.match(/[A-Za-z0-9-_/:]*[.A-Za-z0-9-_/]+/g) || []
  //     },
  //     safelist: {
  //       standard: [/-(leave|enter|appear)(|-(to|from|active))$/, /^(?!(|.*?:)cursor-move).+-move$/, /^RouterLink(|-exact)-active$/, /data-v-.*/],
  //     },
  //   }
  // },
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      "cool-gray": colors.coolGray,
      gray: colors.gray,
      red: colors.red,
      rose: colors.rose,
      yellow: colors.amber,
      green: colors.emerald,
      blue: colors.blue,
      indigo: colors.indigo,
      purple: colors.violet,
      pink: colors.pink,
      teal: colors.teal,
      emerald: colors.emerald,
      cyan: colors.cyan,
      orange: colors.orange,
      'light-blue': colors.lightBlue,
    },
    container: {
      screens: containerScreens,
    },
    extend: {
      ringOffsetColor: ['hover', 'active', 'focus'],
      zIndex: {
        '0': 0,
        '10': 10,
        '15': 15,
        '20': 20,
        '25': 25,
        '30': 30,
        '35': 35,
        '40': 40,
        '45': 45,
        '50': 50,
        '55': 55,
        '60': 60,
        '65': 65,
        '70': 70,
        '75': 75,
        '80': 80,
        '85': 85,
        '90': 90,
        '95': 95,
        '100': 100,
        'auto': 'auto',
      },
      inset: {
        '-px': '-1px',
        '-0': '-0',
        '-1': '-0.25rem',
        '-2': '-0.5rem',
        '-3': '-0.75rem',
        '-4': '-1rem',
        '-5': '-1.25rem',
        '-6': '-1.5rem',
        '-8': '-2rem',
        '-10': '-2.5rem',
        '-12': '-3rem',
        '-16': '-4rem',
      },
      height: {
        '1/4': '25%',
        '3/4': '75%',
        '1/2': '50%',
        '1/3': '33.3%',
        '2/3': '66.6%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
      },
      minHeight: {
        px: '1px',
        '0': '0',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '28': '7rem',
        '32': '8rem',
        '36': '9rem',
        '40': '10rem',
        '44': '11rem',
        '48': '12rem',
        '52': '13rem',
        '56': '14rem',
        '60': '15rem',
        '64': '16rem',
        '72': '18rem',
        '80': '20rem',
        '96': '24rem',

        xs: '20rem',
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        '3xl': '48rem',
        '4xl': '56rem',
        '5xl': '64rem',
        '6xl': '72rem',

        '1/4': '25%',
        '3/4': '75%',
        '1/2': '50%',
        '1/3': '33.3%',
        '2/3': '66.6%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
      },
      minWidth: {
        '12': '3rem',
        '1/4': '25%',
        '3/4': '75%',
        '1/2': '50%',
        '1/3': '33.3%',
        '2/3': '66.6%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
      },
      maxWidth: {
        '1/4': '25%',
        '3/4': '75%',
        '1/2': '50%',
        '1/3': '33.3%',
        '2/3': '66.6%',
        '1/5': '20%',
        '2/5': '40%',
        '3/5': '60%',
        '4/5': '80%',
      },
      screens: {
        'sm-h': { 'raw': '(min-height: 360px)' },
        'md-h': { 'raw': '(min-height: 720px)' },
        'gh-d': { 'raw': '(min-height: 1080px)' },
        'xl-h': { 'raw': '(min-height: 1280px)' },
      },
      typography: (theme) => ({
        // See: https://github.com/tailwindlabs/tailwindcss-typography/blob/master/src/styles.js
        // And: https://github.com/tailwindlabs/tailwindcss-typography
        md: {
          css: {
            '> ul > li > p': {
              marginTop: '0px',
              marginBottom: '0px',
            },
            '> ol > li > p': {
              marginTop: '0px',
              marginBottom: '0px',
            },
            '> ul > li > *:first-child': {
              marginTop: '0px',
            },
            '> ul > li > *:last-child': {
              marginBottom: '0px',
            },
            '> ol > li > *:first-child': {
              marginTop: '0px',
            },
            '> ol > li > *:last-child': {
              marginBottom: '0px',
            },
            'mark': {
              backgroundColor: theme('colors.red.100'),
            },
          },
        },
      }),
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
        // sans: ['Inter var', ...defaultTheme.fontFamily.sans],
      },
    }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),  // https://github.com/tailwindlabs/tailwindcss-typography
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/line-clamp'),
  ],
  // future: {
  //   purgeLayersByDefault: true,
  //   removeDeprecatedGapUtilities: true,
  //   defaultLineHeights: true,
  //   standardFontWeights: true,
  // },
}
```

</details>

<details>

<summary>tsconfig.json</summary>

```js
{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strictNullChecks": true, // because of YUP https://github.com/jquense/yup/blob/master/docs/typescript.md
    "strictFunctionTypes": false, // because of YUP https://github.com/jquense/yup/blob/master/docs/typescript.md
    "sourceMap": true,
    "baseUrl": ".",
    "types": [
      "webpack-env",
      "mocha",
      //"chai"
    ],
    "paths": {
      "@/*": [
        "src/*",
      ],
      // "@": [
      //   "src/*",
      // ],
    },
    "lib": [
      "esnext",
      // "es2019.array", // https://stackoverflow.com/questions/53556409/typescript-flatmap-flat-flatten-doesnt-exist-on-type-any
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.vue",
  ],
  "exclude": [
    "node_modules"
  ]
}
```
</details>

<details>
  <summary>postcss.config.js</summary>

```js
module.exports = {
  'plugins': {
    'tailwindcss': './tailwind.config.js',
    'autoprefixer': {},
    // 'postcss-preset-env': {
    //   'stage': 3,
    //   'features': {
    //     'nesting-rules': true
    //   }
    // },
  }
}
```

</details>

**Comment by adamwathan** [comment] 2021-05-21 20:41
Hey! Can you create a small GitHub repo that minimally reproduces this issue? I can't reproduce this problem on my end when doing production builds, so will need a (small and heavily reduced) example project that demonstrates this behavior in order to track it down.

**Comment by davidluhr** [comment] 2021-05-21 20:41
@SimonPrague I'm transferring this over to the Tailwind CSS repo, as I don't believe this is specific to Tailwind UI.

As you pointed out, it seems like something in your build process is compiling colors to HEX, instead of retaining the `rgba`. My first hunch would be PostCSS, but it's possible this "optimization" is happening elsewhere.

It's unclear if this is an issue in Tailwind CSS, as `opacity-` classes are working as expected across tailwindcss.com, tailwindui.com, etc.

**Comment by SimonPrague** [comment] 2021-05-21 22:22
Thank you guys for your time. It started happening even on `opacity-` It's probably something to do with latest PostCSS. But I did not change anything in my code so it was just some package updated. 

I'll try to prepare some repository to showcase the problem.

**Comment by SimonPrague** [comment] 2021-05-21 22:27
I have a suspicion it's this change of dependency:

![Screenshot_2021-kvě-22-So_00-26-40](https://user-images.githubusercontent.com/47515740/119203901-73767000-ba94-11eb-9a30-49ca996d8e33.png)

**Comment by adamwathan** [comment] 2021-05-21 23:52
Gotcha glad to see more info, so this looks like it's happening in cssnano during your minification phase, and is due to an underlying dependency in cssnano which now appears to be fixed 👍🏻 

Going to close as not a Tailwind issue. Literally nothing we can do, our code outputs the colors correctly, it only breaks when you are using cssnano and that would break even without Tailwind. Hopefully pulling in latest cssnano will resolve this for you 👍🏻

**Closed by adamwathan** 2021-05-21 23:52 UTC

**Comment by SimonPrague** [comment] 2021-05-24 14:51
Yup, it works now. I did not even know I'm using `cssnano`. I mean I don't do anything special for it to be used :) It's probably some dependency. My setup is fairly basic `vue-cli`.

Anyway I appreciate you had time to take a look and respond. 

Cheers,
Simon
