### ISSUE TITLE
Gradients with color defined via CSS variable/custom property break generated CSS file

### ISSUE THREAD

**Issue by maltebaer** [tailwindlabs/tailwindcss#5736] opened 2021-10-08 08:29 UTC
**What version of Tailwind CSS are you using?**

v2.2.16

**What build tool (or framework if it abstracts the build tool) are you using?**

laravel-mix, v6.0.25

**What version of Node.js are you using?**

v14.17.6

**What browser are you using?**

Chrome, Firefox

**What operating system are you using?**

macOS

**Reproduction URL**

https://play.tailwindcss.com/VzO2yFtf1p

**Describe your issue**

If you try to apply a gradient using colors defined via custom property the generate CSS will be broken.

**Input**
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --primary: 25, 169, 157; /* #19a99d; */
  }
}
```

```js
const colors = require('tailwindcss/colors')

function withOpacity(variableName) {
  return ({ opacityValue }) => {
    if (!opacityValue) {
      return `rgb(var(${variableName})`
    }

    return `rgba(var(${variableName}), ${opacityValue})`
  }
}

module.exports = {
  mode: 'jit',
  theme: {
    extend: {},
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      gray: colors.trueGray,
      primary: {
        DEFAULT: withOpacity('--primary'),
     },
    },
  },
  variants: {},
  plugins: [],
}

```

```html
<div class="w-full h-full p-8 space-y-8">
  <div class="bg-primary w-full h-64 rounded"></div>
  <div class="bg-gradient-to-br from-primary w-full h-64 rounded"></div>
</div>
```

**Output**
```css
/* ... */

/* brackets are missing */
.from-primary {
        --tw-gradient-from: rgb(var(--primary) !important;
        --tw-gradient-stops: var(--tw-gradient-from), var(--tw-gradient-to, rgb(var(--primary)) !important;
}

/* ... */
```

**Comment by adamwathan** [comment] 2021-10-09 13:54
Hey! The problem is a bug in your code where you are missing the closing paren:

```diff
  function withOpacity(variableName) {
    return ({ opacityValue }) => {
      if (!opacityValue) {
-       return `rgb(var(${variableName})`
+       return `rgb(var(${variableName}))`
      }
  
      return `rgba(var(${variableName}), ${opacityValue})`
    }
  }
```

Works then:

https://play.tailwindcss.com/OkNNvJAhKJ

Hope that helps!

**Closed by adamwathan** 2021-10-09 13:54 UTC
