### ISSUE TITLE
can't use arbitrary group selectors with group labels that contains `$` character

### ISSUE THREAD

**Issue by sibbng** [tailwindlabs/tailwindcss#10402] opened 2023-01-23 19:03 UTC
**Reproduction URL**

https://play.tailwindcss.com/3uWb41wv5q

**Describe your issue**

Hi, I was testing the changes in #10276 and it seems that the first group in the following code does not generate the related classes:

```html
<!-- doesn't work -->
<div class="group/${id} foo">
  <div class="group-[.foo]/${id}:bg-gray-300">group-[.foo]/${id}:bg-gray-300</div>
</div>

<!-- works -->
<div class="group/{id} foo">
  <div class="group-[.foo]/{id}:bg-gray-300">group-[.foo]/{id}:bg-gray-300</div>
</div>
```

To be honest, I'm surprised to see Tailwind support this kind of use case. I would expect to see a convention like; *"Only alphanumeric group labels supported."*. Since the use case mentioned in the original issue [misunderstood the way how Tailwind works](https://github.com/tailwindlabs/tailwindcss/issues/10266#issuecomment-1374513943), I would expect this issue to be fixed by just fixing the compiler error rather than generating a *"false positive"*(?) I guess.

Also, it seems #10276 trying to __balance brackets__. In my opinion, balanced shouldn't be a must. For example, the following code is should be totally valid and generate corresponding classes if special characters are allowed in group labels, but it doesn't.

```html
<div class="group/{id foo">
  <div class="group-[.foo]/{id:bg-gray-300">group-[.foo]/{id:bg-gray-300</div>
  <!--                        ^ second bracket is removed -->
</div>
```

**Comment by Mullins22W** [comment] 2023-02-10 05:14
Hello,
Yes, that is correct. The "$" character is a special character in regular expressions and can cause issues when used in group labels. To work around this, you can either escape the "$" character with a backslash (e.g. "$"), or you can use a different character for your group label.

**Comment by jalalbmnf** [comment] 2023-04-03 13:13
Is this issue solved? @reinink

**Comment by Goicerouth** [comment] 2023-06-01 05:05
Based on the provided code, it seems that there are issues with generating the related classes for the first group in Tailwind CSS. The code using ${id} in the class doesn't generate the expected classes, while the code using {id} works correctly.

You mentioned that you expected a convention stating that only alphanumeric group labels are supported, but it seems that Tailwind allows for more flexibility. However, the issue you encountered might be a compiler error or false positive.

Regarding the balancing of brackets, you mentioned that it shouldn't be a requirement for the code to work correctly. For example, in the code <div class="group/{id foo">, the second closing bracket is removed, but you would still expect the corresponding classes to be generated.

[MyBKExperience Survey](https://www.mybkexperience.onl/)

**Comment by DonLogsdon** [comment] 2023-07-10 07:16
Hello,

I can see your issue
The dollar sign ($) character is often reserved for specific purposes, such as variable names or special identifiers. Consequently, using arbitrary group selectors with group labels containing the $ character may cause conflicts or unexpected behavior.

To address this, you can consider a few alternatives:

Escape the $ Character: In some languages, you can escape special characters using a backslash () to treat them as literal characters. For example, if you have a group label like "Group$1", you can use the selector "Group$1" to specify it in your code.

Use Different Group Labeling: If possible, consider using alternative group labels that don't include the $ character. This helps avoid potential conflicts and makes it easier to work with group selectors.

Modify or Extend the Language Syntax: If you have control over the language or framework you are using, you might consider modifying or extending the syntax rules to support arbitrary group selectors with specific characters. However, this approach may require more significant changes and should be approached with caution.

Try above steps might helps you
DonLogsdon

**Comment by Haydenpayne** [comment] 2023-08-21 08:53
Thanks for the information.

**Comment by reinink** [comment] 2023-09-04 20:34
Hey folks! My apologies on the delay here — I started looking into this back in January, which led to some internal discussions, but it never went anywhere from there.

So you're right, currently it's not possible to use a `$` character in group names. The changes in #10276 weren't intended to make this possible, but rather to fix an issue where the build was failing if you did use a `$` in a group name. We've fixed things so that the build no longer crashes, but Tailwind still doesn't see this as a valid class.

We could potentially make this possible, but for now we've opted to limit the allowed characters here to keep our parser sane to work with. We can't allow just any character in the group names, as some characters of course have special meaning in Tailwind. For example, you couldn't use the `:` character as that's the separator we use to determine class modifiers like screen sizes, hover, focus, etc.

While changing this behavior isn't something that we're able to prioritize right now, I've made a note about this internally as we're already having some discussions about permitted class name characters as we look ahead to the next version of Tailwind, so I'm certain this will get brought up as we work through that.

One final consideration — please keep in mind that you cannot use string interpolation or concatenate partial class names together when working with Tailwind — Tailwind will not find them and therefore will not generate the corresponding CSS. Meaning dynamically generating named group classes using `group/${id}`, where the `${id}` piece is swapped out dynamically with a real value, will not work. This is something that's covered in our documentation: https://tailwindcss.com/docs/content-configuration#dynamic-class-names

Hope that helps!

**Closed by reinink** 2023-09-04 20:34 UTC
