### ISSUE TITLE
`shadow-[...]` loses the CSS property `box-shadow` when specifying an offset via `theme()`

### ISSUE THREAD

**Issue by Serator** [tailwindlabs/tailwindcss#12096] opened 2023-09-27 14:33 UTC
**What version of Tailwind CSS are you using?**

v3.3.3

**What browser are you using?**

Chrome 117.0.5938.92

**What operating system are you using?**

Windows 10

**Reproduction URL**

https://play.tailwindcss.com/1muYy6Ty4y

**Describe your issue**

When specifying the `shadow-[...]` [offset](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow#values) via the `theme()` function, the CSS property `box-shadow` is lost and the shadow is not displayed.

![image](https://github.com/tailwindlabs/tailwindcss/assets/625005/d233b062-22ce-45a1-a359-c57f46d45a25)

**Comment by thecrypticace** [comment] 2023-09-27 18:18
Hey, this is because it's ambiguous on which type property should be chosen, `shadow` or `color`. This is because we also support setting the shadow color via an arbitrary property. In this case it's not able to figure out the intent and defaults to color rather than shadow. You can explicitly override this by prefixing the value itself with `shadow:` so you end up with a utility like so `shadow-[shadow:theme(spacing.0)_…]`.

I've updated your Tailwind Play to account for this: https://play.tailwindcss.com/dDamqDY62U

Hope that helps. ✨

**Comment by Serator** [comment] 2023-09-27 18:38
@thecrypticace Thank you! Could you please tell me where I can find a list of all possible similar prefixes?

**Comment by thecrypticace** [comment] 2023-09-27 18:58
These generally follow the list of [CSS data types](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Types) — we talk about this on the "[Resolving Ambiguities](https://tailwindcss.com/docs/adding-custom-styles#resolving-ambiguities)" page of the docs — but shadow might be one of the odd ones that doesn't have an explicit data type.

You can find a list here though:
https://github.com/tailwindlabs/tailwindcss/blob/61dc99f4adbebdbcfeb899f3bcd64167b49d758c/src/util/pluginUtils.js#L163-L180

I've made a note internally to discuss adding a table of these to the documentation.

**Comment by rcardona-eb** [comment] 2023-10-31 21:48
Thank you @Serator for bringing this up, it was exactly the same issue I was experimenting right now, and thanks @thecrypticace for your superb explanation of what the problem was and how to fix it.

Now @thecrypticace, I'm having something very similar but a little bit different (I'm building a plugin using ts):
```
[...]
'--popover-shadow-size': theme('boxShadow.xl'),
'--popover-shadow-color': theme('colors.green.500'),

'@apply shadow-[shadow:var(--popover-shadow-size)] shadow-[color:var(--popover-shadow-color)]':  {},
[...]
```
Here the `shadow:` hint works and the `color:` hint generates the right color but the the shadow color doesn't get applied. Here's the resulting css:
```
.popover {
  --popover-shadow-size: 0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1);
  --popover-shadow-color: #22c55e;
  --tw-shadow: var(--popover-shadow-size);
  --tw-shadow-colored: var(--popover-shadow-size);
  box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
  --tw-shadow-color: var(--popover-shadow-color);
  --tw-shadow: var(--tw-shadow-colored);
}

```

![image](https://github.com/tailwindlabs/tailwindcss/assets/109558810/75edfc88-5afd-4971-9826-06baf09d53fa)

Do you have an idea of what could be wrong here?

Thanks for your work.

**Comment by thecrypticace** [comment] 2023-10-31 22:02
It's because the use of variables prevents us from replacing the color in the shadow. Variables can be anything and change at runtime which makes resolving this issue impossible unfortunately.

**Comment by thecrypticace** [comment] 2023-10-31 22:13
Actually, it's a bit more subtle than that. This also appears for _any_ arbitrary value that's not immediately parsable as a shadow. That includes the use of the `theme()` fn because it's resolved later.

For example — only the first div these has a colored shadow:
```html
<!-- has colored shadow -->
<div class="shadow-[shadow:0_20px_25px_-5px_rgb(0_0_0/0.1),0_8px_10px_-6px_rgb(0_0_0/0.1)] shadow-[color:theme(colors.green.500)]">test</div>

<!-- has no colored shadow -->
<div class="shadow-[shadow:theme(boxShadow.xl)] shadow-[color:theme(colors.green.500)]">test</div>
```

To work around this in your situation you'd need to mirror the output of the first one in your CSS variable (by including a reference to `var(--tw-shadow-color)`)

**Comment by rcardona-eb** [comment] 2023-10-31 23:57
@thecrypticace in my snippet above I saved the value of `theme(boxShadow.lg)` in a css variable and used it like this:
```
'--popover-shadow-size': theme('boxShadow.xl'),
'@apply shadow-[shadow:var(--popover-shadow-size)]`
```
If I hardcode the value of `boxShadow.xl` into `shadow-[shadow:...]` it works just like you said. I think the problem is what you said:
> This also appears for any arbitrary value that's not immediately parsable as a shadow. That includes the use of the theme() fn because it's resolved later.

If I use borders, margins, paddings or other non <em>immediately parsable</em> properties I can perfectly reference things with no problems using the `theme` fn, but this doesn't work combing `theme` with properties like `box-shadow`, which is not immediately parsed.

Just one final question that I didn't get clearly... can you please elaborate on this (mainly including the reference to `--tw-shadow-color`)?
>you'd need to mirror the output of the first one in your CSS variable (by including a reference to var(--tw-shadow-color))

**Comment by thecrypticace** [comment] 2023-11-01 00:04
It's because of when the parsing happens:
https://github.com/tailwindlabs/tailwindcss/blob/b7bafaaf85d48becb166a1bf0b4ff3063ffe4a7f/src/corePlugins.js#L2355

In this case we see `var(--popover-shadow-size)` as the value — which is not a shadow value _itself_ and therefore not parsable. So it's the same situation.

Regarding the reference to `--tw-shadow-color` I mean something like this:
```
  '--popover-shadow-size': '0 20px 25px -5px var(--tw-shadow-color), 0 8px 10px -6px var(--tw-shadow-color)'
```

Which means you'd need to hardcode the value unless you wanted to parse the shadow and replace the color yourself.

[Here's an example of this working on Tailwind Play.](https://play.tailwindcss.com/QkpEEOFtHp)

**Comment by thecrypticace** [comment] 2023-11-01 00:08
_sigh_ I clicked the wrong buttons. I was prepping a better example and somehow posted the comment.

Here's one that replaces the colors for you: https://play.tailwindcss.com/szFJ1ZpiaM?file=config

**Closed** 2023-11-01 00:08 UTC

**Comment by rcardona-eb** [comment] 2023-11-01 00:13
Thank you so much for the detailed explanations @thecrypticace, I really appreciate it.
