### ISSUE TITLE
text-color is rendered incorrectly when minified

### ISSUE THREAD

**Issue by mocherif86** [tailwindlabs/tailwindcss#6380] opened 2021-12-10 21:39 UTC
I have the following sass being compiled to css then goes through tailwindcss
```
.header-breadcrumb {
  .breadcrumb-home-icon {
    @apply text-gray-100 hover:text-white;
  }
}
```
In tailwind 2 the output was 
```
.header-breadcrumb .breadcrumb-home-icon {
  --tw-text-opacity: 1;
  color: rgba(243, 244, 246, var(--tw-text-opacity));
}
```
so when minified works correctly, however after upgrading to tailwind 3 the following output is created:
```
.header-breadcrumb .breadcrumb-home-icon {
  --tw-text-opacity: 1;
  color: rgb(243 244 246 / var(--tw-text-opacity));
}
```
so when minified ends up becoming:
```
.header-breadcrumb .breadcrumb-home-icon {
  --tw-text-opacity: 1;
  color: rgb(243244246/var(--tw-text-opacity));
}
```
Which is not understoof by the browser as RGB

**Comment by adamwathan** [comment] 2021-12-10 23:49
Hey! Which minifier? This is a bug in the minifier as that is totally valid syntax:

![C7EB2B3F-6855-4F3A-9116-F1AF65B8B4F2](https://user-images.githubusercontent.com/4323180/145654853-e7c9e676-67da-468a-a3f0-f0e734967ffa.jpeg)

**Comment by mohamedcherifmo** [comment] 2021-12-11 14:17
Hi Adam,
Thanks for your prompt response, notation is definitely correct... and seems the issue is related to an external tool's minification (I'm using Sitecore and it automatically optimizes)... Working now on either moving to tailwind --minify (which is also giving me an error but still debugging through it)

**Comment by reinink** [comment] 2021-12-16 19:10
@mohamedcherifmo Thanks for the update here. Since it sounds like this is an issue with another tool, I am going to close this issue 👍

**Closed by reinink** 2021-12-16 19:10 UTC
