### ISSUE TITLE
Issue when run npm watch laravel 8 with talwind 2 (unwantend comma ->;,)

### ISSUE THREAD

**Issue by flowser** [tailwindlabs/tailwindcss#3303] opened 2021-01-07 10:06 UTC
```
  **4844** |
  4845 | .via-red-101 {
> 4846 |   --tw-gradient-stops: var(--tw-gradient-from), **#da16167a;, var**(--tw-gradient-to, rgba(255, 255, 255, 0));
       |                                                                                                    ^
  4847 | }
  4848 |
  4849 | .via-red-200 {
```

how do i solve that i am thinking of removing it (Unknown word (4846:59))`` the comma after the semi-colon

**Comment by adamwathan** [comment] 2021-01-07 13:45
Closing since no reproduction was provided, please reopen with a reproduction if this is an issue for you.

**Closed by adamwathan** 2021-01-07 13:45 UTC
