### ISSUE TITLE
Watch script doesn't rebuild after creating new file

### ISSUE THREAD

**Issue by josecarlosrx** [tailwindlabs/tailwindcss#9710] opened 2022-11-02 12:34 UTC
**What version of Tailwind CSS are you using?**

3.2.1

**What build tool (or framework if it abstracts the build tool) are you using?**

Create React App

**What version of Node.js are you using?**

16.14.2

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction**

`
module.exports = {
  content: ["./src/app/**/*.{html,js}"],
  theme: {
    // ...
  },
};
`

**Describe your issue**

I'm using tailwindcss without postcss. It works fine. The output CSS file is generated every time JS files are saved. The problem happens when I create a new JS file: the "watch" script stops working, it doesn't rebuild the output CSS anymore.

It's working ok with version 3.1.8 though.

**Comment by reinink** [comment] 2022-11-02 12:52
Hey! Thanks for reporting this. I'm fairly confident that this is a duplicate of #9667, so I'm going to close this issue in favor of that one. It also looks like we might have a possible solution already for this (see #9689), so stay tuned for an upcoming fix which will hopefully your resolve issue here too 👍

**Closed by reinink** 2022-11-02 12:52 UTC
