### ISSUE TITLE
flex + divide-x is incorrect on RTL

### ISSUE THREAD

**Issue by Newbie012** [tailwindlabs/tailwindcss#10179] opened 2022-12-27 12:47 UTC
**What version of Tailwind CSS are you using?**

3.2.4

**What build tool (or framework if it abstracts the build tool) are you using?**

```
"postcss": "8.4.20",
"next": "13.1.1",
```

**What version of Node.js are you using?**

v18.4.0

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

https://play.tailwindcss.com/uGu893pb62

**Describe your issue**

While using divide-x with flex, it doesn't play nicely on RTL.

Expected:

![image](https://user-images.githubusercontent.com/10504365/209668617-5031cb6f-93cd-45fc-9ef5-50a2af23318d.png)

Actual:

![image](https://user-images.githubusercontent.com/10504365/209668635-12e9b985-0e88-444c-9d8b-96559cd17e7f.png)

**Comment by adamwathan** [comment] 2022-12-27 14:58
Hey! This is currently by design, you should use `divide-x-reverse` when the direction of the children is reversed (either because of RTL or using `flex-row-reverse`):

https://tailwindcss.com/docs/divide-width#reversing-children-order

We considered moving to logical properties for these at one point but reverted it because the name `divide-x` doesn't make sense for stuff in the inline axis, since that axis can be vertical in vertical writing modes and `x` implies horizontal:

https://github.com/tailwindlabs/tailwindcss/pull/2644

This is something I'm definitely interested in exploring how to improve still, especially with #10166 now open, but going to close this as "not a bug" at least since it is currently the intended behavior.

**Closed by adamwathan** 2022-12-27 14:58 UTC

**Comment by TheMikeyRoss** [comment] 2024-07-03 03:11
@adamwathan How can I reverse a `grid` if I'm using `grid` instead of `flex` ?
