### ISSUE TITLE
Using multiple animations not working

### ISSUE THREAD

**Issue by Alwinator** [tailwindlabs/tailwindcss#5247] opened 2021-08-18 13:11 UTC
### What version of Tailwind CSS are you using?

v2.2.7

### What build tool (or framework if it abstracts the build tool) are you using?

Next.js 11.1.0

### What version of Node.js are you using?

v12.21.0

### What browser are you using?

Firefox

### What operating system are you using?

Ubuntu 21.04

### Reproduction repository

https://github.com/Alwinator/tailwind-multiple-animations-bug

### Describe your issue

You cannot combine animations. The expected behavior would be that the hello text in the project pulses and bounces. If you test both animations on their own they are working. 

I am not 100% sure, but I think Tailwind forgets to include the keyframes in the CSS.

**Warning:**
After you tried both animations on their own the combined animation also works. So make sure to completely restart the project after testing.

**Comment by bradlc** [comment] 2021-08-18 17:04
Hey @Alwinator. It looks like this is a duplicate of #5015

**Closed by bradlc** 2021-08-18 17:04 UTC
