### ISSUE TITLE
Dark mode broken in 3.4.0, last working 3.3.7

### ISSUE THREAD

**Issue by bilogic** [tailwindlabs/tailwindcss#12633] opened 2023-12-20 19:26 UTC
**What version of Tailwind CSS are you using?**
3.4.0

**What build tool (or framework if it abstracts the build tool) are you using?**
CDN
 
**What version of Node.js are you using?**

CDN, so N/A

**What browser are you using?**

Chrome

**What operating system are you using?**

Windows

**Reproduction URL**

We identified the offending CSS in https://github.com/tailwindlabs/tailwindcss/discussions/12627#discussioncomment-7911565

> 3.3.7:
> 
> ```css
> .dark .dark\:bg-neutral-700 { ... }
> ```
> 
> 3.4.0:
> 
> ```css
> :is(:where(.dark) .dark\:bg-neutral-700) { ... }
> ```
> 
> If the `:where()` pseudoclass is removed, everything starts to look the same.

**Describe your issue**

Dark mode is broken.

**Comment by andreww2012** [comment] 2023-12-20 19:38
See also https://github.com/tailwindlabs/tailwindcss/discussions/12627#discussioncomment-7911639

**Comment by Sarenor** [comment] 2023-12-20 20:44
[Skeleton](https://www.skeleton.dev) is also making use of ``darkMode: 'class'`` to enable the [LightSwitchs](https://www.skeleton.dev/utilities/local-storage-stores) behaviour of toggling the mode depending on the users choice persisted in Local Storage.

This update is breaking for all of our users that customized Skeleton components depending on light/dark mode since instead of ``dark:bg-primary-800`` they now have to use ``dark:!bg-primary-800``.

A resolution to this problem and preferably a revert until a major Tailwind version will be published would be very much appreciated.

**Comment by adamwathan** [comment] 2023-12-20 23:40
Hey! Can you please provide a reproduction? Something that shows some specific code that used to work and doesn't work now.

Dark mode _does_ work generally: https://play.tailwindcss.com/WZBZxlIUzn

**Comment by andreww2012** [comment] 2023-12-21 07:27
A basic example: https://play.tailwindcss.com/sxcXJrc50E

The button on hover used to preserve its color in the dark mode (stay violet), but in 3.4.0 it becomes green.

**Comment by Sarenor** [comment] 2023-12-21 15:24
A more convoluted example using Skeleton:

Working (with Tailwind 3.3.3): https://stackblitz.com/edit/skeletonlabs-repl-ojdt8e?file=src%2Froutes%2F%2Bpage.svelte

Not Working (with Tailwind 3.4.0): https://stackblitz.com/edit/skeletonlabs-repl-hxd8qn?file=src%2Froutes%2F%2Bpage.svelte

**Comment by sheepa** [comment] 2023-12-21 15:40
Can confirm dark mode is broken in 3.4.0. Hopefully this will get fixed.

**Comment by adamwathan** [comment] 2023-12-22 20:28
Was hoping to push out a solution for this before the holidays but likely not going to be until first week of January after the Christmas break, sorry folks. Use v3.3 in the mean time if you're affected by this and we'll push out an update right after the holidays.

**Comment by Sarenor** [comment] 2023-12-22 20:53
No problem Adam, we'll follow that advice for now. Thanks and have a nice holiday!

**Comment by mshajid** [comment] 2023-12-23 14:37
Thanks for letting us know! Let's see on the first week of jan. Enjoy the holidays.

**Comment by bilogic** [comment] 2023-12-23 16:13
Thanks @adamwathan

**Comment by AugustinBriolon** [comment] 2023-12-29 10:04
Hey, I have the same issue... So the only solutions for now is to downgrade to 3.3.7 ?

**Comment by thecrypticace** [comment] 2024-01-05 19:40
We've got a fix for this in #12717. I've got to backport this to v3.4, get a release out an update play + the cdn. It'll take a bit before everything's updated but everything should (hopefully) be out in the next hour or two. I'll leave a comment here when done.

**Closed** 2024-01-05 19:39 UTC

**Comment by thecrypticace** [comment] 2024-01-05 21:10
Release is out — play and CDN are both updated

**Comment by Sarenor** [comment] 2024-01-05 22:28
Successfully verified with the package. Thank you very much!

**Comment by thecrypticace** [comment] 2024-01-05 23:23
Fantastic — thanks for checking! ✨
