### ISSUE TITLE
Space utilities not working with flex order

### ISSUE THREAD

**Issue by scottzirkel** [tailwindlabs/tailwindcss#3730] opened 2021-03-11 02:14 UTC
When changing the flex order of elements, the space utilities are not updated. They are still applied in the original DOM order.

Here's an example:
https://play.tailwindcss.com/2vqKZW1mPW

**Comment by adamwathan** [comment] 2021-03-11 02:50
Duplicate of https://github.com/tailwindlabs/tailwindcss/issues/3724

**Closed by adamwathan** 2021-03-11 02:50 UTC

**Comment by scottzirkel** [comment] 2021-03-11 02:55
Hey @adamwathan, I saw that issue, I don't think it's a dupe. That is dealing with the reverse order, not specifying the flex order. `order-{n}` is what I'm trying to use.

Here's a screenshot of the playground to better show what I mean. The spacing of the top three are off, but the spacing of the bottom are correct.

<img width="1381" alt="Screen Shot 2021-03-10 at 8 54 47 PM" src="https://user-images.githubusercontent.com/1329131/110728526-dc16b600-81e2-11eb-8968-83c0ecd38836.png">

**Comment by adamwathan** [comment] 2021-03-11 02:57
Bleh sorry trigger happy on this one. Yeah in this case it's just gonna be a limitation of what's possible in CSS, not really any way for us to automatically support that. `space-x-{n}` is just a shortcut for "add margin to everything except the first child", so if that's not the behavior you need, you'll have to just add margin to each element manually.

**Comment by scottzirkel** [comment] 2021-03-11 02:58
OK cool. Was afraid that's what it was. Thanks!
