### ISSUE TITLE
Default `font-family` (no custom fonts) on linux (Ubuntu/Kubuntu) does not render properly font weights

### ISSUE THREAD

**Issue by frederikhors** [tailwindlabs/tailwindcss#8258] opened 2022-05-03 10:50 UTC
**What version of Tailwind CSS are you using?**

v3.0.24

**What build tool (or framework if it abstracts the build tool) are you using?**

svelte-kit@latest

**What version of Node.js are you using?**

v16

**What browser are you using?**

Chrome

**What operating system are you using?**

linux@ubuntu/kubuntu

**Describe your issue**

I've always used Windows and Mac. Lately I've been forced to use linux (both Ubuntu and Kubuntu 22.04).

To my surprise the fonts on the site do not match those on Windows and Mac and a lot of the graphics work is spoiled by this "idiosyncrasy".

In the following screenshots you can see the tailwind website on Chrome v100 before and after changing the font-family (manually in the dev-tools panel).

As you can see, when the "Inter" font is removed (ie when we developers decide NOT to use custom fonts) the browser chooses to display everything with the "Noto Sans" font which does not distinguish between `font-light`, `font-normal` and `font-medium` and then between `font-semibold` and `font-bold`.

**Expected**

Can we change the default `font-family` in a smarter way that takes into account the default fonts on all the most used operating systems?

**Screens**

- with Inter font:

  ![image](https://user-images.githubusercontent.com/41120635/166439581-3b845ec1-86a0-4469-b984-f0c34de53314.png)

- without Inter font:

  ![image](https://user-images.githubusercontent.com/41120635/166439571-743cc8cb-d97e-4f27-a674-edad437ab49b.png)

**Comment by adamwathan** [comment] 2022-05-07 20:19
Hey! Can you test if this renders better? This is with a change based on [this Bootstrap PR](https://github.com/twbs/bootstrap/pull/34547) to update their font stack for what looks like a similar issue.

https://play.tailwindcss.com/5hJD7n8T3j?file=css

I have no easy way to test on Ubuntu unfortunately.

**Comment by thecrypticace** [comment] 2022-05-09 19:29
I've got access to Parallels and have fresh installed an Ubuntu 20.04 VM on my machine. I've tested using both Firefox and Chromium (… not Chrome proper because I'm on an ARM64 chip).

This screenshot is from the tailwindcss.com website with `Inter var` removed from the font stack and the font's appear to have appropriate font sizes:
<img width="805" alt="Screen Shot 2022-05-09 at 14 56 15" src="https://user-images.githubusercontent.com/614993/167482845-884d927e-b0da-4686-89a1-8ba8cb1d8ce8.png">

The following two screenshots are from the Tailwind Play with the font-stack enabled/disabled and both have appropriately weighted fonts:

<img width="1728" alt="Screen Shot 2022-05-09 at 14 54 27" src="https://user-images.githubusercontent.com/614993/167483084-eb9d4bfd-1aca-44a5-85c4-d91bf78c7164.png">
<img width="1728" alt="Screen Shot 2022-05-09 at 14 54 20" src="https://user-images.githubusercontent.com/614993/167483094-c3ba6fff-6489-4903-b446-fda98bc24b58.png">

So, all that to say, unfortunately I can't reproduce this. Could there be an issue with the fonts installed on your machine?

**Comment by frederikhors** [comment] 2022-05-10 09:44
1. this is Fedora 35, Chrome 101, without `Inter`, the default font now is "Cantarell Light" (and there is the issue):

    ![image](https://user-images.githubusercontent.com/41120635/167597621-fc33638e-8950-443c-ad06-b59ac9753d6f.png)

1. This is Fedora 35, Chrome 101, with your custom css, the default font now is "Cantarell Light" (and there is the issue):

    ![image](https://user-images.githubusercontent.com/41120635/167598281-122b6b4a-ee97-4b29-9bf9-d537739c86ad.png)

1. This is Fedora 35, Chrome 101, without your custom css, the default font now is "Cantarell Light" (and there is the issue):

    ![image](https://user-images.githubusercontent.com/41120635/167598816-f2321752-1a0f-4ec3-b44f-22d8d1a52bc3.png)

1. This is Fedora 35, Firefox 93, without `Inter` (and there is the issue):

    ![image](https://user-images.githubusercontent.com/41120635/167599212-adcabce9-86af-418a-8d1e-3f47ed221736.png)

1. This is Fedora 35, Firefox 93, , with your custom css (and there is the issue):

    ![image](https://user-images.githubusercontent.com/41120635/167599575-b43af977-e20a-48f2-a186-11dd9a3a051f.png)

1. This is Fedora 35, Firefox 93, without your custom css (and there is the issue):

    ![image](https://user-images.githubusercontent.com/41120635/167599697-b8b2addc-8227-4e5a-b1a2-b7f4b6b5efa9.png)

**Comment by frederikhors** [comment] 2022-05-10 09:46
> I have no easy way to test on Ubuntu unfortunately.

Can you install it on a Windows machine with Hyper-V or similar?

I think tests on Mac (with Parallels) are not accurate as those on pure linux. Maybe Parallels is doing "something magic".

**Comment by frederikhors** [comment] 2022-05-10 13:04
@thecrypticace I tried with Kubuntu too (that was the screen). Thank you.

**Comment by adamwathan** [comment] 2022-05-11 19:28
We spent some more time looking into this just to be sure we understood exactly what was going on and the answer here is really just that on those OSes, `system-ui` maps to Cantarell and the version of Cantarell that ships with those OSes only supports a limited number of weights.

You can see on the Wikipedia page that the non-variable version of the font only includes four weights:

https://en.wikipedia.org/wiki/Cantarell_(typeface)

This means that of course certain Tailwind font-weight utilities will look the same, since there's no dedicated weight to actually render.

This is true of other system fonts as well, for example Segoe UI on Windows only includes 6 weights, when Tailwind includes 9 font-weight utilities.

Going to close this as just something we don't intend to take any action on — our default font stack intentionally uses the system font and like you've discovered that means there will be inconsistencies between different operating systems. We are comfortable with that trade-off because it means that at least out of the box Tailwind matches the look of the OS that user is on, and that there is no performance penalty for loading a custom font, but if it's important for your project that things look exactly the same in every browser then we recommend using a custom font. This is what we do for our own sites for example 👍

**Closed by adamwathan** 2022-05-11 19:28 UTC
