### ISSUE TITLE
[2.1] JIT mode break style with Next.js and webpack 5

### ISSUE THREAD

**Issue by valse** [tailwindlabs/tailwindcss#3994] opened 2021-04-06 22:17 UTC
### What version of Tailwind CSS are you using?

2.1.1

### What version of Node.js are you using?

12.21.0

### What browser are you using?

Chrome

### What operating system are you using?

Windows 10

### Reproduction repository

https://www.youtube.com/watch?v=QH2-TGUlwu4

After migrating from `@tailwind/jit` package to the new `tailwind` 2.1.x version enabling the `jit` mode, my Next.js project style breaks if I enable the webpack 5 support; with webpack 4 works fine.

**Comment by joneath** [comment] 2021-04-07 02:42
I'm seeing the same behavior in:

Tailwind: 2.1.1, 2.1.0
Node: 15.13.0
Browser: Chrome
OS: MacOS
Nextjs: 10.1.3

**Comment by valse** [comment] 2021-04-07 21:22
I tried to delete the node_modules folder and yarn.lock file and it works also with the webpack 5 option enabled

**Comment by joneath** [comment] 2021-04-08 04:45
Deleting node_modules and package-lock.json didn't fix it for me. What especially strange is that I've been using `@tailwindcss/jit` up until now with no problems. It feels like purge isn't working and is removing all styles.

**Comment by chrisgrabinski** [comment] 2021-04-08 19:36
@joneath Try also deleting your `.next` directory.
After I did that, I noticed these two lines started showing up in my terminal after running `npm run dev` and JIT was working as expected.

```
warn - You have enabled the JIT engine which is currently in preview.
warn - Preview features are not covered by semver, may introduce breaking changes, and can change at any time.
```

**Comment by joneath** [comment] 2021-04-09 02:25
@chrisgrabinski I just tried deleting `node_modules`, `package-lock.json`, and the `.next` directory and still no luck. I'm not seeing those warning messages either. I also tried disabling my custom server setup and using the nextjs server which made no difference. I'll punt on this for another day and then attempt again with a vanilla `next.config.js` setup.

**Comment by a-y-u-s-h** [comment] 2021-04-09 18:56
@chrisgrabinski Deleting `node_modules`, etc not working for me either.

**Comment by a-y-u-s-h** [comment] 2021-04-09 19:03
I got my issue resolved guys. So I didn't include all extensions in `purge` content options. I was using `yaml` files in several places for configurations, after adding it, it worked with webpack5 as well.

How my config looks:

```jsx
const YAML = require("./.loaders/yaml.js")
const extensions = YAML.read("src/settings/theme/elements/extensions.yaml")
const foundations = YAML.read("src/settings/theme/elements/foundations.yaml")
const variants = YAML.read("src/settings/theme/elements/state.settings.yaml")

module.exports = {
  mode: "jit",
  purge: [
    "./public/**/*.html",
    "./src/**/*.{js,jsx,ts,tsx,vue,css,scss,yaml}",
    "./src/**/**/*.{js,jsx,ts,tsx,vue,css,scss,yaml}"
  ],
  darkMode: "class",
  theme: {
    extend: {
      ...foundations,
      ...extensions
    }
  },
  variants: {
    extend: {
      ...variants
    }
  },
  plugins: [
    require("@tailwindcss/aspect-ratio"),
    require("@tailwindcss/typography"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/custom-forms"),
    require("tailwindcss-filters")
  ]
}

```

**Comment by joneath** [comment] 2021-04-10 04:05
Ugh I feel so dumb. My issue was caused when migrating from `@tailwindcss/jit`. I removed `@tailwindcss/jit` from the plugins section of `postcss.config.js` but never replaced it with `tailwindcss` 🤦. Everything is working now.

**Comment by bradlc** [comment] 2021-05-13 12:33
> I tried to delete the node_modules folder and yarn.lock file and it works also with the webpack 5 option enabled

So if this issue resolved then @valse? If not please can you provide a reproduction so that we can help to debug? Thanks!

**Comment by shareef99** [comment] 2021-05-14 09:46
I am also facing the same issue.

**Comment by adamwathan** [comment] 2021-05-14 10:15
@shareef99 can you please provide a reproduction repository? Currently there is no reproduction anywhere in this issue so we are unable to help.

**Comment by dan-kwiat** [comment] 2021-05-14 14:38
FWIW I just experienced this with `next@10.1.3`, `webpack5: true` and `tailwindcss@2.1.2` in jit mode. Some classes got generated but not others e.g. `grid-cols-3` despite correct `purge` config. Restarting the script didn't help.

Fixed by deleting `node_modules`, `.next`, `yarn.lock` and re-installing.

Otherwise it works beautifully :)

**Comment by adamwathan** [comment] 2021-05-14 14:56
Since no reproduction has been provided here and it sounds like @valse has solved their particular issue, I'm going to close this, if only because it has attracted a lot of +1s but we still don't have a reproduction.

Hopefully by closing it the next person who encounters it will open a new issue instead and include a reproduction 🤞

**Closed by adamwathan** 2021-05-14 14:56 UTC

**Comment by dan-kwiat** [comment] 2021-05-17 13:14
Sorry I'm not able to publicise the code but sharing my experience in case it's useful.

Just ran into this problem again - after successfully working on the project for a while, suddenly new classes failed to generate. I think the break happened after editing & saving a file twice in quick succession.

Fixed by deleting `.next` dir and restarting the next dev script. Not sure if this is an issue with next + webpack5 or tailwind jit.

**Comment by shareef99** [comment] 2021-05-23 07:11
I solve this by 
```npm
npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
```

**Comment by kayac-chang** [comment] 2021-05-23 13:58
> I solve this by
> 
> ```
> npm install -D tailwindcss@latest postcss@latest autoprefixer@latest
> ```

I'm currently using the latest version, but the issue still existed on `webpack5` with `JIT` mode

```
"autoprefixer": "^10.2.5",
"tailwindcss": "^2.1.2",
"postcss": "^8.3.0"
```

**Comment by shareef99** [comment] 2021-05-25 14:25
@kayac-chang 

> Since no reproduction has been provided here

Try giving a reproduction.
It might help you

**Comment by itshoro** [comment] 2021-06-19 18:18
I am also facing this issue, but I lack steps to reproduce it. To me it can happen with any Next.js project, it just happens randomly.

When running the dev script *sometimes* the purge doesn't find new classes at some point during its life time.  It applies to both arbitrary values and inbuilt ones. 

It's also not like tailwind isn't building the file, you are able to add and remove classes that were there prior and that properly changes the output but when trying to add a class that didn't occour before it just doesn't show up.

Restarting the dev script makes it dissappear.

Other than that I like to modify the `tailwind.config.js`. Saving it seems to force a restart of just tailwind, which is much faster and also fixed the problem (well until it happens again down the line).

**Comment by adamwathan** [comment] 2021-06-19 18:29
Hey! Please open a new issue if you are having problems with this, and make sure to include what versions you are using. We made changes for v2.2 that should make this impossible (we hope!) so it's helpful to know if people are experience it even on Next 11 + Tailwind CSS v2.2.

I'm going to lock this because we don't really monitor closed issues and I will miss important stuff if people are always chiming in here vs. opening new issues. Please don't hesitate to open new issues for the same problem if it's still happening though.
