### ISSUE TITLE
@apply not working with styled-jsx (Next.js v10, Tailwind v2)

### ISSUE THREAD

**Issue by DaniGuardiola** [tailwindlabs/tailwindcss#2870] opened 2020-11-22 14:39 UTC
There is another bug already about this (#1234), but it is closed as it seems like a solution was found for previous versions. I am using the new Tailwind v2 and I've tried some of the configurations listed in the issue's comments but none have worked for me. Maybe there's something wrong with my setup, but I'm posting as a new bug just in case it's related to Tailwind v2.

## Relevant configs

```jsonc
// .babelrc
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["styled-jsx-plugin-postcss"]
        }
      }
    ]
  ]
}
```

```js
// postcss.config.js
module.exports = {
  plugins: ['tailwindcss', 'autoprefixer']
}
```

```jsonc
// deps (package.json)
{
  "dependencies": {
    "bluebird": "^3.7.2",
    "classnames": "^2.2.6",
    "next": "10.0.2",
    "next-mdx-remote": "^1.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  },
  "devDependencies": {
    "@types/bluebird": "^3.5.33",
    "@types/classnames": "^2.2.11",
    "@types/node": "^14.14.9",
    "@types/react": "^17.0.0",
    "autoprefixer": "^10.0.2",
    "gray-matter": "^4.0.2",
    "postcss": "^8.1.8",
    "styled-jsx-plugin-postcss": "^3.0.2",
    "tailwindcss": "^2.0.1",
    "typescript": "^4.1.2"
  }
}
```

## Errors that I'm getting

```
wait  - compiling...
[styled-jsx] Loading plugin from path: /home/dani/projects/daniguardiola-me/node_modules/styled-jsx-plugin-postcss/index.js
Next.js 9 default postcss support uses a non standard postcss config schema https://err.sh/next.js/postcss-shape, you must use the interoperable object-based format instead https://nextjs.org/docs/advanced-features/customizing-postcss-config
Next.js 9 default postcss support uses a non standard postcss config schema https://err.sh/next.js/postcss-shape, you must use the interoperable object-based format instead https://nextjs.org/docs/advanced-features/customizing-postcss-config
error - ./components/Post.tsx
Error: /home/dani/projects/daniguardiola-me/components/Post.tsx: postcss failed with TypeError: Invalid PostCSS Plugin found: [0]
    at Array.forEach (<anonymous>)
```

**Comment by adamwathan** [comment] 2020-11-22 14:59
Hey! Please provide a GitHub repo that reproduces the issue so we don't have to create it from scratch ourselves, we can help much faster if all we need to do is clone a reproduction and see what's happening.

**Comment by DaniGuardiola** [comment] 2020-11-22 15:02
@adamwathan I literally just finished doing that, and I'm about to push it, hang tight :)

**Comment by DaniGuardiola** [comment] 2020-11-22 15:06
@adamwathan here you go: https://github.com/DaniGuardiola/tmp-tailwind-bug-repro

**Comment by adamwathan** [comment] 2020-11-22 17:34
I don't get any errors but the reason `@apply` doesn't work as far as I can tell is that styled JSX isn't being processed by your custom PostCSS config which I don't think we can really do anything about in Tailwind itself.

On my end it builds and I get this:

![image](https://user-images.githubusercontent.com/4323180/99910907-ce363700-2cbe-11eb-920f-961997c4ee17.png)

I'm going to close this as not a Tailwind issue because Tailwind isn't even being run against that code so I'm not sure what we can do to help aside from help troubleshoot any configuration problems with Next.js. Happy to offer my two cents there with any ideas I have but no action we can really take in the codebase I'm afraid :/

**Closed by adamwathan** 2020-11-22 17:34 UTC
Labels: needs reproduction

**Comment by DaniGuardiola** [comment] 2020-11-22 18:43
Okay thanks, @adamwathan, I think I will take it to the Next.js issue tracker then. I'll report back here if I ever get a solution, to help folks who come from Google with a similar problem.

**Comment by DaniGuardiola** [comment] 2020-11-22 18:44
Of course, if you see something wrong with the Next.js configuration, please let me know. AFAIK, it should be working with the given PostCSS and Babel configs :(
