### ISSUE TITLE
[v4] Styling doesn't get applied properly to ::after elements

### ISSUE THREAD

**Issue by spaceemotion** [tailwindlabs/tailwindcss#15241] opened 2024-11-29 14:55 UTC
**What version of Tailwind CSS are you using?**
v4 beta 3

**What build tool (or framework if it abstracts the build tool) are you using?**
Astro 5 beta, Vite 6.01

**What version of Node.js are you using?**
v20

**What browser are you using?**
Chrome, Brave

**What operating system are you using?**
Windows, Linux

**Reproduction URL**
https://play.tailwindcss.com/X0BTXShKkd

**Describe your issue**
The element no longer looks the same when upgrading from v3 to v4. the after-styles don't get applied properly:

Before (v3):
![image](https://github.com/user-attachments/assets/17953996-8ecf-4d1d-b7ab-75203d5e50ba)

After (v4):
![image](https://github.com/user-attachments/assets/0a21b147-9212-44a2-9fcb-1c6caa79b581)

I also noticed that every `after` directive seems to re-add the `content: var(--tw-content)` line, which seems a bit redundant?
![image](https://github.com/user-attachments/assets/8d804c47-1c78-4b23-950e-785bea1961e4)

**Comment by ktmn** [comment] 2024-11-29 16:17
In TW4 the variant chaining order is reversed, changing 
`after:data-[active=true]:border-solid` -> `data-[active=true]:after:border-solid` 
seems to work. (Although there might be some special cases for some variants where the order shouldn't matter, don't know off the top of my head which ones these are, if any)

> I also noticed that every after directive seems to re-add the content: var(--tw-content) line, which seems a bit redundant?

Especially when using `@apply`, you can end up with like 10 lines of the same declaration in the same selector and LightningCSS doesn't minify it out, for some reason.

**Comment by Alma219Way** [comment] 2024-11-30 04:59
Thanks for providing all the details. It sounds like the issue you're facing with Tailwind CSS v4 beta 3 might be due to changes in how pseudo-elements and content are handled.

In Tailwind CSS v4, the ::after and ::before pseudo-elements are treated differently compared to v3. The content: var(--tw-content) line being re-added is part of this update. You might need to adjust your Tailwind configuration or utility classes to align with these changes. 

Best Regards,
Alma
[MyFedLoan](https://www.my-fedloan.com)

**Comment by philipp-spiess** [comment] 2024-12-04 08:29
@spaceemotion Did changing the variant order fix all problems for you here?

> I also noticed that every after directive seems to re-add the content: var(--tw-content) line, which seems a bit redundant?

Yeah this is unfortunate but since these utilities don't have to be used together on the same node there's really no way I can see we can meaningfully reduce that output :/ 

> Especially when using `@apply`, you can end up with like 10 lines of the same declaration in the same selector and LightningCSS doesn't minify it out, for some reason.

We found a few of those issues where lightningcss doesn't minify the output fully right now. That's something that's currently under active investigation by both parties.

**Comment by spaceemotion** [comment] 2024-12-04 09:14
@philipp-spiess ah sorry, yes!  swapping the order indeed fixed the issue. I just wasn't sure if that was the intention with v4, or just a known workaround.

Glad to hear about the efforts to improve minification :)

**Comment by philipp-spiess** [comment] 2024-12-04 09:29
Definitely expected: https://tailwindcss.com/docs/v4-beta#stacking-order-sensitive-variants our upgrade tool also converts this case automatically.

Going to close this as it's not a bug then, thanks for the report and for your testing 🙇

**Closed by philipp-spiess** 2024-12-04 09:29 UTC
