### ISSUE TITLE
I use px-5 and px-10 at same class but px-10 is not applied

### ISSUE THREAD

**Issue by NhaPCS** [tailwindlabs/tailwindcss#9102] opened 2022-08-15 09:08 UTC
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/9101

<div type='discussions-op-text'>

<sup>Originally posted by **NhaPCS** August 15, 2022</sup>
Hi, I haven't gotten this issue before, my code is not changed, but in some way, I use `px-5` and `px-10` in the same class (please check the photo below). 

The `px-10` should be overrides `px-5` but it's not. It overrides before.

<img width="473" alt="Screen Shot 2022-08-15 at 16 02 54" src="https://user-images.githubusercontent.com/9054422/184608021-7210b8b0-1ac0-4601-88b1-85c9f4e13f27.png">

Has anyone face this issue before? 
Thanks for your help!</div>

**Comment by syedfahad1122** [comment] 2022-08-15 09:13
> ### Discussed in #9101
> Originally posted by **NhaPCS** August 15, 2022 Hi, I haven't gotten this issue before, my code is not changed, but in some way, I use `px-5` and `px-10` in the same class (please check the photo below).
> 
> The `px-10` should be overrides `px-5` but it's not. It overrides before.
> 
> <img alt="Screen Shot 2022-08-15 at 16 02 54" width="473" src="https://user-images.githubusercontent.com/9054422/184608021-7210b8b0-1ac0-4601-88b1-85c9f4e13f27.png">
> Has anyone face this issue before? Thanks for your help!

**Comment by RobinMalfait** [comment] 2022-08-15 09:31
Closing in favour of the discussion since this is not a bug.

**Closed** 2022-08-15 09:31 UTC
