### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Danon** [tailwindlabs/tailwindcss#4129] opened 2021-04-20 17:59 UTC
### What version of Tailwind CSS are you using?

^2.1.0

### What build tool (or framework if it abstracts the build tool) are you using?

webpack, tailwind jit

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome 89.0.4389.128, 64-bit

### What operating system are you using?

Windows 10

### Reproduction repository

https://github.com/Danon/tailwind-em-issue

### Describe your issue

Normally, when designing UI's, when you don't change the global state, you'd expect your unit to remain the same size. That's the definition of a unit.

Yet, when I use tailwind `w-4` and/or tailwind `mr-1`, which use `em`, when I resized my page (not in a way that would cause a responsive breakpoint to kick in), I can see that the units are actually malformed in a very weird way.

It "looks" as if squeezing webpage in width would cause the units to squeeze as well. When I remove the `em`-kind utilities everything works as it's supposed to and is rigid again.

Styles with `px`:
![px](https://user-images.githubusercontent.com/13367735/115442840-c9949100-a212-11eb-920e-0009d10b1838.gif)

Styles with tailwind:
![em](https://user-images.githubusercontent.com/13367735/115442865-d0230880-a212-11eb-86cb-a5f89bf1164a.gif)

Maybe the squeezing nature of `em` is required in containers or tables, but for something like lists (my case), it looks really wierd when icons stop being horiznotal.

**Comment by ccchapman** [comment] 2021-04-20 19:12
This is [expected behaviour](https://www.w3.org/TR/css-flexbox-1/#flex-flex-shrink-factor) of the Flexbox layout model.

Your issue can be resolved by adding `flex-shrink-0` to each icon.

**Comment by Danon** [comment] 2021-04-20 19:31
I added, didnt change anything. Same effect. BTW, chaning to px margin
fixes that despite the flexbox.

wt., 20 kwi 2021, 21:13 użytkownik Chris Chapman ***@***.***>
napisał:

**Comment by SirMishaa** [comment] 2021-04-21 01:56
Please provide a reproducible example. Make a new sample project that includes whatever is required to reproduce the bug.

**Comment by adamwathan** [comment] 2021-04-25 13:23
Your demo works as expected for me, all of the icons are 16px x 16px which is what h-4 and w-4 set:

<img width="461" alt="image" src="https://user-images.githubusercontent.com/4323180/115994800-7fab0280-a5a6-11eb-8d57-45a4543a75bb.png">

In your first screenshot the icons are bigger than 16px by the looks of it, so it seems like you are just comparing two non-equivalent implementations.

There's also some `fa-w-16` class being added at runtime somehow, which is setting some other styles that are not from Tailwind at all and overriding the icon size. Tailwind doesn't include any `em` units anywhere, only `rem` and `px`.

You can see even in your project `mr-1` is using rem not em:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/4323180/115995064-bf261e80-a5a7-11eb-9271-baedfd86eb73.png">

I can't really tell what steps you are taking when you say "when I remove the em-kind utilities" since Tailwind doesn't include any `em` stuff, and I'm also not sure what you're actually showing in your "Styles with px" screenshot, like where you are actually changing anything to px.

Going to close as there's really no way this is a Tailwind bug per se but happy to provide more input if you can share more concrete details.

**Closed by adamwathan** 2021-04-25 13:23 UTC
