### ISSUE TITLE
Plugin config extensions aren't deepmerged.

### ISSUE THREAD

**Issue by Hugos68** [tailwindlabs/tailwindcss#15021] opened 2024-11-17 18:18 UTC
**What version of Tailwind CSS are you using?**

- 3.4.9

**What build tool (or framework if it abstracts the build tool) are you using?**

- vite:  5.0.3

**What version of Node.js are you using?**

- 22.11.0

**What browser are you using?**

- Chrome

**What operating system are you using?**

- Windows

**Reproduction URL**

Unsure how to reproduce in tailwind.play as it's a config issue and I can't access the post merge config.

**Describe your issue**

[In the tailwind docs](https://tailwindcss.com/docs/plugins#extending-the-configuration) it states quote:
> Plugins can merge their own set of configuration values into the user’s tailwind.config.js configuration by providing an object as the second argument to the plugin function.

So when doing the following:
```js
import plugin from 'tailwindcss/plugin';

export default {
    content: ['one']
    plugins: [
       plugin(() => {}, { content: ['two'] })
    ]
}
```

I would expect the merged config to look like:
```js
export default {
    content: ['one', 'two']
}
```
But the actual resulted config is:
```js
export default {
    content: ['one']
}
```

This means because the `content` field is present in the config, the plugin's `content` field is completely ignored. This makes authoring plugins more painful as know I need to instruct users to add stuff to their `content` field manually instead of have my plugin do this *for* them.

Is this intended behaviour?

**Comment by wongjn** [comment] 2024-11-17 18:31
It is intended behavior. The plugin configuration logic follows [that of presets](https://tailwindcss.com/docs/presets#merging-logic-in-depth):

> The following options in `tailwind.config.js` simply **replace** the same option if present in a preset:
>
> - `content`
> - `darkMode`
> - `prefix`
> - `important`
> - `variantOrder`
> - `separator`
> - `safelist`

We can also see in the source code:

https://github.com/tailwindlabs/tailwindcss/blob/f65023efb97832660dc17cf954504f9f156047ba/src/util/resolveConfig.js#L255-L277

It explicitly merges `theme`, `corePlugins` and `plugins`, but the rest of the configuration keys are "collapsed", replacing each other (via the [`defaults()` function](https://github.com/tailwindlabs/tailwindcss/blob/v3.4.9/src/util/defaults.js)).

**Comment by Hugos68** [comment] 2024-11-17 18:36
Can/will this ever change? It makes authoring plugins in some scenario's a bit difficult. As I'm authoring a component library that utilises tailwind so the end user needs to configure their content path to include our package inside node_modules. It would be awesom if our already present tailwind plugin could handle this *for* them.

**Comment by wongjn** [comment] 2024-11-17 18:40
As a work-around, you could consider having consumers wrap their configuration object in a function you `export`:

```js
import { tailwindConfigWrapperFunction } = 'my-library';

export default tailwindConfigWrapperFunction({
  // Consumer Tailwind configuration.
});
```

This would allow you to augment the configuration as desired.

**Comment by philipp-spiess** [comment] 2024-11-19 11:06
@Hugos68 Hey! 

> Can/will this ever change? 

In v3 probably not, as this would be considered a breaking change and we'd rather focus on the release of v4.

In v4, this is going to be much easier because the config for custom content paths was moved into CSS. The idea is that your v4 plugin could export a CSS file that your users can update, and that CSS file can add custom content rules like so:


```css
/* my-plugin/index.css */
@source "./components/*.js"; /* add a path to scan for content relative to the this CSS file */
@plugin "./src/plugin.js";
```

Then, a consumer of your library could register the plugin by importing a CSS file:

```css
@import "my-plugin";
```

This is already supported in the current version of v4 so I suggest you give it a try (we'll have a beta release out _very_ soon too 👀).

I'm going to mark this issue as a won't fix but if you have any issues with the v4 example, please let us know and we'll look into it!

**Closed by philipp-spiess** 2024-11-19 11:06 UTC
