### ISSUE TITLE
Tailwind fails to compile animate-pulse: "Cannot set property 'parent' of undefined."

### ISSUE THREAD

**Issue by nataliemeurer** [tailwindlabs/tailwindcss#8854] opened 2022-07-14 02:15 UTC
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/8853

<div type='discussions-op-text'>

<sup>Originally posted by **nataliemeurer** July 13, 2022</sup>
Hi all,

My team is encountering an issue building tailwind for specific classes locally, particularly `.animate-pulse`. Here is some information on our version, setup, and error.

## Versions
    "postcss": "8.4.14",
    "tailwindcss": "^3.1.6"

## Build System

We are running a create-react-app setup with craco for configuration. We are using postcss with the following craco configuration:

```
const appDirectory = fs.realpathSync(process.cwd());
const resolveApp = (relativePath) => path.resolve(appDirectory, relativePath);

module.exports = {
	style: {
		postcss: {
      plugins: [
        require('tailwindcss'),
        require('autoprefixer'),
      ],
    }
	},
	plugins: [
		{
			plugin: require('craco-babel-loader'),
			options: {
				includes: [resolveApp('../api')],
			},
		},
	],
};
```

## Error
```
$ tailwind build -i src/styles/index.css -o src/styles/tailwind.css

🌼 daisyUI components 2.13.6 
  ✔︎ Including:  base, components, themes[1]
  
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError: Cannot set property 'parent' of undefined
    at Root.removeChild (my/project/node_modules/postcss/lib/container.js:522:30)
    at Root.removeChild (my/project/node_modules/postcss/lib/root.js:49:45)
    at Proxy.remove (my/project/packages/react-app/node_modules/postcss/lib/node.js:78:19)
    at Rule (my/project/packages/react-app/node_modules/postcss-nested/index.js:209:43)
    at LazyResult.visitSync (my/project/packages/react-app/node_modules/postcss/lib/lazy-result.js:308:19)
    at LazyResult.walkSync (my/project/packages/react-app/node_modules/postcss/lib/lazy-result.js:297:20)
    at my/project/packages/react-app/node_modules/postcss/lib/lazy-result.js:291:39
    at Root.each (my/project/node_modules/postcss/lib/container.js:105:16)
    at LazyResult.walkSync (my/project/packages/react-app/node_modules/postcss/lib/lazy-result.js:290:16)
    at LazyResult.sync (my/project/packages/react-app/node_modules/postcss/lib/lazy-result.js:247:14) {
  postcssNode: <ref *3> Rule {
    raws: { semicolon: true },
    selector: '.animate-pulse',
    type: 'rule',
    nodes: [],
    parent: <ref *1> Root {
      raws: {},
      type: 'root',
      nodes: [
        <ref *2> AtRule {
          raws: {},
          name: 'keyframes',
          params: 'pulse',
          type: 'atrule',
          nodes: [ [Rule] ],
          parent: [Circular *1],
          proxyCache: [Circular *2],
          lastEach: 1,
          indexes: {},
          [Symbol(my)]: true
        },
        [Circular *3]
      ],
      lastEach: 1,
      indexes: { '1': 1 },
      [Symbol(my)]: true,
      [Symbol(isClean)]: false
    },
    proxyCache: [Circular *3],
    lastEach: 1,
    indexes: {},
    [Symbol(my)]: true,
    [Symbol(isClean)]: false
  }
}
error Command failed with exit code 1.
```

In other words, tailwind is working great for the majority of classes, but it's consistently failing if we add `animate-pulse` or other animations to our components.

Any help would be greatly appreciated. Happy to dig in here if folks have a sense of what the issue is.</div>

**Comment by adamwathan** [comment] 2022-07-14 11:29
Hey! For issues it's important that they follow the issue template and include an actual reproduction of the problem that we can clone down and troubleshoot. Going to close this since it doesn't meet the requirements outlined in our issue template, but if it's still a problem for you please open a new issue and just include an actual reproduction so we have something to work with ❤️

**Closed by adamwathan** 2022-07-14 11:29 UTC
