### ISSUE TITLE
[v4] Border does not work as expected (breaks backward compatibility)

### ISSUE THREAD

**Issue by surjithctly** [tailwindlabs/tailwindcss#13128] opened 2024-03-07 15:25 UTC
**What version of Tailwind CSS are you using?**

For example: 4.0.0-alpha.5

**What build tool (or framework if it abstracts the build tool) are you using?**

vite ^5.1.5

**What version of Node.js are you using?**

v18.19.0

**What browser are you using?**

Chrome 

**What operating system are you using?**

macOS

**Reproduction URL**

Stackblitz URL not working coz oxide cannot work on browser. 

**Describe your issue**

I added a `border-b` for bottom border only, but it renders a full border. 

```html
 <div class="bg-gray-200 h-14 w-14 border-b border-pink-500"></div>
```

### Result:

**v3 (expected)**

<img width="100" alt="CleanShot 2024-03-07 at 20 50 03@2x" src="https://github.com/tailwindlabs/tailwindcss/assets/1884712/d3c2b6c8-fac4-4234-994a-35a1a3ffc3f5">

**v4 (broken)**

<img width="91" alt="CleanShot 2024-03-07 at 20 53 52@2x" src="https://github.com/tailwindlabs/tailwindcss/assets/1884712/5356853a-38bb-49e8-96d2-b6155e13fa08">

**v4 (after adding `border-b-pink-500` specifically)**

<img width="97" alt="CleanShot 2024-03-07 at 20 54 09@2x" src="https://github.com/tailwindlabs/tailwindcss/assets/1884712/1dc52b1e-88ed-478c-a131-019c8431ab9b">

⚠️ Remember I did not add `border`, I only added `border-b`. If this change is intended, it gonna break 1000s of old tailwind projects.

**Comment by adamwathan** [comment] 2024-03-07 15:27
Hey! Duplicate of https://github.com/tailwindlabs/tailwindcss/issues/13121 and fixed in v4.0.0-alpha.6 which was just released a few minutes ago 👍

**Closed by adamwathan** 2024-03-07 15:27 UTC
