### ISSUE TITLE
'-webkit-text-size-adjust' is not supported by Chrome, Chrome Android, Edge 79+, Firefox, Safari. Add 'text-size-adjust' to support Chrome 54+, Chrome Android 54+, Edge 79+.

### ISSUE THREAD

**Issue by pschaub** [tailwindlabs/tailwindcss#12724] opened 2024-01-06 12:09 UTC
In Microsoft Edge (version 120), you can open the Dev Tools (F12), open the tab "Issues" and see this compatibility error:

> '-webkit-text-size-adjust' is not supported by Chrome, Chrome Android, Edge 79+, Firefox, Safari. Add 'text-size-adjust' to support Chrome 54+, Chrome Android 54+, Edge 79+.

![image](https://github.com/tailwindlabs/tailwindcss/assets/11846736/26b55519-1d47-48a6-b4ab-4db2b6b9e7f4)

### In Tailwind CSS code
https://github.com/tailwindlabs/tailwindcss/blob/fb1743b4b028323d83f5b5f9866ec0f6595fe08c/src/css/preflight.css#L30-L35

**Comment by pschaub** [comment] 2024-01-06 12:10
Should Tailwind CSS add `text-size-adjust` to solve this?

**Comment by adamwathan** [comment] 2024-01-06 14:01
Duplicate of https://github.com/tailwindlabs/tailwindcss/issues/12650

Not sure why Edge says this, because it definitely does support it, here's a screenshot from Edge comparing what it does with a property it doesn't support with a property it does support:

<img width="313" alt="image" src="https://github.com/tailwindlabs/tailwindcss/assets/4323180/126a9a8f-dc78-430a-84b3-a7761ea434d5">

**Closed by adamwathan** 2024-01-06 14:01 UTC

**Comment by RustemZhangazin** [comment] 2024-02-06 10:29
![Uploading IMG_20240206_162718.jpg…]()
![Uploading IMG_20240206_162718.jpg…]()
Text align having issue too

**Comment by alimabrouki** [comment] 2025-06-15 11:03
so what should we do ?
