### ISSUE TITLE
`.prose-invert` is declared before and thus overwritten by prose gray scale modifiers

### ISSUE THREAD

**Issue by mdrbohlav** [tailwindlabs/tailwindcss#9776] opened 2022-11-08 21:35 UTC
**What version of Tailwind CSS are you using?**
3.2.1

**What build tool (or framework if it abstracts the build tool) are you using?**
postcss-cli 8.4.18

**What version of Node.js are you using?**
v16.13.2

**What browser are you using?**
Chrome

**What operating system are you using?**
macOS 13.0

**Describe your issue**
When using `.prose-invert` with any prose gray scale modifier the `.prose-invert` has no effect because it is declared before those modifiers.

**Comment by adamwathan** [comment] 2022-11-08 23:17
Hey! This is a duplicate of https://github.com/tailwindlabs/tailwindcss-typography/issues/228, so let’s just stick with that issue 👍🏻

**Closed by adamwathan** 2022-11-08 23:17 UTC
