### ISSUE TITLE
Shadow does not apply when size is instantiated on hover

### ISSUE THREAD

**Issue by brandonmcconnell** [tailwindlabs/tailwindcss#13450] opened 2024-04-04 22:52 UTC
### What version of Tailwind CSS are you using?

v3.4.3

### What browser are you using?

Chrome v123.0.6312.87 (Official Build) (arm64)

### What operating system are you using?

macOS Sonoma v14.4

### Reproduction URL

https://play.tailwindcss.com/jngJ1mOTKS

### Describe your issue

Changing the size of a shadow does not reveal the shadow if its size is instantiated on hover. My workaround was to show the shadow by default without a variant and hide it when it's not being hovered using a `:not` pseudo selector.

This bug appears to be easily reproducible.

I demonstrate the issue on this Loom as well:
https://www.loom.com/share/585482a718584525a1f3fae5c1a1c4f9?sid=d329fa46-54b6-4811-aa76-93b3053249fa

**Comment by brandonmcconnell** [comment] 2024-04-04 23:03
I can confirm this applies to other variants as well. `sm:shadow-lg` isn't applying either.

**Comment by adamwathan** [comment] 2024-04-05 00:35
Just opened the Play and when I hover the shadow appears:

https://github.com/tailwindlabs/tailwindcss/assets/4323180/b93e01b1-c900-4b0d-85a3-bbe66386cfa7

It's not red, maybe that's what you mean? That's because the shadow size classes all reset the shadow back to their default color, by design at least at the moment because otherwise there's no way to get the default color back once you change it.

**Comment by brandonmcconnell** [comment] 2024-04-05 01:11
Interesting. I'm surprised I've never run into that before. I work with shadows a bunch 😄

@adamwathan Would the best practice then be to apply both the size and color to every state you want to affect, so in this case, `hover:shadow-red-500 hover:shadow-xl`?

This works, I just want to make sure there's no better work around to having the shadow color pre-applied so we can trigger the size when needed.

For example, this would be my naturally expected API (before today), if I needed to cover a lot of states:
```html
<div class="
    hover:shadow-xl
    active:shadow-xl
    focus:shadow-xl
    
    shadow-red-500
"></div>
```

But it looks like we would need to cover both properties for each— is that right? (https://play.tailwindcss.com/P5s42RqtPS)
```html
<div class="
    hover:shadow-xl hover:shadow-red-500
    active:shadow-xl active:shadow-red-500
    focus:shadow-xl focus:shadow-red-500
"></div>
```

I can work with this. I just want to make sure that I'm getting this right before committing that to memory lol

**Comment by adamwathan** [comment] 2024-04-05 01:22
Yeah correct, `shadow-xl` sets the color so you need to add any color override explicitly with the same conditions you use to apply a different shadow size.

This is similar to how `text-sm leading-9 md:text-lg` doesn't preserve `leading-9` because `md:text-lg` overrides the line-height back to the default line-height for that font size utility.

Going to close this one since this is by design 👍

**Closed by adamwathan** 2024-04-05 01:22 UTC

**Comment by brandonmcconnell** [comment] 2024-04-05 02:14
@adamwathan Sweet, thanks for clarifying that
