### ISSUE TITLE
TailwindCSS2 and Nano issue on focus-within, prod build error.

### ISSUE THREAD

**Issue by gregtap** [tailwindlabs/tailwindcss#2856] opened 2020-11-21 15:16 UTC
### Describe the problem:

After upgrading to TailwindCSS2 the `postcss` fails on `Error: Expected an opening square bracket.`

The issue is the line: `  .sm\[focus-within]\:sr-only[focus-within] {`

Without `precss` in `postcss` it builds but the final CSS is missing some classes. 

`    at /home/xxx/common.css:45216:3`
```
  .sm\:not-sr-only {
    position: static;
    width: auto;
    height: auto;
    padding: 0;
    margin: 0;
    overflow: visible;
    clip: auto;
    white-space: normal;
  }

   /* ---> HERE <---- */
  .sm\[focus-within]\:not-sr-only[focus-within] {
    position: static;
    width: auto;
    height: auto;
    padding: 0;
    margin: 0;
    overflow: visible;
    clip: auto;
    white-space: normal;
  }

```

## postcss

```
 module.exports = {
  plugins: {
    'tailwindcss': {},
    'precss': {}, // Lets you use Sass-like markup and staged CSS features in CSS.
    'postcss-import': {}, // This plugin can consume local files, node modules or web_modules. To resolve path of an @import rule
    'postcss-preset-env': {
      browsers: 'last 2 versions',
      stage: 0,
      features: {
        'focus-within-pseudo-class': false // Attempt at fixing build error 
      }
    },
  }
}
```
### Link to a minimal reproduction:

8 files.

https://github.com/SilvrGroup/tailwindbug

**Comment by adamwathan** [comment] 2020-11-22 14:07
Problem here is postcss-preset-env, it uses postcss-focus-within internally and there was a bug there that while fixed on master, still hasn't been published in an updated version of postcss-preset-env:

https://github.com/csstools/postcss-focus-within/issues/3

Weirdly your fix _should_ work by just disabling that plugin, so not sure what's happening there :/

**Comment by adamwathan** [comment] 2020-11-22 14:12
Cloned your project and it seems to build:

![image](https://user-images.githubusercontent.com/4323180/99906017-886b7580-2ca2-11eb-945d-79997ca68d10.png)

I also tried using postcss-cli and can't reproduce it, it builds with no `[focus-within]` stuff in the output.

**Comment by gregtap** [comment] 2020-11-22 14:49
Try `npm run build`

**Comment by adamwathan** [comment] 2020-11-22 14:55
Ah problem is precss also includes postcss-preset-env, so you are running it twice.

https://github.com/jonathantneal/precss/blob/master/package.json#L32

This fixes it:

```js
module.exports = {
  plugins: {
    tailwindcss: {},
    precss: {
      browsers: 'last 2 versions',
      stage: 0,
      features: {
        'focus-within-pseudo-class': false, // Attempt at fixing build error
        // https://github.com/tailwindlabs/tailwindcss/discussions/2462
      },
    }, // Lets you use Sass-like markup and staged CSS features in CSS.
    'postcss-import': {}, // This plugin can consume local files, node modules or web_modules. To resolve path of an @import rule
    'postcss-preset-env': {
      browsers: 'last 2 versions',
      stage: 0,
      features: {
        'focus-within-pseudo-class': false, // Attempt at fixing build error
        // https://github.com/tailwindlabs/tailwindcss/discussions/2462
      },
    },
  },
}
```

...but you have a lot of serious duplication happening since postcss-preset-env is running twice.

You can clean this up a lot, for example postcss-import should always be the first plugin.

I would personally not use precss or postcss-preset-env at all, just use the couple individual plugins you need.

On our projects we literally use nothing, just Tailwind and autoprefixer.

**Closed by adamwathan** 2020-11-22 14:55 UTC

**Comment by gregtap** [comment] 2020-11-22 15:28
Somehow without precss the final CSS (visual) was a bit different than with Tailwind1 where I had precss enabled.

Also without precss the final minified CSS is 3MB.
