### ISSUE TITLE
[v4] including @tailwindcss/vite in plugins breaks css modules in production

### ISSUE THREAD

**Issue by abhishiv** [tailwindlabs/tailwindcss#15147] opened 2024-11-23 21:35 UTC
**What version of Tailwind CSS are you using?**

4.0.0-beta.1

**What build tool (or framework if it abstracts the build tool) are you using?**

@tailwindcss/vite@4.0.0-beta.1 with vite@5.4.11

**What version of Node.js are you using?**

v20.5.0

**What browser are you using?**

Chrome

**What operating system are you using?**

macOS

**Describe your issue**

Following vite.config.js makes vite generate incorrect css class name for css modules

```
  plugins: [tailwindcss()],
  css: {
    postcss: {},
    modules: {
      generateScopedName: "[local]__[hash:base64:5]",
    },
  },
```

Maybe related, but I see following error in production

```

[plugin @tailwindcss/vite:generate:build] Sourcemap is likely to be incorrect: a plugin (@tailwindcss/vite:generate:build) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

**Comment by philipp-spiess** [comment] 2024-11-25 09:44
Hey @abhishiv! Thanks for the report. Do you mind uploading a reproduction repository for us to check out? I was just testing your config in our Vite playground and it seems to work as expected for both dev and production builds:

 
<img width="1277" alt="Screenshot 2024-11-25 at 10 43 07" src="https://github.com/user-attachments/assets/a7504338-b754-4095-8780-c5851099ce2b">

**Comment by Alma219Way** [comment] 2024-11-29 06:25
Hello!
It looks like your Tailwind CSS and Vite setup is generating incorrect CSS class names for modules and causing sourcemap issues. Ensure your dependencies are up to date, verify your vite.config.js for accuracy, and check your sourcemap settings. If the problem persists, consider reviewing the documentation or forums for additional help.

**Comment by philipp-spiess** [comment] 2024-12-05 10:32
@abhishiv Going to close this one for now but if you have a repro that you can share with us, please feel free to reply here or create a new issue, thank you!

**Closed by philipp-spiess** 2024-12-05 10:32 UTC
Labels: needs reproduction, v4, vite
