### ISSUE TITLE
No color opacity utilities for custom extended colors

### ISSUE THREAD

**Issue by Rhjulskov** [tailwindlabs/tailwindcss#4086] opened 2021-04-15 19:16 UTC
### What version of Tailwind CSS are you using?

v.2.1.1

### What build tool (or framework if it abstracts the build tool) are you using?

next.js@10.1.3

### What version of Node.js are you using?

14.15.5

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

-

### Describe your issue

When extending a color in the `tailwind.config.js`, the bg-opacity utilities are not applied.
I can see from your test suite, that you are not expecting to add  " --tw-bg-opacity", so is this what you want, or should there be a way to have custom colors & use this feature? :)

**Comment by adamwathan** [comment] 2021-04-17 18:43
Hey! This definitely works, here's a Tailwind Play example:

https://play.tailwindcss.com/DJakbTsBDP

Closing since no reproduction was provided.

**Closed by adamwathan** 2021-04-17 18:43 UTC

**Comment by Rhjulskov** [comment] 2021-04-20 20:47
@adamwathan  Thank you for elaborating and sorry for me not bringing along an example :)
I've realized my issue was based on using CSS variables in my tailwind config: https://play.tailwindcss.com/gBpT0fnIFE?file=css

I don't know, if that is something you even want to support, but I thought, I'll let you know.
I've inlined the variables and solved it for now. Thank you 👍

**Comment by aryan02420** [comment] 2021-06-28 10:04
https://play.tailwindcss.com/TIRtNQdl4H
this is my workaround

**Comment by adamwathan** [comment] 2021-06-28 12:11
Here's an example from the docs of using CSS variables for custom colors in a way that works with the opacity utilities:

https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo
